// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: assist.proto

package assistv1

import (
	v1 "github.com/fairtier/workspace-api/proto/transformation/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DraftFile is one generated file, path relative to the target repo root.
type DraftFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftFile) Reset() {
	*x = DraftFile{}
	mi := &file_assist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftFile) ProtoMessage() {}

func (x *DraftFile) ProtoReflect() protoreflect.Message {
	mi := &file_assist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftFile.ProtoReflect.Descriptor instead.
func (*DraftFile) Descriptor() ([]byte, []int) {
	return file_assist_proto_rawDescGZIP(), []int{0}
}

func (x *DraftFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DraftFile) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DraftTransformationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Natural-language description, e.g. "Build a daily revenue mart from the
	// stripe charges table".
	Prompt        string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftTransformationRequest) Reset() {
	*x = DraftTransformationRequest{}
	mi := &file_assist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftTransformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftTransformationRequest) ProtoMessage() {}

func (x *DraftTransformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftTransformationRequest.ProtoReflect.Descriptor instead.
func (*DraftTransformationRequest) Descriptor() ([]byte, []int) {
	return file_assist_proto_rawDescGZIP(), []int{1}
}

func (x *DraftTransformationRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type DraftTransformationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pre-filled, validated create request. repo_url and git_credentials are
	// always empty (hosted-repo mode) — the model never drafts repos or
	// secrets — and trigger_after_pipeline_id is left for the user (the model
	// cannot know pipeline IDs).
	Draft *v1.CreateTransformationRequest `protobuf:"bytes,1,opt,name=draft,proto3" json:"draft,omitempty"`
	// Starter dbt files for the hosted repo (models/**.sql + schema.yml),
	// rendered read-only for review; the user commits them via the box repo
	// editor or copy-paste.
	Files []*DraftFile `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	// Short human-readable explanation of the draft and any assumptions made.
	Notes         string `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftTransformationResponse) Reset() {
	*x = DraftTransformationResponse{}
	mi := &file_assist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftTransformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftTransformationResponse) ProtoMessage() {}

func (x *DraftTransformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftTransformationResponse.ProtoReflect.Descriptor instead.
func (*DraftTransformationResponse) Descriptor() ([]byte, []int) {
	return file_assist_proto_rawDescGZIP(), []int{2}
}

func (x *DraftTransformationResponse) GetDraft() *v1.CreateTransformationRequest {
	if x != nil {
		return x.Draft
	}
	return nil
}

func (x *DraftTransformationResponse) GetFiles() []*DraftFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DraftTransformationResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type DraftRillDashboardRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Prompt string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Existing Rill repo paths, sent by the Console so the model references
	// real models/sources instead of inventing them.
	ExistingPaths []string `protobuf:"bytes,2,rep,name=existing_paths,json=existingPaths,proto3" json:"existing_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftRillDashboardRequest) Reset() {
	*x = DraftRillDashboardRequest{}
	mi := &file_assist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftRillDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftRillDashboardRequest) ProtoMessage() {}

func (x *DraftRillDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftRillDashboardRequest.ProtoReflect.Descriptor instead.
func (*DraftRillDashboardRequest) Descriptor() ([]byte, []int) {
	return file_assist_proto_rawDescGZIP(), []int{3}
}

func (x *DraftRillDashboardRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *DraftRillDashboardRequest) GetExistingPaths() []string {
	if x != nil {
		return x.ExistingPaths
	}
	return nil
}

type DraftRillDashboardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Drafted files (metrics/<name>.yaml, dashboards/<name>.yaml, optional
	// models/<name>.sql), YAML-validated server-side.
	Files         []*DraftFile `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Notes         string       `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftRillDashboardResponse) Reset() {
	*x = DraftRillDashboardResponse{}
	mi := &file_assist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftRillDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftRillDashboardResponse) ProtoMessage() {}

func (x *DraftRillDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftRillDashboardResponse.ProtoReflect.Descriptor instead.
func (*DraftRillDashboardResponse) Descriptor() ([]byte, []int) {
	return file_assist_proto_rawDescGZIP(), []int{4}
}

func (x *DraftRillDashboardResponse) GetFiles() []*DraftFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DraftRillDashboardResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

var File_assist_proto protoreflect.FileDescriptor

const file_assist_proto_rawDesc = "" +
	"\n" +
	"\fassist.proto\x12\tassist.v1\x1a\x14transformation.proto\"9\n" +
	"\tDraftFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"4\n" +
	"\x1aDraftTransformationRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"\xa5\x01\n" +
	"\x1bDraftTransformationResponse\x12D\n" +
	"\x05draft\x18\x01 \x01(\v2..transformation.v1.CreateTransformationRequestR\x05draft\x12*\n" +
	"\x05files\x18\x02 \x03(\v2\x14.assist.v1.DraftFileR\x05files\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"Z\n" +
	"\x19DraftRillDashboardRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12%\n" +
	"\x0eexisting_paths\x18\x02 \x03(\tR\rexistingPaths\"^\n" +
	"\x1aDraftRillDashboardResponse\x12*\n" +
	"\x05files\x18\x01 \x03(\v2\x14.assist.v1.DraftFileR\x05files\x12\x14\n" +
	"\x05notes\x18\x02 \x01(\tR\x05notes2\xdc\x01\n" +
	"\rAssistService\x12f\n" +
	"\x13DraftTransformation\x12%.assist.v1.DraftTransformationRequest\x1a&.assist.v1.DraftTransformationResponse\"\x00\x12c\n" +
	"\x12DraftRillDashboard\x12$.assist.v1.DraftRillDashboardRequest\x1a%.assist.v1.DraftRillDashboardResponse\"\x00B<Z:github.com/fairtier/workspace-api/proto/assist/v1;assistv1b\x06proto3"

var (
	file_assist_proto_rawDescOnce sync.Once
	file_assist_proto_rawDescData []byte
)

func file_assist_proto_rawDescGZIP() []byte {
	file_assist_proto_rawDescOnce.Do(func() {
		file_assist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assist_proto_rawDesc), len(file_assist_proto_rawDesc)))
	})
	return file_assist_proto_rawDescData
}

var file_assist_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_assist_proto_goTypes = []any{
	(*DraftFile)(nil),                      // 0: assist.v1.DraftFile
	(*DraftTransformationRequest)(nil),     // 1: assist.v1.DraftTransformationRequest
	(*DraftTransformationResponse)(nil),    // 2: assist.v1.DraftTransformationResponse
	(*DraftRillDashboardRequest)(nil),      // 3: assist.v1.DraftRillDashboardRequest
	(*DraftRillDashboardResponse)(nil),     // 4: assist.v1.DraftRillDashboardResponse
	(*v1.CreateTransformationRequest)(nil), // 5: transformation.v1.CreateTransformationRequest
}
var file_assist_proto_depIdxs = []int32{
	5, // 0: assist.v1.DraftTransformationResponse.draft:type_name -> transformation.v1.CreateTransformationRequest
	0, // 1: assist.v1.DraftTransformationResponse.files:type_name -> assist.v1.DraftFile
	0, // 2: assist.v1.DraftRillDashboardResponse.files:type_name -> assist.v1.DraftFile
	1, // 3: assist.v1.AssistService.DraftTransformation:input_type -> assist.v1.DraftTransformationRequest
	3, // 4: assist.v1.AssistService.DraftRillDashboard:input_type -> assist.v1.DraftRillDashboardRequest
	2, // 5: assist.v1.AssistService.DraftTransformation:output_type -> assist.v1.DraftTransformationResponse
	4, // 6: assist.v1.AssistService.DraftRillDashboard:output_type -> assist.v1.DraftRillDashboardResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_assist_proto_init() }
func file_assist_proto_init() {
	if File_assist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assist_proto_rawDesc), len(file_assist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assist_proto_goTypes,
		DependencyIndexes: file_assist_proto_depIdxs,
		MessageInfos:      file_assist_proto_msgTypes,
	}.Build()
	File_assist_proto = out.File
	file_assist_proto_goTypes = nil
	file_assist_proto_depIdxs = nil
}
