// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: snapshot.proto

package snapshotv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target app: "rill" or "cube".
	App           string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotRequest) Reset() {
	*x = TriggerSnapshotRequest{}
	mi := &file_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotRequest) ProtoMessage() {}

func (x *TriggerSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotRequest.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerSnapshotRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type TriggerSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result status: "created", "unchanged", or "busy".
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// S3 object key of the snapshot archive.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Content hash (SHA-256) of the snapshot.
	Hash          string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotResponse) Reset() {
	*x = TriggerSnapshotResponse{}
	mi := &file_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotResponse) ProtoMessage() {}

func (x *TriggerSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotResponse.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerSnapshotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TriggerSnapshotResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TriggerSnapshotResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ListSnapshotsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target app: "rill" or "cube".
	App           string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *ListSnapshotsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*Snapshot            `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// Snapshot represents a point-in-time capture of an app's project directory.
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// S3 object key of the snapshot archive.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Content hash (SHA-256) of the snapshot.
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// RFC 3339 timestamp when the snapshot was created.
	Timestamp     string `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *Snapshot) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Snapshot) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Snapshot) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_snapshot_proto protoreflect.FileDescriptor

const file_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x0esnapshot.proto\x12\vsnapshot.v1\"*\n" +
	"\x16TriggerSnapshotRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\"W\n" +
	"\x17TriggerSnapshotResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\"(\n" +
	"\x14ListSnapshotsRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\"L\n" +
	"\x15ListSnapshotsResponse\x123\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x15.snapshot.v1.SnapshotR\tsnapshots\"N\n" +
	"\bSnapshot\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp2\xcb\x01\n" +
	"\x0fSnapshotService\x12^\n" +
	"\x0fTriggerSnapshot\x12#.snapshot.v1.TriggerSnapshotRequest\x1a$.snapshot.v1.TriggerSnapshotResponse\"\x00\x12X\n" +
	"\rListSnapshots\x12!.snapshot.v1.ListSnapshotsRequest\x1a\".snapshot.v1.ListSnapshotsResponse\"\x00B@Z>github.com/fairtier/workspace-api/proto/snapshot/v1;snapshotv1b\x06proto3"

var (
	file_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_proto_rawDescData []byte
)

func file_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)))
	})
	return file_snapshot_proto_rawDescData
}

var file_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_snapshot_proto_goTypes = []any{
	(*TriggerSnapshotRequest)(nil),  // 0: snapshot.v1.TriggerSnapshotRequest
	(*TriggerSnapshotResponse)(nil), // 1: snapshot.v1.TriggerSnapshotResponse
	(*ListSnapshotsRequest)(nil),    // 2: snapshot.v1.ListSnapshotsRequest
	(*ListSnapshotsResponse)(nil),   // 3: snapshot.v1.ListSnapshotsResponse
	(*Snapshot)(nil),                // 4: snapshot.v1.Snapshot
}
var file_snapshot_proto_depIdxs = []int32{
	4, // 0: snapshot.v1.ListSnapshotsResponse.snapshots:type_name -> snapshot.v1.Snapshot
	0, // 1: snapshot.v1.SnapshotService.TriggerSnapshot:input_type -> snapshot.v1.TriggerSnapshotRequest
	2, // 2: snapshot.v1.SnapshotService.ListSnapshots:input_type -> snapshot.v1.ListSnapshotsRequest
	1, // 3: snapshot.v1.SnapshotService.TriggerSnapshot:output_type -> snapshot.v1.TriggerSnapshotResponse
	3, // 4: snapshot.v1.SnapshotService.ListSnapshots:output_type -> snapshot.v1.ListSnapshotsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_snapshot_proto_init() }
func file_snapshot_proto_init() {
	if File_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_proto_depIdxs,
		MessageInfos:      file_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_proto = out.File
	file_snapshot_proto_goTypes = nil
	file_snapshot_proto_depIdxs = nil
}
