// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boxrepo.proto

package boxrepov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Repo names are an allowlist — "rill" or "transformations" — not arbitrary
// Gitea repos.
type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_boxrepo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{0}
}

func (x *ListFilesRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type FileEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path relative to the repo root.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Git blob sha of the file content.
	Sha           string `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_boxrepo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{1}
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileEntry           `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_boxrepo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{2}
}

func (x *ListFilesResponse) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_boxrepo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GetFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Sha           string                 `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_boxrepo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetFileResponse) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

type PutFileRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Repo    string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Path    string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Blob sha the edit was based on; empty when creating a new file.
	Sha string `protobuf:"bytes,4,opt,name=sha,proto3" json:"sha,omitempty"`
	// Commit message; a default is used when empty.
	Message       string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileRequest) Reset() {
	*x = PutFileRequest{}
	mi := &file_boxrepo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileRequest) ProtoMessage() {}

func (x *PutFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileRequest.ProtoReflect.Descriptor instead.
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{5}
}

func (x *PutFileRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *PutFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PutFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PutFileRequest) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *PutFileRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PutFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New blob sha after the commit.
	Sha           string `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileResponse) Reset() {
	*x = PutFileResponse{}
	mi := &file_boxrepo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileResponse) ProtoMessage() {}

func (x *PutFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileResponse.ProtoReflect.Descriptor instead.
func (*PutFileResponse) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{6}
}

func (x *PutFileResponse) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

type ListFileHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileHistoryRequest) Reset() {
	*x = ListFileHistoryRequest{}
	mi := &file_boxrepo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileHistoryRequest) ProtoMessage() {}

func (x *ListFileHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListFileHistoryRequest) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{7}
}

func (x *ListFileHistoryRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ListFileHistoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileCommit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full commit sha.
	Sha string `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	// Commit message (first line is the summary).
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Git author of the change — the acting Console user for Console saves,
	// an app/bot identity otherwise (e.g. "Rill Autosave").
	AuthorName  string `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorEmail string `protobuf:"bytes,4,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	// RFC 3339 author time.
	Date          string `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCommit) Reset() {
	*x = FileCommit{}
	mi := &file_boxrepo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCommit) ProtoMessage() {}

func (x *FileCommit) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCommit.ProtoReflect.Descriptor instead.
func (*FileCommit) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{8}
}

func (x *FileCommit) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *FileCommit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileCommit) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *FileCommit) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *FileCommit) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ListFileHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*FileCommit          `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileHistoryResponse) Reset() {
	*x = ListFileHistoryResponse{}
	mi := &file_boxrepo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileHistoryResponse) ProtoMessage() {}

func (x *ListFileHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListFileHistoryResponse) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{9}
}

func (x *ListFileHistoryResponse) GetCommits() []*FileCommit {
	if x != nil {
		return x.Commits
	}
	return nil
}

type GetFileAtRefRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Repo  string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Path  string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Commit sha from ListFileHistory (abbreviated hex accepted).
	Ref           string `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileAtRefRequest) Reset() {
	*x = GetFileAtRefRequest{}
	mi := &file_boxrepo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileAtRefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileAtRefRequest) ProtoMessage() {}

func (x *GetFileAtRefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileAtRefRequest.ProtoReflect.Descriptor instead.
func (*GetFileAtRefRequest) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{10}
}

func (x *GetFileAtRefRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GetFileAtRefRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileAtRefRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type GetFileAtRefResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileAtRefResponse) Reset() {
	*x = GetFileAtRefResponse{}
	mi := &file_boxrepo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileAtRefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileAtRefResponse) ProtoMessage() {}

func (x *GetFileAtRefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileAtRefResponse.ProtoReflect.Descriptor instead.
func (*GetFileAtRefResponse) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileAtRefResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SetPushMirrorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Repo  string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	// HTTPS clone URL of the customer's remote, e.g.
	// https://github.com/acme/analytics.git. Must not embed credentials.
	RemoteUrl string `protobuf:"bytes,2,opt,name=remote_url,json=remoteUrl,proto3" json:"remote_url,omitempty"`
	// Username for the remote (GitHub: the account name or "git";
	// GitLab: "oauth2" for a PAT).
	RemoteUsername string `protobuf:"bytes,3,opt,name=remote_username,json=remoteUsername,proto3" json:"remote_username,omitempty"`
	// Token/password with write access to the remote repo. Passed through to
	// the box's Gitea; never stored or logged centrally.
	RemotePassword string `protobuf:"bytes,4,opt,name=remote_password,json=remotePassword,proto3" json:"remote_password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetPushMirrorRequest) Reset() {
	*x = SetPushMirrorRequest{}
	mi := &file_boxrepo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPushMirrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPushMirrorRequest) ProtoMessage() {}

func (x *SetPushMirrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPushMirrorRequest.ProtoReflect.Descriptor instead.
func (*SetPushMirrorRequest) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{12}
}

func (x *SetPushMirrorRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SetPushMirrorRequest) GetRemoteUrl() string {
	if x != nil {
		return x.RemoteUrl
	}
	return ""
}

func (x *SetPushMirrorRequest) GetRemoteUsername() string {
	if x != nil {
		return x.RemoteUsername
	}
	return ""
}

func (x *SetPushMirrorRequest) GetRemotePassword() string {
	if x != nil {
		return x.RemotePassword
	}
	return ""
}

type SetPushMirrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPushMirrorResponse) Reset() {
	*x = SetPushMirrorResponse{}
	mi := &file_boxrepo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPushMirrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPushMirrorResponse) ProtoMessage() {}

func (x *SetPushMirrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPushMirrorResponse.ProtoReflect.Descriptor instead.
func (*SetPushMirrorResponse) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{13}
}

type GetPushMirrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPushMirrorRequest) Reset() {
	*x = GetPushMirrorRequest{}
	mi := &file_boxrepo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPushMirrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushMirrorRequest) ProtoMessage() {}

func (x *GetPushMirrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushMirrorRequest.ProtoReflect.Descriptor instead.
func (*GetPushMirrorRequest) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{14}
}

func (x *GetPushMirrorRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type GetPushMirrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False when no mirror is configured (other fields are empty).
	Configured bool `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	// Remote URL with any userinfo stripped.
	RemoteUrl string `protobuf:"bytes,2,opt,name=remote_url,json=remoteUrl,proto3" json:"remote_url,omitempty"`
	// RFC 3339 time of the last successful sync (empty if never synced).
	LastUpdate string `protobuf:"bytes,3,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	// Last sync error reported by Gitea (empty when healthy).
	LastError     string `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPushMirrorResponse) Reset() {
	*x = GetPushMirrorResponse{}
	mi := &file_boxrepo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPushMirrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushMirrorResponse) ProtoMessage() {}

func (x *GetPushMirrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushMirrorResponse.ProtoReflect.Descriptor instead.
func (*GetPushMirrorResponse) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{15}
}

func (x *GetPushMirrorResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *GetPushMirrorResponse) GetRemoteUrl() string {
	if x != nil {
		return x.RemoteUrl
	}
	return ""
}

func (x *GetPushMirrorResponse) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

func (x *GetPushMirrorResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type DeletePushMirrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePushMirrorRequest) Reset() {
	*x = DeletePushMirrorRequest{}
	mi := &file_boxrepo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePushMirrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePushMirrorRequest) ProtoMessage() {}

func (x *DeletePushMirrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePushMirrorRequest.ProtoReflect.Descriptor instead.
func (*DeletePushMirrorRequest) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{16}
}

func (x *DeletePushMirrorRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type DeletePushMirrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePushMirrorResponse) Reset() {
	*x = DeletePushMirrorResponse{}
	mi := &file_boxrepo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePushMirrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePushMirrorResponse) ProtoMessage() {}

func (x *DeletePushMirrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePushMirrorResponse.ProtoReflect.Descriptor instead.
func (*DeletePushMirrorResponse) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{17}
}

type SyncPushMirrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPushMirrorRequest) Reset() {
	*x = SyncPushMirrorRequest{}
	mi := &file_boxrepo_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPushMirrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPushMirrorRequest) ProtoMessage() {}

func (x *SyncPushMirrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPushMirrorRequest.ProtoReflect.Descriptor instead.
func (*SyncPushMirrorRequest) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{18}
}

func (x *SyncPushMirrorRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type SyncPushMirrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPushMirrorResponse) Reset() {
	*x = SyncPushMirrorResponse{}
	mi := &file_boxrepo_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPushMirrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPushMirrorResponse) ProtoMessage() {}

func (x *SyncPushMirrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxrepo_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPushMirrorResponse.ProtoReflect.Descriptor instead.
func (*SyncPushMirrorResponse) Descriptor() ([]byte, []int) {
	return file_boxrepo_proto_rawDescGZIP(), []int{19}
}

var File_boxrepo_proto protoreflect.FileDescriptor

const file_boxrepo_proto_rawDesc = "" +
	"\n" +
	"\rboxrepo.proto\x12\n" +
	"boxrepo.v1\"&\n" +
	"\x10ListFilesRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\"1\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x10\n" +
	"\x03sha\x18\x02 \x01(\tR\x03sha\"@\n" +
	"\x11ListFilesResponse\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.boxrepo.v1.FileEntryR\x05files\"8\n" +
	"\x0eGetFileRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"=\n" +
	"\x0fGetFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x10\n" +
	"\x03sha\x18\x02 \x01(\tR\x03sha\"~\n" +
	"\x0ePutFileRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x10\n" +
	"\x03sha\x18\x04 \x01(\tR\x03sha\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"#\n" +
	"\x0fPutFileResponse\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\"@\n" +
	"\x16ListFileHistoryRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x90\x01\n" +
	"\n" +
	"FileCommit\x12\x10\n" +
	"\x03sha\x18\x01 \x01(\tR\x03sha\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\x04 \x01(\tR\vauthorEmail\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\"K\n" +
	"\x17ListFileHistoryResponse\x120\n" +
	"\acommits\x18\x01 \x03(\v2\x16.boxrepo.v1.FileCommitR\acommits\"O\n" +
	"\x13GetFileAtRefRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\"0\n" +
	"\x14GetFileAtRefResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\x9b\x01\n" +
	"\x14SetPushMirrorRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1d\n" +
	"\n" +
	"remote_url\x18\x02 \x01(\tR\tremoteUrl\x12'\n" +
	"\x0fremote_username\x18\x03 \x01(\tR\x0eremoteUsername\x12'\n" +
	"\x0fremote_password\x18\x04 \x01(\tR\x0eremotePassword\"\x17\n" +
	"\x15SetPushMirrorResponse\"*\n" +
	"\x14GetPushMirrorRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\"\x96\x01\n" +
	"\x15GetPushMirrorResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x1d\n" +
	"\n" +
	"remote_url\x18\x02 \x01(\tR\tremoteUrl\x12\x1f\n" +
	"\vlast_update\x18\x03 \x01(\tR\n" +
	"lastUpdate\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"-\n" +
	"\x17DeletePushMirrorRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\"\x1a\n" +
	"\x18DeletePushMirrorResponse\"+\n" +
	"\x15SyncPushMirrorRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\"\x18\n" +
	"\x16SyncPushMirrorResponse2\x87\x06\n" +
	"\x0eBoxRepoService\x12J\n" +
	"\tListFiles\x12\x1c.boxrepo.v1.ListFilesRequest\x1a\x1d.boxrepo.v1.ListFilesResponse\"\x00\x12D\n" +
	"\aGetFile\x12\x1a.boxrepo.v1.GetFileRequest\x1a\x1b.boxrepo.v1.GetFileResponse\"\x00\x12D\n" +
	"\aPutFile\x12\x1a.boxrepo.v1.PutFileRequest\x1a\x1b.boxrepo.v1.PutFileResponse\"\x00\x12\\\n" +
	"\x0fListFileHistory\x12\".boxrepo.v1.ListFileHistoryRequest\x1a#.boxrepo.v1.ListFileHistoryResponse\"\x00\x12S\n" +
	"\fGetFileAtRef\x12\x1f.boxrepo.v1.GetFileAtRefRequest\x1a .boxrepo.v1.GetFileAtRefResponse\"\x00\x12V\n" +
	"\rSetPushMirror\x12 .boxrepo.v1.SetPushMirrorRequest\x1a!.boxrepo.v1.SetPushMirrorResponse\"\x00\x12V\n" +
	"\rGetPushMirror\x12 .boxrepo.v1.GetPushMirrorRequest\x1a!.boxrepo.v1.GetPushMirrorResponse\"\x00\x12_\n" +
	"\x10DeletePushMirror\x12#.boxrepo.v1.DeletePushMirrorRequest\x1a$.boxrepo.v1.DeletePushMirrorResponse\"\x00\x12Y\n" +
	"\x0eSyncPushMirror\x12!.boxrepo.v1.SyncPushMirrorRequest\x1a\".boxrepo.v1.SyncPushMirrorResponse\"\x00B>Z<github.com/fairtier/workspace-api/proto/boxrepo/v1;boxrepov1b\x06proto3"

var (
	file_boxrepo_proto_rawDescOnce sync.Once
	file_boxrepo_proto_rawDescData []byte
)

func file_boxrepo_proto_rawDescGZIP() []byte {
	file_boxrepo_proto_rawDescOnce.Do(func() {
		file_boxrepo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boxrepo_proto_rawDesc), len(file_boxrepo_proto_rawDesc)))
	})
	return file_boxrepo_proto_rawDescData
}

var file_boxrepo_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_boxrepo_proto_goTypes = []any{
	(*ListFilesRequest)(nil),         // 0: boxrepo.v1.ListFilesRequest
	(*FileEntry)(nil),                // 1: boxrepo.v1.FileEntry
	(*ListFilesResponse)(nil),        // 2: boxrepo.v1.ListFilesResponse
	(*GetFileRequest)(nil),           // 3: boxrepo.v1.GetFileRequest
	(*GetFileResponse)(nil),          // 4: boxrepo.v1.GetFileResponse
	(*PutFileRequest)(nil),           // 5: boxrepo.v1.PutFileRequest
	(*PutFileResponse)(nil),          // 6: boxrepo.v1.PutFileResponse
	(*ListFileHistoryRequest)(nil),   // 7: boxrepo.v1.ListFileHistoryRequest
	(*FileCommit)(nil),               // 8: boxrepo.v1.FileCommit
	(*ListFileHistoryResponse)(nil),  // 9: boxrepo.v1.ListFileHistoryResponse
	(*GetFileAtRefRequest)(nil),      // 10: boxrepo.v1.GetFileAtRefRequest
	(*GetFileAtRefResponse)(nil),     // 11: boxrepo.v1.GetFileAtRefResponse
	(*SetPushMirrorRequest)(nil),     // 12: boxrepo.v1.SetPushMirrorRequest
	(*SetPushMirrorResponse)(nil),    // 13: boxrepo.v1.SetPushMirrorResponse
	(*GetPushMirrorRequest)(nil),     // 14: boxrepo.v1.GetPushMirrorRequest
	(*GetPushMirrorResponse)(nil),    // 15: boxrepo.v1.GetPushMirrorResponse
	(*DeletePushMirrorRequest)(nil),  // 16: boxrepo.v1.DeletePushMirrorRequest
	(*DeletePushMirrorResponse)(nil), // 17: boxrepo.v1.DeletePushMirrorResponse
	(*SyncPushMirrorRequest)(nil),    // 18: boxrepo.v1.SyncPushMirrorRequest
	(*SyncPushMirrorResponse)(nil),   // 19: boxrepo.v1.SyncPushMirrorResponse
}
var file_boxrepo_proto_depIdxs = []int32{
	1,  // 0: boxrepo.v1.ListFilesResponse.files:type_name -> boxrepo.v1.FileEntry
	8,  // 1: boxrepo.v1.ListFileHistoryResponse.commits:type_name -> boxrepo.v1.FileCommit
	0,  // 2: boxrepo.v1.BoxRepoService.ListFiles:input_type -> boxrepo.v1.ListFilesRequest
	3,  // 3: boxrepo.v1.BoxRepoService.GetFile:input_type -> boxrepo.v1.GetFileRequest
	5,  // 4: boxrepo.v1.BoxRepoService.PutFile:input_type -> boxrepo.v1.PutFileRequest
	7,  // 5: boxrepo.v1.BoxRepoService.ListFileHistory:input_type -> boxrepo.v1.ListFileHistoryRequest
	10, // 6: boxrepo.v1.BoxRepoService.GetFileAtRef:input_type -> boxrepo.v1.GetFileAtRefRequest
	12, // 7: boxrepo.v1.BoxRepoService.SetPushMirror:input_type -> boxrepo.v1.SetPushMirrorRequest
	14, // 8: boxrepo.v1.BoxRepoService.GetPushMirror:input_type -> boxrepo.v1.GetPushMirrorRequest
	16, // 9: boxrepo.v1.BoxRepoService.DeletePushMirror:input_type -> boxrepo.v1.DeletePushMirrorRequest
	18, // 10: boxrepo.v1.BoxRepoService.SyncPushMirror:input_type -> boxrepo.v1.SyncPushMirrorRequest
	2,  // 11: boxrepo.v1.BoxRepoService.ListFiles:output_type -> boxrepo.v1.ListFilesResponse
	4,  // 12: boxrepo.v1.BoxRepoService.GetFile:output_type -> boxrepo.v1.GetFileResponse
	6,  // 13: boxrepo.v1.BoxRepoService.PutFile:output_type -> boxrepo.v1.PutFileResponse
	9,  // 14: boxrepo.v1.BoxRepoService.ListFileHistory:output_type -> boxrepo.v1.ListFileHistoryResponse
	11, // 15: boxrepo.v1.BoxRepoService.GetFileAtRef:output_type -> boxrepo.v1.GetFileAtRefResponse
	13, // 16: boxrepo.v1.BoxRepoService.SetPushMirror:output_type -> boxrepo.v1.SetPushMirrorResponse
	15, // 17: boxrepo.v1.BoxRepoService.GetPushMirror:output_type -> boxrepo.v1.GetPushMirrorResponse
	17, // 18: boxrepo.v1.BoxRepoService.DeletePushMirror:output_type -> boxrepo.v1.DeletePushMirrorResponse
	19, // 19: boxrepo.v1.BoxRepoService.SyncPushMirror:output_type -> boxrepo.v1.SyncPushMirrorResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_boxrepo_proto_init() }
func file_boxrepo_proto_init() {
	if File_boxrepo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boxrepo_proto_rawDesc), len(file_boxrepo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boxrepo_proto_goTypes,
		DependencyIndexes: file_boxrepo_proto_depIdxs,
		MessageInfos:      file_boxrepo_proto_msgTypes,
	}.Build()
	File_boxrepo_proto = out.File
	file_boxrepo_proto_goTypes = nil
	file_boxrepo_proto_depIdxs = nil
}
