// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pipeline_assist.proto

package pipelineassistv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fairtier/workspace-api/proto/pipeline_assist/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PipelineAssistServiceName is the fully-qualified name of the PipelineAssistService service.
	PipelineAssistServiceName = "pipeline_assist.v1.PipelineAssistService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PipelineAssistServiceDraftPipelineProcedure is the fully-qualified name of the
	// PipelineAssistService's DraftPipeline RPC.
	PipelineAssistServiceDraftPipelineProcedure = "/pipeline_assist.v1.PipelineAssistService/DraftPipeline"
)

// PipelineAssistServiceClient is a client for the pipeline_assist.v1.PipelineAssistService service.
type PipelineAssistServiceClient interface {
	// DraftPipeline turns a natural-language prompt into a draft pipeline
	// configuration. Returns INVALID_ARGUMENT (with ValidationErrors details)
	// when the drafted source_config fails schema validation, and UNIMPLEMENTED
	// when AI drafting is not configured on the server.
	DraftPipeline(context.Context, *connect.Request[v1.DraftPipelineRequest]) (*connect.Response[v1.DraftPipelineResponse], error)
}

// NewPipelineAssistServiceClient constructs a client for the
// pipeline_assist.v1.PipelineAssistService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPipelineAssistServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PipelineAssistServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pipelineAssistServiceMethods := v1.File_pipeline_assist_proto.Services().ByName("PipelineAssistService").Methods()
	return &pipelineAssistServiceClient{
		draftPipeline: connect.NewClient[v1.DraftPipelineRequest, v1.DraftPipelineResponse](
			httpClient,
			baseURL+PipelineAssistServiceDraftPipelineProcedure,
			connect.WithSchema(pipelineAssistServiceMethods.ByName("DraftPipeline")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pipelineAssistServiceClient implements PipelineAssistServiceClient.
type pipelineAssistServiceClient struct {
	draftPipeline *connect.Client[v1.DraftPipelineRequest, v1.DraftPipelineResponse]
}

// DraftPipeline calls pipeline_assist.v1.PipelineAssistService.DraftPipeline.
func (c *pipelineAssistServiceClient) DraftPipeline(ctx context.Context, req *connect.Request[v1.DraftPipelineRequest]) (*connect.Response[v1.DraftPipelineResponse], error) {
	return c.draftPipeline.CallUnary(ctx, req)
}

// PipelineAssistServiceHandler is an implementation of the pipeline_assist.v1.PipelineAssistService
// service.
type PipelineAssistServiceHandler interface {
	// DraftPipeline turns a natural-language prompt into a draft pipeline
	// configuration. Returns INVALID_ARGUMENT (with ValidationErrors details)
	// when the drafted source_config fails schema validation, and UNIMPLEMENTED
	// when AI drafting is not configured on the server.
	DraftPipeline(context.Context, *connect.Request[v1.DraftPipelineRequest]) (*connect.Response[v1.DraftPipelineResponse], error)
}

// NewPipelineAssistServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPipelineAssistServiceHandler(svc PipelineAssistServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pipelineAssistServiceMethods := v1.File_pipeline_assist_proto.Services().ByName("PipelineAssistService").Methods()
	pipelineAssistServiceDraftPipelineHandler := connect.NewUnaryHandler(
		PipelineAssistServiceDraftPipelineProcedure,
		svc.DraftPipeline,
		connect.WithSchema(pipelineAssistServiceMethods.ByName("DraftPipeline")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pipeline_assist.v1.PipelineAssistService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PipelineAssistServiceDraftPipelineProcedure:
			pipelineAssistServiceDraftPipelineHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPipelineAssistServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPipelineAssistServiceHandler struct{}

func (UnimplementedPipelineAssistServiceHandler) DraftPipeline(context.Context, *connect.Request[v1.DraftPipelineRequest]) (*connect.Response[v1.DraftPipelineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline_assist.v1.PipelineAssistService.DraftPipeline is not implemented"))
}
