// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: connection.proto

package connectionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fairtier/workspace-api/proto/connection/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConnectionServiceName is the fully-qualified name of the ConnectionService service.
	ConnectionServiceName = "connection.v1.ConnectionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConnectionServiceListConnectionsProcedure is the fully-qualified name of the ConnectionService's
	// ListConnections RPC.
	ConnectionServiceListConnectionsProcedure = "/connection.v1.ConnectionService/ListConnections"
	// ConnectionServiceCreateConnectionProcedure is the fully-qualified name of the ConnectionService's
	// CreateConnection RPC.
	ConnectionServiceCreateConnectionProcedure = "/connection.v1.ConnectionService/CreateConnection"
	// ConnectionServiceDeleteConnectionProcedure is the fully-qualified name of the ConnectionService's
	// DeleteConnection RPC.
	ConnectionServiceDeleteConnectionProcedure = "/connection.v1.ConnectionService/DeleteConnection"
)

// ConnectionServiceClient is a client for the connection.v1.ConnectionService service.
type ConnectionServiceClient interface {
	// ListConnections returns the workspace's connections, newest first.
	ListConnections(context.Context, *connect.Request[v1.ListConnectionsRequest]) (*connect.Response[v1.ListConnectionsResponse], error)
	// CreateConnection creates a connection from a provider-specific source.
	// For Google, the source is a grant_id from the "Sign in with Google"
	// popup — one-time use, minted by /oauth/google/callback.
	//
	// Re-authorizing an account that is already connected UPDATES that
	// connection in place and returns it, keeping its id: reconnecting is the
	// documented fix for an expired or app-rotated grant, so it must not be the
	// one thing the API refuses. Identity is the granting account, not the
	// display name. ALREADY_EXISTS is therefore reserved for a genuine clash —
	// an explicit name already taken by a different account.
	CreateConnection(context.Context, *connect.Request[v1.CreateConnectionRequest]) (*connect.Response[v1.CreateConnectionResponse], error)
	// DeleteConnection removes a connection. Refused with FailedPrecondition
	// while a pipeline still references it — detach or delete those first.
	// The box engine's minted token expires on its own shortly after.
	DeleteConnection(context.Context, *connect.Request[v1.DeleteConnectionRequest]) (*connect.Response[v1.DeleteConnectionResponse], error)
}

// NewConnectionServiceClient constructs a client for the connection.v1.ConnectionService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConnectionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConnectionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	connectionServiceMethods := v1.File_connection_proto.Services().ByName("ConnectionService").Methods()
	return &connectionServiceClient{
		listConnections: connect.NewClient[v1.ListConnectionsRequest, v1.ListConnectionsResponse](
			httpClient,
			baseURL+ConnectionServiceListConnectionsProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("ListConnections")),
			connect.WithClientOptions(opts...),
		),
		createConnection: connect.NewClient[v1.CreateConnectionRequest, v1.CreateConnectionResponse](
			httpClient,
			baseURL+ConnectionServiceCreateConnectionProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("CreateConnection")),
			connect.WithClientOptions(opts...),
		),
		deleteConnection: connect.NewClient[v1.DeleteConnectionRequest, v1.DeleteConnectionResponse](
			httpClient,
			baseURL+ConnectionServiceDeleteConnectionProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("DeleteConnection")),
			connect.WithClientOptions(opts...),
		),
	}
}

// connectionServiceClient implements ConnectionServiceClient.
type connectionServiceClient struct {
	listConnections  *connect.Client[v1.ListConnectionsRequest, v1.ListConnectionsResponse]
	createConnection *connect.Client[v1.CreateConnectionRequest, v1.CreateConnectionResponse]
	deleteConnection *connect.Client[v1.DeleteConnectionRequest, v1.DeleteConnectionResponse]
}

// ListConnections calls connection.v1.ConnectionService.ListConnections.
func (c *connectionServiceClient) ListConnections(ctx context.Context, req *connect.Request[v1.ListConnectionsRequest]) (*connect.Response[v1.ListConnectionsResponse], error) {
	return c.listConnections.CallUnary(ctx, req)
}

// CreateConnection calls connection.v1.ConnectionService.CreateConnection.
func (c *connectionServiceClient) CreateConnection(ctx context.Context, req *connect.Request[v1.CreateConnectionRequest]) (*connect.Response[v1.CreateConnectionResponse], error) {
	return c.createConnection.CallUnary(ctx, req)
}

// DeleteConnection calls connection.v1.ConnectionService.DeleteConnection.
func (c *connectionServiceClient) DeleteConnection(ctx context.Context, req *connect.Request[v1.DeleteConnectionRequest]) (*connect.Response[v1.DeleteConnectionResponse], error) {
	return c.deleteConnection.CallUnary(ctx, req)
}

// ConnectionServiceHandler is an implementation of the connection.v1.ConnectionService service.
type ConnectionServiceHandler interface {
	// ListConnections returns the workspace's connections, newest first.
	ListConnections(context.Context, *connect.Request[v1.ListConnectionsRequest]) (*connect.Response[v1.ListConnectionsResponse], error)
	// CreateConnection creates a connection from a provider-specific source.
	// For Google, the source is a grant_id from the "Sign in with Google"
	// popup — one-time use, minted by /oauth/google/callback.
	//
	// Re-authorizing an account that is already connected UPDATES that
	// connection in place and returns it, keeping its id: reconnecting is the
	// documented fix for an expired or app-rotated grant, so it must not be the
	// one thing the API refuses. Identity is the granting account, not the
	// display name. ALREADY_EXISTS is therefore reserved for a genuine clash —
	// an explicit name already taken by a different account.
	CreateConnection(context.Context, *connect.Request[v1.CreateConnectionRequest]) (*connect.Response[v1.CreateConnectionResponse], error)
	// DeleteConnection removes a connection. Refused with FailedPrecondition
	// while a pipeline still references it — detach or delete those first.
	// The box engine's minted token expires on its own shortly after.
	DeleteConnection(context.Context, *connect.Request[v1.DeleteConnectionRequest]) (*connect.Response[v1.DeleteConnectionResponse], error)
}

// NewConnectionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConnectionServiceHandler(svc ConnectionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	connectionServiceMethods := v1.File_connection_proto.Services().ByName("ConnectionService").Methods()
	connectionServiceListConnectionsHandler := connect.NewUnaryHandler(
		ConnectionServiceListConnectionsProcedure,
		svc.ListConnections,
		connect.WithSchema(connectionServiceMethods.ByName("ListConnections")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceCreateConnectionHandler := connect.NewUnaryHandler(
		ConnectionServiceCreateConnectionProcedure,
		svc.CreateConnection,
		connect.WithSchema(connectionServiceMethods.ByName("CreateConnection")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceDeleteConnectionHandler := connect.NewUnaryHandler(
		ConnectionServiceDeleteConnectionProcedure,
		svc.DeleteConnection,
		connect.WithSchema(connectionServiceMethods.ByName("DeleteConnection")),
		connect.WithHandlerOptions(opts...),
	)
	return "/connection.v1.ConnectionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConnectionServiceListConnectionsProcedure:
			connectionServiceListConnectionsHandler.ServeHTTP(w, r)
		case ConnectionServiceCreateConnectionProcedure:
			connectionServiceCreateConnectionHandler.ServeHTTP(w, r)
		case ConnectionServiceDeleteConnectionProcedure:
			connectionServiceDeleteConnectionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConnectionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConnectionServiceHandler struct{}

func (UnimplementedConnectionServiceHandler) ListConnections(context.Context, *connect.Request[v1.ListConnectionsRequest]) (*connect.Response[v1.ListConnectionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connection.v1.ConnectionService.ListConnections is not implemented"))
}

func (UnimplementedConnectionServiceHandler) CreateConnection(context.Context, *connect.Request[v1.CreateConnectionRequest]) (*connect.Response[v1.CreateConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connection.v1.ConnectionService.CreateConnection is not implemented"))
}

func (UnimplementedConnectionServiceHandler) DeleteConnection(context.Context, *connect.Request[v1.DeleteConnectionRequest]) (*connect.Response[v1.DeleteConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connection.v1.ConnectionService.DeleteConnection is not implemented"))
}
