// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: lakekeeper_user.proto

package lakekeeperuserv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fairtier/workspace-api/proto/lakekeeper_user/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LakekeeperUserServiceName is the fully-qualified name of the LakekeeperUserService service.
	LakekeeperUserServiceName = "lakekeeper_user.v1.LakekeeperUserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LakekeeperUserServiceAddUserProcedure is the fully-qualified name of the LakekeeperUserService's
	// AddUser RPC.
	LakekeeperUserServiceAddUserProcedure = "/lakekeeper_user.v1.LakekeeperUserService/AddUser"
	// LakekeeperUserServiceRemoveUserProcedure is the fully-qualified name of the
	// LakekeeperUserService's RemoveUser RPC.
	LakekeeperUserServiceRemoveUserProcedure = "/lakekeeper_user.v1.LakekeeperUserService/RemoveUser"
	// LakekeeperUserServiceListUsersProcedure is the fully-qualified name of the
	// LakekeeperUserService's ListUsers RPC.
	LakekeeperUserServiceListUsersProcedure = "/lakekeeper_user.v1.LakekeeperUserService/ListUsers"
)

// LakekeeperUserServiceClient is a client for the lakekeeper_user.v1.LakekeeperUserService service.
type LakekeeperUserServiceClient interface {
	// AddUser creates a new data platform service account with the specified role
	// and warehouse access. Returns OAuth2 client credentials (the client_secret
	// is shown only once).
	AddUser(context.Context, *connect.Request[v1.AddUserRequest]) (*connect.Response[v1.AddUserResponse], error)
	// RemoveUser deletes a data platform service account and revokes its
	// Lakekeeper access.
	RemoveUser(context.Context, *connect.Request[v1.RemoveUserRequest]) (*connect.Response[v1.RemoveUserResponse], error)
	// ListUsers returns all data platform service accounts for the tenant.
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
}

// NewLakekeeperUserServiceClient constructs a client for the
// lakekeeper_user.v1.LakekeeperUserService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLakekeeperUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LakekeeperUserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lakekeeperUserServiceMethods := v1.File_lakekeeper_user_proto.Services().ByName("LakekeeperUserService").Methods()
	return &lakekeeperUserServiceClient{
		addUser: connect.NewClient[v1.AddUserRequest, v1.AddUserResponse](
			httpClient,
			baseURL+LakekeeperUserServiceAddUserProcedure,
			connect.WithSchema(lakekeeperUserServiceMethods.ByName("AddUser")),
			connect.WithClientOptions(opts...),
		),
		removeUser: connect.NewClient[v1.RemoveUserRequest, v1.RemoveUserResponse](
			httpClient,
			baseURL+LakekeeperUserServiceRemoveUserProcedure,
			connect.WithSchema(lakekeeperUserServiceMethods.ByName("RemoveUser")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[v1.ListUsersRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+LakekeeperUserServiceListUsersProcedure,
			connect.WithSchema(lakekeeperUserServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lakekeeperUserServiceClient implements LakekeeperUserServiceClient.
type lakekeeperUserServiceClient struct {
	addUser    *connect.Client[v1.AddUserRequest, v1.AddUserResponse]
	removeUser *connect.Client[v1.RemoveUserRequest, v1.RemoveUserResponse]
	listUsers  *connect.Client[v1.ListUsersRequest, v1.ListUsersResponse]
}

// AddUser calls lakekeeper_user.v1.LakekeeperUserService.AddUser.
func (c *lakekeeperUserServiceClient) AddUser(ctx context.Context, req *connect.Request[v1.AddUserRequest]) (*connect.Response[v1.AddUserResponse], error) {
	return c.addUser.CallUnary(ctx, req)
}

// RemoveUser calls lakekeeper_user.v1.LakekeeperUserService.RemoveUser.
func (c *lakekeeperUserServiceClient) RemoveUser(ctx context.Context, req *connect.Request[v1.RemoveUserRequest]) (*connect.Response[v1.RemoveUserResponse], error) {
	return c.removeUser.CallUnary(ctx, req)
}

// ListUsers calls lakekeeper_user.v1.LakekeeperUserService.ListUsers.
func (c *lakekeeperUserServiceClient) ListUsers(ctx context.Context, req *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// LakekeeperUserServiceHandler is an implementation of the lakekeeper_user.v1.LakekeeperUserService
// service.
type LakekeeperUserServiceHandler interface {
	// AddUser creates a new data platform service account with the specified role
	// and warehouse access. Returns OAuth2 client credentials (the client_secret
	// is shown only once).
	AddUser(context.Context, *connect.Request[v1.AddUserRequest]) (*connect.Response[v1.AddUserResponse], error)
	// RemoveUser deletes a data platform service account and revokes its
	// Lakekeeper access.
	RemoveUser(context.Context, *connect.Request[v1.RemoveUserRequest]) (*connect.Response[v1.RemoveUserResponse], error)
	// ListUsers returns all data platform service accounts for the tenant.
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
}

// NewLakekeeperUserServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLakekeeperUserServiceHandler(svc LakekeeperUserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lakekeeperUserServiceMethods := v1.File_lakekeeper_user_proto.Services().ByName("LakekeeperUserService").Methods()
	lakekeeperUserServiceAddUserHandler := connect.NewUnaryHandler(
		LakekeeperUserServiceAddUserProcedure,
		svc.AddUser,
		connect.WithSchema(lakekeeperUserServiceMethods.ByName("AddUser")),
		connect.WithHandlerOptions(opts...),
	)
	lakekeeperUserServiceRemoveUserHandler := connect.NewUnaryHandler(
		LakekeeperUserServiceRemoveUserProcedure,
		svc.RemoveUser,
		connect.WithSchema(lakekeeperUserServiceMethods.ByName("RemoveUser")),
		connect.WithHandlerOptions(opts...),
	)
	lakekeeperUserServiceListUsersHandler := connect.NewUnaryHandler(
		LakekeeperUserServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(lakekeeperUserServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/lakekeeper_user.v1.LakekeeperUserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LakekeeperUserServiceAddUserProcedure:
			lakekeeperUserServiceAddUserHandler.ServeHTTP(w, r)
		case LakekeeperUserServiceRemoveUserProcedure:
			lakekeeperUserServiceRemoveUserHandler.ServeHTTP(w, r)
		case LakekeeperUserServiceListUsersProcedure:
			lakekeeperUserServiceListUsersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLakekeeperUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLakekeeperUserServiceHandler struct{}

func (UnimplementedLakekeeperUserServiceHandler) AddUser(context.Context, *connect.Request[v1.AddUserRequest]) (*connect.Response[v1.AddUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lakekeeper_user.v1.LakekeeperUserService.AddUser is not implemented"))
}

func (UnimplementedLakekeeperUserServiceHandler) RemoveUser(context.Context, *connect.Request[v1.RemoveUserRequest]) (*connect.Response[v1.RemoveUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lakekeeper_user.v1.LakekeeperUserService.RemoveUser is not implemented"))
}

func (UnimplementedLakekeeperUserServiceHandler) ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lakekeeper_user.v1.LakekeeperUserService.ListUsers is not implemented"))
}
