// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: assist.proto

package assistv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fairtier/workspace-api/proto/assist/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AssistServiceName is the fully-qualified name of the AssistService service.
	AssistServiceName = "assist.v1.AssistService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AssistServiceDraftTransformationProcedure is the fully-qualified name of the AssistService's
	// DraftTransformation RPC.
	AssistServiceDraftTransformationProcedure = "/assist.v1.AssistService/DraftTransformation"
	// AssistServiceDraftRillDashboardProcedure is the fully-qualified name of the AssistService's
	// DraftRillDashboard RPC.
	AssistServiceDraftRillDashboardProcedure = "/assist.v1.AssistService/DraftRillDashboard"
	// AssistServiceDraftSqlProcedure is the fully-qualified name of the AssistService's DraftSql RPC.
	AssistServiceDraftSqlProcedure = "/assist.v1.AssistService/DraftSql"
	// AssistServiceExplainErrorProcedure is the fully-qualified name of the AssistService's
	// ExplainError RPC.
	AssistServiceExplainErrorProcedure = "/assist.v1.AssistService/ExplainError"
)

// AssistServiceClient is a client for the assist.v1.AssistService service.
type AssistServiceClient interface {
	// DraftTransformation turns a natural-language prompt into a draft dbt
	// transformation: a pre-filled CreateTransformation request (hosted-repo
	// mode) plus starter model files the user reviews and commits themselves.
	DraftTransformation(context.Context, *connect.Request[v1.DraftTransformationRequest]) (*connect.Response[v1.DraftTransformationResponse], error)
	// DraftRillDashboard turns a natural-language prompt into draft Rill
	// project files (metrics views, explore dashboards, optional models),
	// opened as unsaved buffers in the Console's Rill editor.
	DraftRillDashboard(context.Context, *connect.Request[v1.DraftRillDashboardRequest]) (*connect.Response[v1.DraftRillDashboardResponse], error)
	// DraftSql turns a natural-language request into one read-only DuckDB
	// query. The server assembles the schema context from the caller's own
	// warehouse (all table names, column detail for the most relevant few) and
	// validates the draft with EXPLAIN best-effort — a statement the engine
	// rejects still comes back, with the engine's message in notes. The draft
	// is inserted into the editor, NEVER executed automatically.
	DraftSql(context.Context, *connect.Request[v1.DraftSqlRequest]) (*connect.Response[v1.DraftSqlResponse], error)
	// ExplainError explains one failure in plain language. For pipeline and
	// transformation runs the client sends only ids — the server assembles the
	// trusted context from the caller's own rows (config without credentials,
	// run status, the stored error text) so nothing client-supplied poses as
	// trusted data. The SQL target is the exception: the editor's SQL and
	// engine error are client-supplied because the server keeps no query
	// history.
	ExplainError(context.Context, *connect.Request[v1.ExplainErrorRequest]) (*connect.Response[v1.ExplainErrorResponse], error)
}

// NewAssistServiceClient constructs a client for the assist.v1.AssistService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAssistServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AssistServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	assistServiceMethods := v1.File_assist_proto.Services().ByName("AssistService").Methods()
	return &assistServiceClient{
		draftTransformation: connect.NewClient[v1.DraftTransformationRequest, v1.DraftTransformationResponse](
			httpClient,
			baseURL+AssistServiceDraftTransformationProcedure,
			connect.WithSchema(assistServiceMethods.ByName("DraftTransformation")),
			connect.WithClientOptions(opts...),
		),
		draftRillDashboard: connect.NewClient[v1.DraftRillDashboardRequest, v1.DraftRillDashboardResponse](
			httpClient,
			baseURL+AssistServiceDraftRillDashboardProcedure,
			connect.WithSchema(assistServiceMethods.ByName("DraftRillDashboard")),
			connect.WithClientOptions(opts...),
		),
		draftSql: connect.NewClient[v1.DraftSqlRequest, v1.DraftSqlResponse](
			httpClient,
			baseURL+AssistServiceDraftSqlProcedure,
			connect.WithSchema(assistServiceMethods.ByName("DraftSql")),
			connect.WithClientOptions(opts...),
		),
		explainError: connect.NewClient[v1.ExplainErrorRequest, v1.ExplainErrorResponse](
			httpClient,
			baseURL+AssistServiceExplainErrorProcedure,
			connect.WithSchema(assistServiceMethods.ByName("ExplainError")),
			connect.WithClientOptions(opts...),
		),
	}
}

// assistServiceClient implements AssistServiceClient.
type assistServiceClient struct {
	draftTransformation *connect.Client[v1.DraftTransformationRequest, v1.DraftTransformationResponse]
	draftRillDashboard  *connect.Client[v1.DraftRillDashboardRequest, v1.DraftRillDashboardResponse]
	draftSql            *connect.Client[v1.DraftSqlRequest, v1.DraftSqlResponse]
	explainError        *connect.Client[v1.ExplainErrorRequest, v1.ExplainErrorResponse]
}

// DraftTransformation calls assist.v1.AssistService.DraftTransformation.
func (c *assistServiceClient) DraftTransformation(ctx context.Context, req *connect.Request[v1.DraftTransformationRequest]) (*connect.Response[v1.DraftTransformationResponse], error) {
	return c.draftTransformation.CallUnary(ctx, req)
}

// DraftRillDashboard calls assist.v1.AssistService.DraftRillDashboard.
func (c *assistServiceClient) DraftRillDashboard(ctx context.Context, req *connect.Request[v1.DraftRillDashboardRequest]) (*connect.Response[v1.DraftRillDashboardResponse], error) {
	return c.draftRillDashboard.CallUnary(ctx, req)
}

// DraftSql calls assist.v1.AssistService.DraftSql.
func (c *assistServiceClient) DraftSql(ctx context.Context, req *connect.Request[v1.DraftSqlRequest]) (*connect.Response[v1.DraftSqlResponse], error) {
	return c.draftSql.CallUnary(ctx, req)
}

// ExplainError calls assist.v1.AssistService.ExplainError.
func (c *assistServiceClient) ExplainError(ctx context.Context, req *connect.Request[v1.ExplainErrorRequest]) (*connect.Response[v1.ExplainErrorResponse], error) {
	return c.explainError.CallUnary(ctx, req)
}

// AssistServiceHandler is an implementation of the assist.v1.AssistService service.
type AssistServiceHandler interface {
	// DraftTransformation turns a natural-language prompt into a draft dbt
	// transformation: a pre-filled CreateTransformation request (hosted-repo
	// mode) plus starter model files the user reviews and commits themselves.
	DraftTransformation(context.Context, *connect.Request[v1.DraftTransformationRequest]) (*connect.Response[v1.DraftTransformationResponse], error)
	// DraftRillDashboard turns a natural-language prompt into draft Rill
	// project files (metrics views, explore dashboards, optional models),
	// opened as unsaved buffers in the Console's Rill editor.
	DraftRillDashboard(context.Context, *connect.Request[v1.DraftRillDashboardRequest]) (*connect.Response[v1.DraftRillDashboardResponse], error)
	// DraftSql turns a natural-language request into one read-only DuckDB
	// query. The server assembles the schema context from the caller's own
	// warehouse (all table names, column detail for the most relevant few) and
	// validates the draft with EXPLAIN best-effort — a statement the engine
	// rejects still comes back, with the engine's message in notes. The draft
	// is inserted into the editor, NEVER executed automatically.
	DraftSql(context.Context, *connect.Request[v1.DraftSqlRequest]) (*connect.Response[v1.DraftSqlResponse], error)
	// ExplainError explains one failure in plain language. For pipeline and
	// transformation runs the client sends only ids — the server assembles the
	// trusted context from the caller's own rows (config without credentials,
	// run status, the stored error text) so nothing client-supplied poses as
	// trusted data. The SQL target is the exception: the editor's SQL and
	// engine error are client-supplied because the server keeps no query
	// history.
	ExplainError(context.Context, *connect.Request[v1.ExplainErrorRequest]) (*connect.Response[v1.ExplainErrorResponse], error)
}

// NewAssistServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAssistServiceHandler(svc AssistServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	assistServiceMethods := v1.File_assist_proto.Services().ByName("AssistService").Methods()
	assistServiceDraftTransformationHandler := connect.NewUnaryHandler(
		AssistServiceDraftTransformationProcedure,
		svc.DraftTransformation,
		connect.WithSchema(assistServiceMethods.ByName("DraftTransformation")),
		connect.WithHandlerOptions(opts...),
	)
	assistServiceDraftRillDashboardHandler := connect.NewUnaryHandler(
		AssistServiceDraftRillDashboardProcedure,
		svc.DraftRillDashboard,
		connect.WithSchema(assistServiceMethods.ByName("DraftRillDashboard")),
		connect.WithHandlerOptions(opts...),
	)
	assistServiceDraftSqlHandler := connect.NewUnaryHandler(
		AssistServiceDraftSqlProcedure,
		svc.DraftSql,
		connect.WithSchema(assistServiceMethods.ByName("DraftSql")),
		connect.WithHandlerOptions(opts...),
	)
	assistServiceExplainErrorHandler := connect.NewUnaryHandler(
		AssistServiceExplainErrorProcedure,
		svc.ExplainError,
		connect.WithSchema(assistServiceMethods.ByName("ExplainError")),
		connect.WithHandlerOptions(opts...),
	)
	return "/assist.v1.AssistService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AssistServiceDraftTransformationProcedure:
			assistServiceDraftTransformationHandler.ServeHTTP(w, r)
		case AssistServiceDraftRillDashboardProcedure:
			assistServiceDraftRillDashboardHandler.ServeHTTP(w, r)
		case AssistServiceDraftSqlProcedure:
			assistServiceDraftSqlHandler.ServeHTTP(w, r)
		case AssistServiceExplainErrorProcedure:
			assistServiceExplainErrorHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAssistServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAssistServiceHandler struct{}

func (UnimplementedAssistServiceHandler) DraftTransformation(context.Context, *connect.Request[v1.DraftTransformationRequest]) (*connect.Response[v1.DraftTransformationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("assist.v1.AssistService.DraftTransformation is not implemented"))
}

func (UnimplementedAssistServiceHandler) DraftRillDashboard(context.Context, *connect.Request[v1.DraftRillDashboardRequest]) (*connect.Response[v1.DraftRillDashboardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("assist.v1.AssistService.DraftRillDashboard is not implemented"))
}

func (UnimplementedAssistServiceHandler) DraftSql(context.Context, *connect.Request[v1.DraftSqlRequest]) (*connect.Response[v1.DraftSqlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("assist.v1.AssistService.DraftSql is not implemented"))
}

func (UnimplementedAssistServiceHandler) ExplainError(context.Context, *connect.Request[v1.ExplainErrorRequest]) (*connect.Response[v1.ExplainErrorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("assist.v1.AssistService.ExplainError is not implemented"))
}
