// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: connection.proto

package connectionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Connection is the wire shape of one workspace connection. No credential
// material, ever — email is display metadata from the consent.
type Connection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type key: "google" today.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Display name; defaults to the granting account's email.
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Granting account email, for display (google connections).
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// RFC 3339 creation timestamp.
	CreatedAt string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// What the granting consent authorized (google connections). Empty means
	// "not recorded" — a connection made before scopes were tracked — never
	// "nothing granted", so a client must not refuse on an empty list.
	//
	// It is here so the connection picker can say "this account is connected for
	// Sheets only, reconnect to add Drive" at the moment of choosing, instead of
	// letting a scheduled run on the box discover it in a 403.
	Scopes        []string `protobuf:"bytes,7,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_connection_proto_rawDescGZIP(), []int{0}
}

func (x *Connection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Connection) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Connection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Connection) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Connection) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Connection) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Connection) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type ListConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectionsRequest) Reset() {
	*x = ListConnectionsRequest{}
	mi := &file_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionsRequest) ProtoMessage() {}

func (x *ListConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_connection_proto_rawDescGZIP(), []int{1}
}

type ListConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*Connection          `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectionsResponse) Reset() {
	*x = ListConnectionsResponse{}
	mi := &file_connection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionsResponse) ProtoMessage() {}

func (x *ListConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_connection_proto_rawDescGZIP(), []int{2}
}

func (x *ListConnectionsResponse) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type CreateConnectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional display name; defaults to the granting account's email.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Provider-specific source of the authorization.
	//
	// Types that are valid to be assigned to Source:
	//
	//	*CreateConnectionRequest_GoogleGrantId
	Source        isCreateConnectionRequest_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConnectionRequest) Reset() {
	*x = CreateConnectionRequest{}
	mi := &file_connection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConnectionRequest) ProtoMessage() {}

func (x *CreateConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConnectionRequest.ProtoReflect.Descriptor instead.
func (*CreateConnectionRequest) Descriptor() ([]byte, []int) {
	return file_connection_proto_rawDescGZIP(), []int{3}
}

func (x *CreateConnectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateConnectionRequest) GetSource() isCreateConnectionRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CreateConnectionRequest) GetGoogleGrantId() string {
	if x != nil {
		if x, ok := x.Source.(*CreateConnectionRequest_GoogleGrantId); ok {
			return x.GoogleGrantId
		}
	}
	return ""
}

type isCreateConnectionRequest_Source interface {
	isCreateConnectionRequest_Source()
}

type CreateConnectionRequest_GoogleGrantId struct {
	// A grant_id from the Google consent popup (one-time use).
	GoogleGrantId string `protobuf:"bytes,2,opt,name=google_grant_id,json=googleGrantId,proto3,oneof"`
}

func (*CreateConnectionRequest_GoogleGrantId) isCreateConnectionRequest_Source() {}

type CreateConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *Connection            `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConnectionResponse) Reset() {
	*x = CreateConnectionResponse{}
	mi := &file_connection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConnectionResponse) ProtoMessage() {}

func (x *CreateConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConnectionResponse.ProtoReflect.Descriptor instead.
func (*CreateConnectionResponse) Descriptor() ([]byte, []int) {
	return file_connection_proto_rawDescGZIP(), []int{4}
}

func (x *CreateConnectionResponse) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type DeleteConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnectionRequest) Reset() {
	*x = DeleteConnectionRequest{}
	mi := &file_connection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectionRequest) ProtoMessage() {}

func (x *DeleteConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteConnectionRequest) Descriptor() ([]byte, []int) {
	return file_connection_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteConnectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnectionResponse) Reset() {
	*x = DeleteConnectionResponse{}
	mi := &file_connection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectionResponse) ProtoMessage() {}

func (x *DeleteConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteConnectionResponse) Descriptor() ([]byte, []int) {
	return file_connection_proto_rawDescGZIP(), []int{6}
}

var File_connection_proto protoreflect.FileDescriptor

const file_connection_proto_rawDesc = "" +
	"\n" +
	"\x10connection.proto\x12\rconnection.v1\"\xa9\x01\n" +
	"\n" +
	"Connection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06scopes\x18\a \x03(\tR\x06scopes\"\x18\n" +
	"\x16ListConnectionsRequest\"V\n" +
	"\x17ListConnectionsResponse\x12;\n" +
	"\vconnections\x18\x01 \x03(\v2\x19.connection.v1.ConnectionR\vconnections\"a\n" +
	"\x17CreateConnectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x0fgoogle_grant_id\x18\x02 \x01(\tH\x00R\rgoogleGrantIdB\b\n" +
	"\x06source\"U\n" +
	"\x18CreateConnectionResponse\x129\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x19.connection.v1.ConnectionR\n" +
	"connection\")\n" +
	"\x17DeleteConnectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x18DeleteConnectionResponse2\xc5\x02\n" +
	"\x11ConnectionService\x12b\n" +
	"\x0fListConnections\x12%.connection.v1.ListConnectionsRequest\x1a&.connection.v1.ListConnectionsResponse\"\x00\x12e\n" +
	"\x10CreateConnection\x12&.connection.v1.CreateConnectionRequest\x1a'.connection.v1.CreateConnectionResponse\"\x00\x12e\n" +
	"\x10DeleteConnection\x12&.connection.v1.DeleteConnectionRequest\x1a'.connection.v1.DeleteConnectionResponse\"\x00BDZBgithub.com/fairtier/workspace-api/proto/connection/v1;connectionv1b\x06proto3"

var (
	file_connection_proto_rawDescOnce sync.Once
	file_connection_proto_rawDescData []byte
)

func file_connection_proto_rawDescGZIP() []byte {
	file_connection_proto_rawDescOnce.Do(func() {
		file_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connection_proto_rawDesc), len(file_connection_proto_rawDesc)))
	})
	return file_connection_proto_rawDescData
}

var file_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_connection_proto_goTypes = []any{
	(*Connection)(nil),               // 0: connection.v1.Connection
	(*ListConnectionsRequest)(nil),   // 1: connection.v1.ListConnectionsRequest
	(*ListConnectionsResponse)(nil),  // 2: connection.v1.ListConnectionsResponse
	(*CreateConnectionRequest)(nil),  // 3: connection.v1.CreateConnectionRequest
	(*CreateConnectionResponse)(nil), // 4: connection.v1.CreateConnectionResponse
	(*DeleteConnectionRequest)(nil),  // 5: connection.v1.DeleteConnectionRequest
	(*DeleteConnectionResponse)(nil), // 6: connection.v1.DeleteConnectionResponse
}
var file_connection_proto_depIdxs = []int32{
	0, // 0: connection.v1.ListConnectionsResponse.connections:type_name -> connection.v1.Connection
	0, // 1: connection.v1.CreateConnectionResponse.connection:type_name -> connection.v1.Connection
	1, // 2: connection.v1.ConnectionService.ListConnections:input_type -> connection.v1.ListConnectionsRequest
	3, // 3: connection.v1.ConnectionService.CreateConnection:input_type -> connection.v1.CreateConnectionRequest
	5, // 4: connection.v1.ConnectionService.DeleteConnection:input_type -> connection.v1.DeleteConnectionRequest
	2, // 5: connection.v1.ConnectionService.ListConnections:output_type -> connection.v1.ListConnectionsResponse
	4, // 6: connection.v1.ConnectionService.CreateConnection:output_type -> connection.v1.CreateConnectionResponse
	6, // 7: connection.v1.ConnectionService.DeleteConnection:output_type -> connection.v1.DeleteConnectionResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_connection_proto_init() }
func file_connection_proto_init() {
	if File_connection_proto != nil {
		return
	}
	file_connection_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateConnectionRequest_GoogleGrantId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connection_proto_rawDesc), len(file_connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connection_proto_goTypes,
		DependencyIndexes: file_connection_proto_depIdxs,
		MessageInfos:      file_connection_proto_msgTypes,
	}.Build()
	File_connection_proto = out.File
	file_connection_proto_goTypes = nil
	file_connection_proto_depIdxs = nil
}
