// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: lakekeeper_user.proto

package lakekeeperuserv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name for the service account.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Access role: "reader", "writer", or "admin".
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// Lakekeeper warehouse name to grant access to.
	WarehouseName string `protobuf:"bytes,3,opt,name=warehouse_name,json=warehouseName,proto3" json:"warehouse_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_lakekeeper_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lakekeeper_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_lakekeeper_user_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AddUserRequest) GetWarehouseName() string {
	if x != nil {
		return x.WarehouseName
	}
	return ""
}

type AddUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created service account.
	User *LakekeeperUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// OAuth2 client ID for the client_credentials grant flow.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// OAuth2 client secret. Shown only once at creation — store it securely.
	ClientSecret  string `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserResponse) Reset() {
	*x = AddUserResponse{}
	mi := &file_lakekeeper_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserResponse) ProtoMessage() {}

func (x *AddUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lakekeeper_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserResponse.ProtoReflect.Descriptor instead.
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return file_lakekeeper_user_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserResponse) GetUser() *LakekeeperUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AddUserResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AddUserResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type RemoveUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the service account to remove (Casdoor app name).
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRequest) Reset() {
	*x = RemoveUserRequest{}
	mi := &file_lakekeeper_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRequest) ProtoMessage() {}

func (x *RemoveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lakekeeper_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return file_lakekeeper_user_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserResponse) Reset() {
	*x = RemoveUserResponse{}
	mi := &file_lakekeeper_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserResponse) ProtoMessage() {}

func (x *RemoveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lakekeeper_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserResponse) Descriptor() ([]byte, []int) {
	return file_lakekeeper_user_proto_rawDescGZIP(), []int{3}
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_lakekeeper_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lakekeeper_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_lakekeeper_user_proto_rawDescGZIP(), []int{4}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*LakekeeperUser      `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_lakekeeper_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lakekeeper_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_lakekeeper_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersResponse) GetUsers() []*LakekeeperUser {
	if x != nil {
		return x.Users
	}
	return nil
}

// LakekeeperUser represents a data platform service account.
type LakekeeperUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service account ID (Casdoor app name).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Access role: "reader", "writer", or "admin".
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// Lakekeeper warehouse the service account has access to. Empty if the
	// warehouse could not be resolved.
	Warehouse     string `protobuf:"bytes,4,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LakekeeperUser) Reset() {
	*x = LakekeeperUser{}
	mi := &file_lakekeeper_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LakekeeperUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LakekeeperUser) ProtoMessage() {}

func (x *LakekeeperUser) ProtoReflect() protoreflect.Message {
	mi := &file_lakekeeper_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LakekeeperUser.ProtoReflect.Descriptor instead.
func (*LakekeeperUser) Descriptor() ([]byte, []int) {
	return file_lakekeeper_user_proto_rawDescGZIP(), []int{6}
}

func (x *LakekeeperUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LakekeeperUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LakekeeperUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LakekeeperUser) GetWarehouse() string {
	if x != nil {
		return x.Warehouse
	}
	return ""
}

var File_lakekeeper_user_proto protoreflect.FileDescriptor

const file_lakekeeper_user_proto_rawDesc = "" +
	"\n" +
	"\x15lakekeeper_user.proto\x12\x12lakekeeper_user.v1\"_\n" +
	"\x0eAddUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12%\n" +
	"\x0ewarehouse_name\x18\x03 \x01(\tR\rwarehouseName\"\x8b\x01\n" +
	"\x0fAddUserResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".lakekeeper_user.v1.LakekeeperUserR\x04user\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\",\n" +
	"\x11RemoveUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x14\n" +
	"\x12RemoveUserResponse\"\x12\n" +
	"\x10ListUsersRequest\"M\n" +
	"\x11ListUsersResponse\x128\n" +
	"\x05users\x18\x01 \x03(\v2\".lakekeeper_user.v1.LakekeeperUserR\x05users\"f\n" +
	"\x0eLakekeeperUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1c\n" +
	"\twarehouse\x18\x04 \x01(\tR\twarehouse2\xa8\x02\n" +
	"\x15LakekeeperUserService\x12T\n" +
	"\aAddUser\x12\".lakekeeper_user.v1.AddUserRequest\x1a#.lakekeeper_user.v1.AddUserResponse\"\x00\x12]\n" +
	"\n" +
	"RemoveUser\x12%.lakekeeper_user.v1.RemoveUserRequest\x1a&.lakekeeper_user.v1.RemoveUserResponse\"\x00\x12Z\n" +
	"\tListUsers\x12$.lakekeeper_user.v1.ListUsersRequest\x1a%.lakekeeper_user.v1.ListUsersResponse\"\x00BMZKgithub.com/fairtier/workspace-api/proto/lakekeeper_user/v1;lakekeeperuserv1b\x06proto3"

var (
	file_lakekeeper_user_proto_rawDescOnce sync.Once
	file_lakekeeper_user_proto_rawDescData []byte
)

func file_lakekeeper_user_proto_rawDescGZIP() []byte {
	file_lakekeeper_user_proto_rawDescOnce.Do(func() {
		file_lakekeeper_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lakekeeper_user_proto_rawDesc), len(file_lakekeeper_user_proto_rawDesc)))
	})
	return file_lakekeeper_user_proto_rawDescData
}

var file_lakekeeper_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lakekeeper_user_proto_goTypes = []any{
	(*AddUserRequest)(nil),     // 0: lakekeeper_user.v1.AddUserRequest
	(*AddUserResponse)(nil),    // 1: lakekeeper_user.v1.AddUserResponse
	(*RemoveUserRequest)(nil),  // 2: lakekeeper_user.v1.RemoveUserRequest
	(*RemoveUserResponse)(nil), // 3: lakekeeper_user.v1.RemoveUserResponse
	(*ListUsersRequest)(nil),   // 4: lakekeeper_user.v1.ListUsersRequest
	(*ListUsersResponse)(nil),  // 5: lakekeeper_user.v1.ListUsersResponse
	(*LakekeeperUser)(nil),     // 6: lakekeeper_user.v1.LakekeeperUser
}
var file_lakekeeper_user_proto_depIdxs = []int32{
	6, // 0: lakekeeper_user.v1.AddUserResponse.user:type_name -> lakekeeper_user.v1.LakekeeperUser
	6, // 1: lakekeeper_user.v1.ListUsersResponse.users:type_name -> lakekeeper_user.v1.LakekeeperUser
	0, // 2: lakekeeper_user.v1.LakekeeperUserService.AddUser:input_type -> lakekeeper_user.v1.AddUserRequest
	2, // 3: lakekeeper_user.v1.LakekeeperUserService.RemoveUser:input_type -> lakekeeper_user.v1.RemoveUserRequest
	4, // 4: lakekeeper_user.v1.LakekeeperUserService.ListUsers:input_type -> lakekeeper_user.v1.ListUsersRequest
	1, // 5: lakekeeper_user.v1.LakekeeperUserService.AddUser:output_type -> lakekeeper_user.v1.AddUserResponse
	3, // 6: lakekeeper_user.v1.LakekeeperUserService.RemoveUser:output_type -> lakekeeper_user.v1.RemoveUserResponse
	5, // 7: lakekeeper_user.v1.LakekeeperUserService.ListUsers:output_type -> lakekeeper_user.v1.ListUsersResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lakekeeper_user_proto_init() }
func file_lakekeeper_user_proto_init() {
	if File_lakekeeper_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lakekeeper_user_proto_rawDesc), len(file_lakekeeper_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lakekeeper_user_proto_goTypes,
		DependencyIndexes: file_lakekeeper_user_proto_depIdxs,
		MessageInfos:      file_lakekeeper_user_proto_msgTypes,
	}.Build()
	File_lakekeeper_user_proto = out.File
	file_lakekeeper_user_proto_goTypes = nil
	file_lakekeeper_user_proto_depIdxs = nil
}
