// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pipeline.proto

package pipelinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fairtier/workspace-api/proto/pipeline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PipelineServiceName is the fully-qualified name of the PipelineService service.
	PipelineServiceName = "pipeline.v1.PipelineService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PipelineServiceCreatePipelineProcedure is the fully-qualified name of the PipelineService's
	// CreatePipeline RPC.
	PipelineServiceCreatePipelineProcedure = "/pipeline.v1.PipelineService/CreatePipeline"
	// PipelineServiceListPipelinesProcedure is the fully-qualified name of the PipelineService's
	// ListPipelines RPC.
	PipelineServiceListPipelinesProcedure = "/pipeline.v1.PipelineService/ListPipelines"
	// PipelineServiceGetPipelineProcedure is the fully-qualified name of the PipelineService's
	// GetPipeline RPC.
	PipelineServiceGetPipelineProcedure = "/pipeline.v1.PipelineService/GetPipeline"
	// PipelineServiceUpdatePipelineProcedure is the fully-qualified name of the PipelineService's
	// UpdatePipeline RPC.
	PipelineServiceUpdatePipelineProcedure = "/pipeline.v1.PipelineService/UpdatePipeline"
	// PipelineServiceDeletePipelineProcedure is the fully-qualified name of the PipelineService's
	// DeletePipeline RPC.
	PipelineServiceDeletePipelineProcedure = "/pipeline.v1.PipelineService/DeletePipeline"
	// PipelineServiceTriggerPipelineProcedure is the fully-qualified name of the PipelineService's
	// TriggerPipeline RPC.
	PipelineServiceTriggerPipelineProcedure = "/pipeline.v1.PipelineService/TriggerPipeline"
	// PipelineServiceListPipelineVersionsProcedure is the fully-qualified name of the PipelineService's
	// ListPipelineVersions RPC.
	PipelineServiceListPipelineVersionsProcedure = "/pipeline.v1.PipelineService/ListPipelineVersions"
	// PipelineServiceRestorePipelineVersionProcedure is the fully-qualified name of the
	// PipelineService's RestorePipelineVersion RPC.
	PipelineServiceRestorePipelineVersionProcedure = "/pipeline.v1.PipelineService/RestorePipelineVersion"
	// PipelineServiceListUploadedFilesProcedure is the fully-qualified name of the PipelineService's
	// ListUploadedFiles RPC.
	PipelineServiceListUploadedFilesProcedure = "/pipeline.v1.PipelineService/ListUploadedFiles"
	// PipelineServiceDeleteUploadedFileProcedure is the fully-qualified name of the PipelineService's
	// DeleteUploadedFile RPC.
	PipelineServiceDeleteUploadedFileProcedure = "/pipeline.v1.PipelineService/DeleteUploadedFile"
	// PipelineServiceGetPipelineConfigsProcedure is the fully-qualified name of the PipelineService's
	// GetPipelineConfigs RPC.
	PipelineServiceGetPipelineConfigsProcedure = "/pipeline.v1.PipelineService/GetPipelineConfigs"
	// PipelineServiceReportPipelineRunProcedure is the fully-qualified name of the PipelineService's
	// ReportPipelineRun RPC.
	PipelineServiceReportPipelineRunProcedure = "/pipeline.v1.PipelineService/ReportPipelineRun"
)

// PipelineServiceClient is a client for the pipeline.v1.PipelineService service.
type PipelineServiceClient interface {
	// CreatePipeline defines a new data pipeline with source configuration,
	// credentials, and schedule.
	CreatePipeline(context.Context, *connect.Request[v1.CreatePipelineRequest]) (*connect.Response[v1.CreatePipelineResponse], error)
	// ListPipelines returns all pipelines for the authenticated user's tenant.
	ListPipelines(context.Context, *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error)
	// GetPipeline returns a single pipeline with its recent execution history.
	GetPipeline(context.Context, *connect.Request[v1.GetPipelineRequest]) (*connect.Response[v1.GetPipelineResponse], error)
	// UpdatePipeline modifies an existing pipeline's configuration.
	UpdatePipeline(context.Context, *connect.Request[v1.UpdatePipelineRequest]) (*connect.Response[v1.UpdatePipelineResponse], error)
	// DeletePipeline permanently removes a pipeline and its run history.
	DeletePipeline(context.Context, *connect.Request[v1.DeletePipelineRequest]) (*connect.Response[v1.DeletePipelineResponse], error)
	// TriggerPipeline manually starts a pipeline execution outside its schedule.
	TriggerPipeline(context.Context, *connect.Request[v1.TriggerPipelineRequest]) (*connect.Response[v1.TriggerPipelineResponse], error)
	// ListPipelineVersions returns the newest-first history of the pipeline's
	// rendered definition file in the workspace's git repo (VM boxes only;
	// FAILED_PRECONDITION elsewhere). History follows the current file path —
	// versions from before a rename stay with the old path.
	ListPipelineVersions(context.Context, *connect.Request[v1.ListPipelineVersionsRequest]) (*connect.Response[v1.ListPipelineVersionsResponse], error)
	// RestorePipelineVersion applies the definition recorded at a version's
	// commit sha through the normal update path (validated save; the repo gets
	// a new forward commit). Source credentials are never part of a version
	// and stay untouched.
	RestorePipelineVersion(context.Context, *connect.Request[v1.RestorePipelineVersionRequest]) (*connect.Response[v1.RestorePipelineVersionResponse], error)
	// ListUploadedFiles returns the files dropped into a file_upload pipeline.
	ListUploadedFiles(context.Context, *connect.Request[v1.ListUploadedFilesRequest]) (*connect.Response[v1.ListUploadedFilesResponse], error)
	// DeleteUploadedFile removes one dropped file from the customer's storage
	// and from the pipeline's configuration.
	DeleteUploadedFile(context.Context, *connect.Request[v1.DeleteUploadedFileRequest]) (*connect.Response[v1.DeleteUploadedFileResponse], error)
	// GetPipelineConfigs returns all enabled pipelines for a customer, including
	// sensitive source credentials. Called by the dlt-worker poll loop.
	GetPipelineConfigs(context.Context, *connect.Request[v1.GetPipelineConfigsRequest]) (*connect.Response[v1.GetPipelineConfigsResponse], error)
	// ReportPipelineRun records the result of a pipeline execution from the
	// dlt-worker.
	ReportPipelineRun(context.Context, *connect.Request[v1.ReportPipelineRunRequest]) (*connect.Response[v1.ReportPipelineRunResponse], error)
}

// NewPipelineServiceClient constructs a client for the pipeline.v1.PipelineService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPipelineServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PipelineServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pipelineServiceMethods := v1.File_pipeline_proto.Services().ByName("PipelineService").Methods()
	return &pipelineServiceClient{
		createPipeline: connect.NewClient[v1.CreatePipelineRequest, v1.CreatePipelineResponse](
			httpClient,
			baseURL+PipelineServiceCreatePipelineProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("CreatePipeline")),
			connect.WithClientOptions(opts...),
		),
		listPipelines: connect.NewClient[v1.ListPipelinesRequest, v1.ListPipelinesResponse](
			httpClient,
			baseURL+PipelineServiceListPipelinesProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("ListPipelines")),
			connect.WithClientOptions(opts...),
		),
		getPipeline: connect.NewClient[v1.GetPipelineRequest, v1.GetPipelineResponse](
			httpClient,
			baseURL+PipelineServiceGetPipelineProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("GetPipeline")),
			connect.WithClientOptions(opts...),
		),
		updatePipeline: connect.NewClient[v1.UpdatePipelineRequest, v1.UpdatePipelineResponse](
			httpClient,
			baseURL+PipelineServiceUpdatePipelineProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("UpdatePipeline")),
			connect.WithClientOptions(opts...),
		),
		deletePipeline: connect.NewClient[v1.DeletePipelineRequest, v1.DeletePipelineResponse](
			httpClient,
			baseURL+PipelineServiceDeletePipelineProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("DeletePipeline")),
			connect.WithClientOptions(opts...),
		),
		triggerPipeline: connect.NewClient[v1.TriggerPipelineRequest, v1.TriggerPipelineResponse](
			httpClient,
			baseURL+PipelineServiceTriggerPipelineProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("TriggerPipeline")),
			connect.WithClientOptions(opts...),
		),
		listPipelineVersions: connect.NewClient[v1.ListPipelineVersionsRequest, v1.ListPipelineVersionsResponse](
			httpClient,
			baseURL+PipelineServiceListPipelineVersionsProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("ListPipelineVersions")),
			connect.WithClientOptions(opts...),
		),
		restorePipelineVersion: connect.NewClient[v1.RestorePipelineVersionRequest, v1.RestorePipelineVersionResponse](
			httpClient,
			baseURL+PipelineServiceRestorePipelineVersionProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("RestorePipelineVersion")),
			connect.WithClientOptions(opts...),
		),
		listUploadedFiles: connect.NewClient[v1.ListUploadedFilesRequest, v1.ListUploadedFilesResponse](
			httpClient,
			baseURL+PipelineServiceListUploadedFilesProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("ListUploadedFiles")),
			connect.WithClientOptions(opts...),
		),
		deleteUploadedFile: connect.NewClient[v1.DeleteUploadedFileRequest, v1.DeleteUploadedFileResponse](
			httpClient,
			baseURL+PipelineServiceDeleteUploadedFileProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("DeleteUploadedFile")),
			connect.WithClientOptions(opts...),
		),
		getPipelineConfigs: connect.NewClient[v1.GetPipelineConfigsRequest, v1.GetPipelineConfigsResponse](
			httpClient,
			baseURL+PipelineServiceGetPipelineConfigsProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("GetPipelineConfigs")),
			connect.WithClientOptions(opts...),
		),
		reportPipelineRun: connect.NewClient[v1.ReportPipelineRunRequest, v1.ReportPipelineRunResponse](
			httpClient,
			baseURL+PipelineServiceReportPipelineRunProcedure,
			connect.WithSchema(pipelineServiceMethods.ByName("ReportPipelineRun")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pipelineServiceClient implements PipelineServiceClient.
type pipelineServiceClient struct {
	createPipeline         *connect.Client[v1.CreatePipelineRequest, v1.CreatePipelineResponse]
	listPipelines          *connect.Client[v1.ListPipelinesRequest, v1.ListPipelinesResponse]
	getPipeline            *connect.Client[v1.GetPipelineRequest, v1.GetPipelineResponse]
	updatePipeline         *connect.Client[v1.UpdatePipelineRequest, v1.UpdatePipelineResponse]
	deletePipeline         *connect.Client[v1.DeletePipelineRequest, v1.DeletePipelineResponse]
	triggerPipeline        *connect.Client[v1.TriggerPipelineRequest, v1.TriggerPipelineResponse]
	listPipelineVersions   *connect.Client[v1.ListPipelineVersionsRequest, v1.ListPipelineVersionsResponse]
	restorePipelineVersion *connect.Client[v1.RestorePipelineVersionRequest, v1.RestorePipelineVersionResponse]
	listUploadedFiles      *connect.Client[v1.ListUploadedFilesRequest, v1.ListUploadedFilesResponse]
	deleteUploadedFile     *connect.Client[v1.DeleteUploadedFileRequest, v1.DeleteUploadedFileResponse]
	getPipelineConfigs     *connect.Client[v1.GetPipelineConfigsRequest, v1.GetPipelineConfigsResponse]
	reportPipelineRun      *connect.Client[v1.ReportPipelineRunRequest, v1.ReportPipelineRunResponse]
}

// CreatePipeline calls pipeline.v1.PipelineService.CreatePipeline.
func (c *pipelineServiceClient) CreatePipeline(ctx context.Context, req *connect.Request[v1.CreatePipelineRequest]) (*connect.Response[v1.CreatePipelineResponse], error) {
	return c.createPipeline.CallUnary(ctx, req)
}

// ListPipelines calls pipeline.v1.PipelineService.ListPipelines.
func (c *pipelineServiceClient) ListPipelines(ctx context.Context, req *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error) {
	return c.listPipelines.CallUnary(ctx, req)
}

// GetPipeline calls pipeline.v1.PipelineService.GetPipeline.
func (c *pipelineServiceClient) GetPipeline(ctx context.Context, req *connect.Request[v1.GetPipelineRequest]) (*connect.Response[v1.GetPipelineResponse], error) {
	return c.getPipeline.CallUnary(ctx, req)
}

// UpdatePipeline calls pipeline.v1.PipelineService.UpdatePipeline.
func (c *pipelineServiceClient) UpdatePipeline(ctx context.Context, req *connect.Request[v1.UpdatePipelineRequest]) (*connect.Response[v1.UpdatePipelineResponse], error) {
	return c.updatePipeline.CallUnary(ctx, req)
}

// DeletePipeline calls pipeline.v1.PipelineService.DeletePipeline.
func (c *pipelineServiceClient) DeletePipeline(ctx context.Context, req *connect.Request[v1.DeletePipelineRequest]) (*connect.Response[v1.DeletePipelineResponse], error) {
	return c.deletePipeline.CallUnary(ctx, req)
}

// TriggerPipeline calls pipeline.v1.PipelineService.TriggerPipeline.
func (c *pipelineServiceClient) TriggerPipeline(ctx context.Context, req *connect.Request[v1.TriggerPipelineRequest]) (*connect.Response[v1.TriggerPipelineResponse], error) {
	return c.triggerPipeline.CallUnary(ctx, req)
}

// ListPipelineVersions calls pipeline.v1.PipelineService.ListPipelineVersions.
func (c *pipelineServiceClient) ListPipelineVersions(ctx context.Context, req *connect.Request[v1.ListPipelineVersionsRequest]) (*connect.Response[v1.ListPipelineVersionsResponse], error) {
	return c.listPipelineVersions.CallUnary(ctx, req)
}

// RestorePipelineVersion calls pipeline.v1.PipelineService.RestorePipelineVersion.
func (c *pipelineServiceClient) RestorePipelineVersion(ctx context.Context, req *connect.Request[v1.RestorePipelineVersionRequest]) (*connect.Response[v1.RestorePipelineVersionResponse], error) {
	return c.restorePipelineVersion.CallUnary(ctx, req)
}

// ListUploadedFiles calls pipeline.v1.PipelineService.ListUploadedFiles.
func (c *pipelineServiceClient) ListUploadedFiles(ctx context.Context, req *connect.Request[v1.ListUploadedFilesRequest]) (*connect.Response[v1.ListUploadedFilesResponse], error) {
	return c.listUploadedFiles.CallUnary(ctx, req)
}

// DeleteUploadedFile calls pipeline.v1.PipelineService.DeleteUploadedFile.
func (c *pipelineServiceClient) DeleteUploadedFile(ctx context.Context, req *connect.Request[v1.DeleteUploadedFileRequest]) (*connect.Response[v1.DeleteUploadedFileResponse], error) {
	return c.deleteUploadedFile.CallUnary(ctx, req)
}

// GetPipelineConfigs calls pipeline.v1.PipelineService.GetPipelineConfigs.
func (c *pipelineServiceClient) GetPipelineConfigs(ctx context.Context, req *connect.Request[v1.GetPipelineConfigsRequest]) (*connect.Response[v1.GetPipelineConfigsResponse], error) {
	return c.getPipelineConfigs.CallUnary(ctx, req)
}

// ReportPipelineRun calls pipeline.v1.PipelineService.ReportPipelineRun.
func (c *pipelineServiceClient) ReportPipelineRun(ctx context.Context, req *connect.Request[v1.ReportPipelineRunRequest]) (*connect.Response[v1.ReportPipelineRunResponse], error) {
	return c.reportPipelineRun.CallUnary(ctx, req)
}

// PipelineServiceHandler is an implementation of the pipeline.v1.PipelineService service.
type PipelineServiceHandler interface {
	// CreatePipeline defines a new data pipeline with source configuration,
	// credentials, and schedule.
	CreatePipeline(context.Context, *connect.Request[v1.CreatePipelineRequest]) (*connect.Response[v1.CreatePipelineResponse], error)
	// ListPipelines returns all pipelines for the authenticated user's tenant.
	ListPipelines(context.Context, *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error)
	// GetPipeline returns a single pipeline with its recent execution history.
	GetPipeline(context.Context, *connect.Request[v1.GetPipelineRequest]) (*connect.Response[v1.GetPipelineResponse], error)
	// UpdatePipeline modifies an existing pipeline's configuration.
	UpdatePipeline(context.Context, *connect.Request[v1.UpdatePipelineRequest]) (*connect.Response[v1.UpdatePipelineResponse], error)
	// DeletePipeline permanently removes a pipeline and its run history.
	DeletePipeline(context.Context, *connect.Request[v1.DeletePipelineRequest]) (*connect.Response[v1.DeletePipelineResponse], error)
	// TriggerPipeline manually starts a pipeline execution outside its schedule.
	TriggerPipeline(context.Context, *connect.Request[v1.TriggerPipelineRequest]) (*connect.Response[v1.TriggerPipelineResponse], error)
	// ListPipelineVersions returns the newest-first history of the pipeline's
	// rendered definition file in the workspace's git repo (VM boxes only;
	// FAILED_PRECONDITION elsewhere). History follows the current file path —
	// versions from before a rename stay with the old path.
	ListPipelineVersions(context.Context, *connect.Request[v1.ListPipelineVersionsRequest]) (*connect.Response[v1.ListPipelineVersionsResponse], error)
	// RestorePipelineVersion applies the definition recorded at a version's
	// commit sha through the normal update path (validated save; the repo gets
	// a new forward commit). Source credentials are never part of a version
	// and stay untouched.
	RestorePipelineVersion(context.Context, *connect.Request[v1.RestorePipelineVersionRequest]) (*connect.Response[v1.RestorePipelineVersionResponse], error)
	// ListUploadedFiles returns the files dropped into a file_upload pipeline.
	ListUploadedFiles(context.Context, *connect.Request[v1.ListUploadedFilesRequest]) (*connect.Response[v1.ListUploadedFilesResponse], error)
	// DeleteUploadedFile removes one dropped file from the customer's storage
	// and from the pipeline's configuration.
	DeleteUploadedFile(context.Context, *connect.Request[v1.DeleteUploadedFileRequest]) (*connect.Response[v1.DeleteUploadedFileResponse], error)
	// GetPipelineConfigs returns all enabled pipelines for a customer, including
	// sensitive source credentials. Called by the dlt-worker poll loop.
	GetPipelineConfigs(context.Context, *connect.Request[v1.GetPipelineConfigsRequest]) (*connect.Response[v1.GetPipelineConfigsResponse], error)
	// ReportPipelineRun records the result of a pipeline execution from the
	// dlt-worker.
	ReportPipelineRun(context.Context, *connect.Request[v1.ReportPipelineRunRequest]) (*connect.Response[v1.ReportPipelineRunResponse], error)
}

// NewPipelineServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPipelineServiceHandler(svc PipelineServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pipelineServiceMethods := v1.File_pipeline_proto.Services().ByName("PipelineService").Methods()
	pipelineServiceCreatePipelineHandler := connect.NewUnaryHandler(
		PipelineServiceCreatePipelineProcedure,
		svc.CreatePipeline,
		connect.WithSchema(pipelineServiceMethods.ByName("CreatePipeline")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceListPipelinesHandler := connect.NewUnaryHandler(
		PipelineServiceListPipelinesProcedure,
		svc.ListPipelines,
		connect.WithSchema(pipelineServiceMethods.ByName("ListPipelines")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceGetPipelineHandler := connect.NewUnaryHandler(
		PipelineServiceGetPipelineProcedure,
		svc.GetPipeline,
		connect.WithSchema(pipelineServiceMethods.ByName("GetPipeline")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceUpdatePipelineHandler := connect.NewUnaryHandler(
		PipelineServiceUpdatePipelineProcedure,
		svc.UpdatePipeline,
		connect.WithSchema(pipelineServiceMethods.ByName("UpdatePipeline")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceDeletePipelineHandler := connect.NewUnaryHandler(
		PipelineServiceDeletePipelineProcedure,
		svc.DeletePipeline,
		connect.WithSchema(pipelineServiceMethods.ByName("DeletePipeline")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceTriggerPipelineHandler := connect.NewUnaryHandler(
		PipelineServiceTriggerPipelineProcedure,
		svc.TriggerPipeline,
		connect.WithSchema(pipelineServiceMethods.ByName("TriggerPipeline")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceListPipelineVersionsHandler := connect.NewUnaryHandler(
		PipelineServiceListPipelineVersionsProcedure,
		svc.ListPipelineVersions,
		connect.WithSchema(pipelineServiceMethods.ByName("ListPipelineVersions")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceRestorePipelineVersionHandler := connect.NewUnaryHandler(
		PipelineServiceRestorePipelineVersionProcedure,
		svc.RestorePipelineVersion,
		connect.WithSchema(pipelineServiceMethods.ByName("RestorePipelineVersion")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceListUploadedFilesHandler := connect.NewUnaryHandler(
		PipelineServiceListUploadedFilesProcedure,
		svc.ListUploadedFiles,
		connect.WithSchema(pipelineServiceMethods.ByName("ListUploadedFiles")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceDeleteUploadedFileHandler := connect.NewUnaryHandler(
		PipelineServiceDeleteUploadedFileProcedure,
		svc.DeleteUploadedFile,
		connect.WithSchema(pipelineServiceMethods.ByName("DeleteUploadedFile")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceGetPipelineConfigsHandler := connect.NewUnaryHandler(
		PipelineServiceGetPipelineConfigsProcedure,
		svc.GetPipelineConfigs,
		connect.WithSchema(pipelineServiceMethods.ByName("GetPipelineConfigs")),
		connect.WithHandlerOptions(opts...),
	)
	pipelineServiceReportPipelineRunHandler := connect.NewUnaryHandler(
		PipelineServiceReportPipelineRunProcedure,
		svc.ReportPipelineRun,
		connect.WithSchema(pipelineServiceMethods.ByName("ReportPipelineRun")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pipeline.v1.PipelineService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PipelineServiceCreatePipelineProcedure:
			pipelineServiceCreatePipelineHandler.ServeHTTP(w, r)
		case PipelineServiceListPipelinesProcedure:
			pipelineServiceListPipelinesHandler.ServeHTTP(w, r)
		case PipelineServiceGetPipelineProcedure:
			pipelineServiceGetPipelineHandler.ServeHTTP(w, r)
		case PipelineServiceUpdatePipelineProcedure:
			pipelineServiceUpdatePipelineHandler.ServeHTTP(w, r)
		case PipelineServiceDeletePipelineProcedure:
			pipelineServiceDeletePipelineHandler.ServeHTTP(w, r)
		case PipelineServiceTriggerPipelineProcedure:
			pipelineServiceTriggerPipelineHandler.ServeHTTP(w, r)
		case PipelineServiceListPipelineVersionsProcedure:
			pipelineServiceListPipelineVersionsHandler.ServeHTTP(w, r)
		case PipelineServiceRestorePipelineVersionProcedure:
			pipelineServiceRestorePipelineVersionHandler.ServeHTTP(w, r)
		case PipelineServiceListUploadedFilesProcedure:
			pipelineServiceListUploadedFilesHandler.ServeHTTP(w, r)
		case PipelineServiceDeleteUploadedFileProcedure:
			pipelineServiceDeleteUploadedFileHandler.ServeHTTP(w, r)
		case PipelineServiceGetPipelineConfigsProcedure:
			pipelineServiceGetPipelineConfigsHandler.ServeHTTP(w, r)
		case PipelineServiceReportPipelineRunProcedure:
			pipelineServiceReportPipelineRunHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPipelineServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPipelineServiceHandler struct{}

func (UnimplementedPipelineServiceHandler) CreatePipeline(context.Context, *connect.Request[v1.CreatePipelineRequest]) (*connect.Response[v1.CreatePipelineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.CreatePipeline is not implemented"))
}

func (UnimplementedPipelineServiceHandler) ListPipelines(context.Context, *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.ListPipelines is not implemented"))
}

func (UnimplementedPipelineServiceHandler) GetPipeline(context.Context, *connect.Request[v1.GetPipelineRequest]) (*connect.Response[v1.GetPipelineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.GetPipeline is not implemented"))
}

func (UnimplementedPipelineServiceHandler) UpdatePipeline(context.Context, *connect.Request[v1.UpdatePipelineRequest]) (*connect.Response[v1.UpdatePipelineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.UpdatePipeline is not implemented"))
}

func (UnimplementedPipelineServiceHandler) DeletePipeline(context.Context, *connect.Request[v1.DeletePipelineRequest]) (*connect.Response[v1.DeletePipelineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.DeletePipeline is not implemented"))
}

func (UnimplementedPipelineServiceHandler) TriggerPipeline(context.Context, *connect.Request[v1.TriggerPipelineRequest]) (*connect.Response[v1.TriggerPipelineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.TriggerPipeline is not implemented"))
}

func (UnimplementedPipelineServiceHandler) ListPipelineVersions(context.Context, *connect.Request[v1.ListPipelineVersionsRequest]) (*connect.Response[v1.ListPipelineVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.ListPipelineVersions is not implemented"))
}

func (UnimplementedPipelineServiceHandler) RestorePipelineVersion(context.Context, *connect.Request[v1.RestorePipelineVersionRequest]) (*connect.Response[v1.RestorePipelineVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.RestorePipelineVersion is not implemented"))
}

func (UnimplementedPipelineServiceHandler) ListUploadedFiles(context.Context, *connect.Request[v1.ListUploadedFilesRequest]) (*connect.Response[v1.ListUploadedFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.ListUploadedFiles is not implemented"))
}

func (UnimplementedPipelineServiceHandler) DeleteUploadedFile(context.Context, *connect.Request[v1.DeleteUploadedFileRequest]) (*connect.Response[v1.DeleteUploadedFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.DeleteUploadedFile is not implemented"))
}

func (UnimplementedPipelineServiceHandler) GetPipelineConfigs(context.Context, *connect.Request[v1.GetPipelineConfigsRequest]) (*connect.Response[v1.GetPipelineConfigsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.GetPipelineConfigs is not implemented"))
}

func (UnimplementedPipelineServiceHandler) ReportPipelineRun(context.Context, *connect.Request[v1.ReportPipelineRunRequest]) (*connect.Response[v1.ReportPipelineRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pipeline.v1.PipelineService.ReportPipelineRun is not implemented"))
}
