// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: boxcredential.proto

package boxcredentialv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositGitTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gitea username the token belongs to (the box's fixed admin user).
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Gitea access token, scoped to write:repository. One token covers all
	// admin-owned repos on the box.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Optional free-form note (e.g. the minting job / token name) for audit.
	Note          string `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositGitTokenRequest) Reset() {
	*x = DepositGitTokenRequest{}
	mi := &file_boxcredential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositGitTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositGitTokenRequest) ProtoMessage() {}

func (x *DepositGitTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxcredential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositGitTokenRequest.ProtoReflect.Descriptor instead.
func (*DepositGitTokenRequest) Descriptor() ([]byte, []int) {
	return file_boxcredential_proto_rawDescGZIP(), []int{0}
}

func (x *DepositGitTokenRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DepositGitTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DepositGitTokenRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DepositGitTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositGitTokenResponse) Reset() {
	*x = DepositGitTokenResponse{}
	mi := &file_boxcredential_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositGitTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositGitTokenResponse) ProtoMessage() {}

func (x *DepositGitTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxcredential_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositGitTokenResponse.ProtoReflect.Descriptor instead.
func (*DepositGitTokenResponse) Descriptor() ([]byte, []int) {
	return file_boxcredential_proto_rawDescGZIP(), []int{1}
}

type DepositSnapshotTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bearer token the box's rill snapshot sidecar requires (AUTH_TOKEN).
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Optional free-form note (e.g. the minting job / secret name) for audit.
	Note          string `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositSnapshotTokenRequest) Reset() {
	*x = DepositSnapshotTokenRequest{}
	mi := &file_boxcredential_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositSnapshotTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositSnapshotTokenRequest) ProtoMessage() {}

func (x *DepositSnapshotTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxcredential_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositSnapshotTokenRequest.ProtoReflect.Descriptor instead.
func (*DepositSnapshotTokenRequest) Descriptor() ([]byte, []int) {
	return file_boxcredential_proto_rawDescGZIP(), []int{2}
}

func (x *DepositSnapshotTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DepositSnapshotTokenRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DepositSnapshotTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositSnapshotTokenResponse) Reset() {
	*x = DepositSnapshotTokenResponse{}
	mi := &file_boxcredential_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositSnapshotTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositSnapshotTokenResponse) ProtoMessage() {}

func (x *DepositSnapshotTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxcredential_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositSnapshotTokenResponse.ProtoReflect.Descriptor instead.
func (*DepositSnapshotTokenResponse) Descriptor() ([]byte, []int) {
	return file_boxcredential_proto_rawDescGZIP(), []int{3}
}

type DepositAgePublicKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The age X25519 recipient string ("age1..."), validated server-side.
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Optional free-form note (e.g. the minting job / secret name) for audit.
	Note          string `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositAgePublicKeyRequest) Reset() {
	*x = DepositAgePublicKeyRequest{}
	mi := &file_boxcredential_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositAgePublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAgePublicKeyRequest) ProtoMessage() {}

func (x *DepositAgePublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxcredential_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAgePublicKeyRequest.ProtoReflect.Descriptor instead.
func (*DepositAgePublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_boxcredential_proto_rawDescGZIP(), []int{4}
}

func (x *DepositAgePublicKeyRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DepositAgePublicKeyRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DepositAgePublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositAgePublicKeyResponse) Reset() {
	*x = DepositAgePublicKeyResponse{}
	mi := &file_boxcredential_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositAgePublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAgePublicKeyResponse) ProtoMessage() {}

func (x *DepositAgePublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxcredential_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAgePublicKeyResponse.ProtoReflect.Descriptor instead.
func (*DepositAgePublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_boxcredential_proto_rawDescGZIP(), []int{5}
}

var File_boxcredential_proto protoreflect.FileDescriptor

const file_boxcredential_proto_rawDesc = "" +
	"\n" +
	"\x13boxcredential.proto\x12\x10boxcredential.v1\"^\n" +
	"\x16DepositGitTokenRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"\x19\n" +
	"\x17DepositGitTokenResponse\"G\n" +
	"\x1bDepositSnapshotTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"\x1e\n" +
	"\x1cDepositSnapshotTokenResponse\"O\n" +
	"\x1aDepositAgePublicKeyRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"\x1d\n" +
	"\x1bDepositAgePublicKeyResponse2\xef\x02\n" +
	"\x14BoxCredentialService\x12h\n" +
	"\x0fDepositGitToken\x12(.boxcredential.v1.DepositGitTokenRequest\x1a).boxcredential.v1.DepositGitTokenResponse\"\x00\x12w\n" +
	"\x14DepositSnapshotToken\x12-.boxcredential.v1.DepositSnapshotTokenRequest\x1a..boxcredential.v1.DepositSnapshotTokenResponse\"\x00\x12t\n" +
	"\x13DepositAgePublicKey\x12,.boxcredential.v1.DepositAgePublicKeyRequest\x1a-.boxcredential.v1.DepositAgePublicKeyResponse\"\x00BJZHgithub.com/fairtier/workspace-api/proto/boxcredential/v1;boxcredentialv1b\x06proto3"

var (
	file_boxcredential_proto_rawDescOnce sync.Once
	file_boxcredential_proto_rawDescData []byte
)

func file_boxcredential_proto_rawDescGZIP() []byte {
	file_boxcredential_proto_rawDescOnce.Do(func() {
		file_boxcredential_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boxcredential_proto_rawDesc), len(file_boxcredential_proto_rawDesc)))
	})
	return file_boxcredential_proto_rawDescData
}

var file_boxcredential_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_boxcredential_proto_goTypes = []any{
	(*DepositGitTokenRequest)(nil),       // 0: boxcredential.v1.DepositGitTokenRequest
	(*DepositGitTokenResponse)(nil),      // 1: boxcredential.v1.DepositGitTokenResponse
	(*DepositSnapshotTokenRequest)(nil),  // 2: boxcredential.v1.DepositSnapshotTokenRequest
	(*DepositSnapshotTokenResponse)(nil), // 3: boxcredential.v1.DepositSnapshotTokenResponse
	(*DepositAgePublicKeyRequest)(nil),   // 4: boxcredential.v1.DepositAgePublicKeyRequest
	(*DepositAgePublicKeyResponse)(nil),  // 5: boxcredential.v1.DepositAgePublicKeyResponse
}
var file_boxcredential_proto_depIdxs = []int32{
	0, // 0: boxcredential.v1.BoxCredentialService.DepositGitToken:input_type -> boxcredential.v1.DepositGitTokenRequest
	2, // 1: boxcredential.v1.BoxCredentialService.DepositSnapshotToken:input_type -> boxcredential.v1.DepositSnapshotTokenRequest
	4, // 2: boxcredential.v1.BoxCredentialService.DepositAgePublicKey:input_type -> boxcredential.v1.DepositAgePublicKeyRequest
	1, // 3: boxcredential.v1.BoxCredentialService.DepositGitToken:output_type -> boxcredential.v1.DepositGitTokenResponse
	3, // 4: boxcredential.v1.BoxCredentialService.DepositSnapshotToken:output_type -> boxcredential.v1.DepositSnapshotTokenResponse
	5, // 5: boxcredential.v1.BoxCredentialService.DepositAgePublicKey:output_type -> boxcredential.v1.DepositAgePublicKeyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_boxcredential_proto_init() }
func file_boxcredential_proto_init() {
	if File_boxcredential_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boxcredential_proto_rawDesc), len(file_boxcredential_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boxcredential_proto_goTypes,
		DependencyIndexes: file_boxcredential_proto_depIdxs,
		MessageInfos:      file_boxcredential_proto_msgTypes,
	}.Build()
	File_boxcredential_proto = out.File
	file_boxcredential_proto_goTypes = nil
	file_boxcredential_proto_depIdxs = nil
}
