// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boxcredential.proto

package boxcredentialv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositFederationClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OAuth client id the box generated for itself. Not secret.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The matching client secret, generated on the box. Central stores it
	// encrypted and registers it as this tenant's client; it never mints one.
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	// Optional free-form note (e.g. the minting job / secret name) for audit.
	Note          string `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositFederationClientRequest) Reset() {
	*x = DepositFederationClientRequest{}
	mi := &file_boxcredential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositFederationClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositFederationClientRequest) ProtoMessage() {}

func (x *DepositFederationClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxcredential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositFederationClientRequest.ProtoReflect.Descriptor instead.
func (*DepositFederationClientRequest) Descriptor() ([]byte, []int) {
	return file_boxcredential_proto_rawDescGZIP(), []int{0}
}

func (x *DepositFederationClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DepositFederationClientRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *DepositFederationClientRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DepositFederationClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositFederationClientResponse) Reset() {
	*x = DepositFederationClientResponse{}
	mi := &file_boxcredential_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositFederationClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositFederationClientResponse) ProtoMessage() {}

func (x *DepositFederationClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxcredential_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositFederationClientResponse.ProtoReflect.Descriptor instead.
func (*DepositFederationClientResponse) Descriptor() ([]byte, []int) {
	return file_boxcredential_proto_rawDescGZIP(), []int{1}
}

type FetchBoxSecretsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Keys to read. Empty means "everything central holds for this tenant",
	// which is what the sync Job asks for — the box learns of a new secret by
	// receiving it, so it must not have to be taught the key list first.
	Keys          []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBoxSecretsRequest) Reset() {
	*x = FetchBoxSecretsRequest{}
	mi := &file_boxcredential_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBoxSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBoxSecretsRequest) ProtoMessage() {}

func (x *FetchBoxSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boxcredential_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBoxSecretsRequest.ProtoReflect.Descriptor instead.
func (*FetchBoxSecretsRequest) Descriptor() ([]byte, []int) {
	return file_boxcredential_proto_rawDescGZIP(), []int{2}
}

func (x *FetchBoxSecretsRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type FetchBoxSecretsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key → value, for the keys central actually holds. A requested key that is
	// absent is OMITTED rather than an error: the box syncs on a loop and
	// central may not have minted a value yet. Distinguishing "not yet" from
	// "never" is not the box's job, and failing the whole fetch over one
	// missing key would take down the delivery of every other secret.
	Secrets       map[string]string `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchBoxSecretsResponse) Reset() {
	*x = FetchBoxSecretsResponse{}
	mi := &file_boxcredential_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchBoxSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBoxSecretsResponse) ProtoMessage() {}

func (x *FetchBoxSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boxcredential_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBoxSecretsResponse.ProtoReflect.Descriptor instead.
func (*FetchBoxSecretsResponse) Descriptor() ([]byte, []int) {
	return file_boxcredential_proto_rawDescGZIP(), []int{3}
}

func (x *FetchBoxSecretsResponse) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

var File_boxcredential_proto protoreflect.FileDescriptor

const file_boxcredential_proto_rawDesc = "" +
	"\n" +
	"\x13boxcredential.proto\x12\x10boxcredential.v1\"v\n" +
	"\x1eDepositFederationClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"!\n" +
	"\x1fDepositFederationClientResponse\",\n" +
	"\x16FetchBoxSecretsRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\xa7\x01\n" +
	"\x17FetchBoxSecretsResponse\x12P\n" +
	"\asecrets\x18\x01 \x03(\v26.boxcredential.v1.FetchBoxSecretsResponse.SecretsEntryR\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x83\x02\n" +
	"\x14BoxCredentialService\x12\x80\x01\n" +
	"\x17DepositFederationClient\x120.boxcredential.v1.DepositFederationClientRequest\x1a1.boxcredential.v1.DepositFederationClientResponse\"\x00\x12h\n" +
	"\x0fFetchBoxSecrets\x12(.boxcredential.v1.FetchBoxSecretsRequest\x1a).boxcredential.v1.FetchBoxSecretsResponse\"\x00BJZHgithub.com/fairtier/workspace-api/proto/boxcredential/v1;boxcredentialv1b\x06proto3"

var (
	file_boxcredential_proto_rawDescOnce sync.Once
	file_boxcredential_proto_rawDescData []byte
)

func file_boxcredential_proto_rawDescGZIP() []byte {
	file_boxcredential_proto_rawDescOnce.Do(func() {
		file_boxcredential_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boxcredential_proto_rawDesc), len(file_boxcredential_proto_rawDesc)))
	})
	return file_boxcredential_proto_rawDescData
}

var file_boxcredential_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_boxcredential_proto_goTypes = []any{
	(*DepositFederationClientRequest)(nil),  // 0: boxcredential.v1.DepositFederationClientRequest
	(*DepositFederationClientResponse)(nil), // 1: boxcredential.v1.DepositFederationClientResponse
	(*FetchBoxSecretsRequest)(nil),          // 2: boxcredential.v1.FetchBoxSecretsRequest
	(*FetchBoxSecretsResponse)(nil),         // 3: boxcredential.v1.FetchBoxSecretsResponse
	nil,                                     // 4: boxcredential.v1.FetchBoxSecretsResponse.SecretsEntry
}
var file_boxcredential_proto_depIdxs = []int32{
	4, // 0: boxcredential.v1.FetchBoxSecretsResponse.secrets:type_name -> boxcredential.v1.FetchBoxSecretsResponse.SecretsEntry
	0, // 1: boxcredential.v1.BoxCredentialService.DepositFederationClient:input_type -> boxcredential.v1.DepositFederationClientRequest
	2, // 2: boxcredential.v1.BoxCredentialService.FetchBoxSecrets:input_type -> boxcredential.v1.FetchBoxSecretsRequest
	1, // 3: boxcredential.v1.BoxCredentialService.DepositFederationClient:output_type -> boxcredential.v1.DepositFederationClientResponse
	3, // 4: boxcredential.v1.BoxCredentialService.FetchBoxSecrets:output_type -> boxcredential.v1.FetchBoxSecretsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_boxcredential_proto_init() }
func file_boxcredential_proto_init() {
	if File_boxcredential_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boxcredential_proto_rawDesc), len(file_boxcredential_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boxcredential_proto_goTypes,
		DependencyIndexes: file_boxcredential_proto_depIdxs,
		MessageInfos:      file_boxcredential_proto_msgTypes,
	}.Build()
	File_boxcredential_proto = out.File
	file_boxcredential_proto_goTypes = nil
	file_boxcredential_proto_depIdxs = nil
}
