// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: snapshot.proto

package snapshotv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fairtier/workspace-api/proto/snapshot/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SnapshotServiceName is the fully-qualified name of the SnapshotService service.
	SnapshotServiceName = "snapshot.v1.SnapshotService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SnapshotServiceTriggerSnapshotProcedure is the fully-qualified name of the SnapshotService's
	// TriggerSnapshot RPC.
	SnapshotServiceTriggerSnapshotProcedure = "/snapshot.v1.SnapshotService/TriggerSnapshot"
	// SnapshotServiceListSnapshotsProcedure is the fully-qualified name of the SnapshotService's
	// ListSnapshots RPC.
	SnapshotServiceListSnapshotsProcedure = "/snapshot.v1.SnapshotService/ListSnapshots"
)

// SnapshotServiceClient is a client for the snapshot.v1.SnapshotService service.
type SnapshotServiceClient interface {
	// TriggerSnapshot creates a new snapshot of the target app's project directory.
	// Returns "unchanged" if the directory hasn't changed since the last snapshot.
	TriggerSnapshot(context.Context, *connect.Request[v1.TriggerSnapshotRequest]) (*connect.Response[v1.TriggerSnapshotResponse], error)
	// ListSnapshots returns all available snapshots for the target app,
	// ordered by timestamp descending.
	ListSnapshots(context.Context, *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListSnapshotsResponse], error)
}

// NewSnapshotServiceClient constructs a client for the snapshot.v1.SnapshotService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSnapshotServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SnapshotServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	snapshotServiceMethods := v1.File_snapshot_proto.Services().ByName("SnapshotService").Methods()
	return &snapshotServiceClient{
		triggerSnapshot: connect.NewClient[v1.TriggerSnapshotRequest, v1.TriggerSnapshotResponse](
			httpClient,
			baseURL+SnapshotServiceTriggerSnapshotProcedure,
			connect.WithSchema(snapshotServiceMethods.ByName("TriggerSnapshot")),
			connect.WithClientOptions(opts...),
		),
		listSnapshots: connect.NewClient[v1.ListSnapshotsRequest, v1.ListSnapshotsResponse](
			httpClient,
			baseURL+SnapshotServiceListSnapshotsProcedure,
			connect.WithSchema(snapshotServiceMethods.ByName("ListSnapshots")),
			connect.WithClientOptions(opts...),
		),
	}
}

// snapshotServiceClient implements SnapshotServiceClient.
type snapshotServiceClient struct {
	triggerSnapshot *connect.Client[v1.TriggerSnapshotRequest, v1.TriggerSnapshotResponse]
	listSnapshots   *connect.Client[v1.ListSnapshotsRequest, v1.ListSnapshotsResponse]
}

// TriggerSnapshot calls snapshot.v1.SnapshotService.TriggerSnapshot.
func (c *snapshotServiceClient) TriggerSnapshot(ctx context.Context, req *connect.Request[v1.TriggerSnapshotRequest]) (*connect.Response[v1.TriggerSnapshotResponse], error) {
	return c.triggerSnapshot.CallUnary(ctx, req)
}

// ListSnapshots calls snapshot.v1.SnapshotService.ListSnapshots.
func (c *snapshotServiceClient) ListSnapshots(ctx context.Context, req *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListSnapshotsResponse], error) {
	return c.listSnapshots.CallUnary(ctx, req)
}

// SnapshotServiceHandler is an implementation of the snapshot.v1.SnapshotService service.
type SnapshotServiceHandler interface {
	// TriggerSnapshot creates a new snapshot of the target app's project directory.
	// Returns "unchanged" if the directory hasn't changed since the last snapshot.
	TriggerSnapshot(context.Context, *connect.Request[v1.TriggerSnapshotRequest]) (*connect.Response[v1.TriggerSnapshotResponse], error)
	// ListSnapshots returns all available snapshots for the target app,
	// ordered by timestamp descending.
	ListSnapshots(context.Context, *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListSnapshotsResponse], error)
}

// NewSnapshotServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSnapshotServiceHandler(svc SnapshotServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	snapshotServiceMethods := v1.File_snapshot_proto.Services().ByName("SnapshotService").Methods()
	snapshotServiceTriggerSnapshotHandler := connect.NewUnaryHandler(
		SnapshotServiceTriggerSnapshotProcedure,
		svc.TriggerSnapshot,
		connect.WithSchema(snapshotServiceMethods.ByName("TriggerSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	snapshotServiceListSnapshotsHandler := connect.NewUnaryHandler(
		SnapshotServiceListSnapshotsProcedure,
		svc.ListSnapshots,
		connect.WithSchema(snapshotServiceMethods.ByName("ListSnapshots")),
		connect.WithHandlerOptions(opts...),
	)
	return "/snapshot.v1.SnapshotService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SnapshotServiceTriggerSnapshotProcedure:
			snapshotServiceTriggerSnapshotHandler.ServeHTTP(w, r)
		case SnapshotServiceListSnapshotsProcedure:
			snapshotServiceListSnapshotsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSnapshotServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSnapshotServiceHandler struct{}

func (UnimplementedSnapshotServiceHandler) TriggerSnapshot(context.Context, *connect.Request[v1.TriggerSnapshotRequest]) (*connect.Response[v1.TriggerSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("snapshot.v1.SnapshotService.TriggerSnapshot is not implemented"))
}

func (UnimplementedSnapshotServiceHandler) ListSnapshots(context.Context, *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListSnapshotsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("snapshot.v1.SnapshotService.ListSnapshots is not implemented"))
}
