// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: transformation.proto

package transformationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transformation represents a git-backed dbt project execution config.
type Transformation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique transformation identifier (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant slug this transformation belongs to.
	CustomerSlug string `protobuf:"bytes,2,opt,name=customer_slug,json=customerSlug,proto3" json:"customer_slug,omitempty"`
	// Human-readable name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// HTTPS clone URL of the dbt project repo. Empty = the box-hosted Gitea
	// repo (fairtier-admin/transformations), whose URL and read token live on
	// the box only — central never stores box credentials.
	RepoUrl string `protobuf:"bytes,4,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	// Branch or tag to run; resolved to a commit SHA at run time. Default "main".
	RepoRef string `protobuf:"bytes,5,opt,name=repo_ref,json=repoRef,proto3" json:"repo_ref,omitempty"`
	// Cron expression, or empty.
	Schedule string `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// Run after this pipeline reports a successful run (UUID), or empty. The
	// chaining happens inside the dlt-worker, which executes both.
	TriggerAfterPipelineId string `protobuf:"bytes,7,opt,name=trigger_after_pipeline_id,json=triggerAfterPipelineId,proto3" json:"trigger_after_pipeline_id,omitempty"`
	// Optional dbt node selector passed as `--select` (e.g. "tag:daily").
	DbtSelector string `protobuf:"bytes,8,opt,name=dbt_selector,json=dbtSelector,proto3" json:"dbt_selector,omitempty"`
	Enabled     bool   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// RFC 3339 timestamps.
	CreatedAt string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// RFC 3339 timestamp of the most recent run (any status), empty if never
	// run. Populated by List/Get to avoid N+1 run lookups.
	LastRunAt string `protobuf:"bytes,12,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	// Status of the most recent run ("pending", "running", "success", "failed"),
	// empty if never run.
	LastRunStatus string `protobuf:"bytes,13,opt,name=last_run_status,json=lastRunStatus,proto3" json:"last_run_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transformation) Reset() {
	*x = Transformation{}
	mi := &file_transformation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transformation) ProtoMessage() {}

func (x *Transformation) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transformation.ProtoReflect.Descriptor instead.
func (*Transformation) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{0}
}

func (x *Transformation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transformation) GetCustomerSlug() string {
	if x != nil {
		return x.CustomerSlug
	}
	return ""
}

func (x *Transformation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Transformation) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *Transformation) GetRepoRef() string {
	if x != nil {
		return x.RepoRef
	}
	return ""
}

func (x *Transformation) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *Transformation) GetTriggerAfterPipelineId() string {
	if x != nil {
		return x.TriggerAfterPipelineId
	}
	return ""
}

func (x *Transformation) GetDbtSelector() string {
	if x != nil {
		return x.DbtSelector
	}
	return ""
}

func (x *Transformation) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Transformation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Transformation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Transformation) GetLastRunAt() string {
	if x != nil {
		return x.LastRunAt
	}
	return ""
}

func (x *Transformation) GetLastRunStatus() string {
	if x != nil {
		return x.LastRunStatus
	}
	return ""
}

// TransformationRun records a single dbt execution, attributable to an exact
// (code version, data state) pair via commit_sha.
type TransformationRun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique run identifier (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Transformation this run belongs to.
	TransformationId string `protobuf:"bytes,2,opt,name=transformation_id,json=transformationId,proto3" json:"transformation_id,omitempty"`
	// "pending", "running", "success", or "failed".
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// RFC 3339 timestamps.
	StartedAt   string `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt string `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Commit SHA the repo ref resolved to for this run.
	CommitSha string `protobuf:"bytes,6,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	// dbt node counts: models (and seeds/snapshots) executed / failed, tests
	// executed / failed.
	ModelsTotal  int32 `protobuf:"varint,7,opt,name=models_total,json=modelsTotal,proto3" json:"models_total,omitempty"`
	ModelsFailed int32 `protobuf:"varint,8,opt,name=models_failed,json=modelsFailed,proto3" json:"models_failed,omitempty"`
	TestsTotal   int32 `protobuf:"varint,9,opt,name=tests_total,json=testsTotal,proto3" json:"tests_total,omitempty"`
	TestsFailed  int32 `protobuf:"varint,10,opt,name=tests_failed,json=testsFailed,proto3" json:"tests_failed,omitempty"`
	// JSON array of per-node results, each entry carrying "name", "status",
	// "execution_time" and "message".
	//
	// (No indented lines here on purpose: protoc-gen-go runs the comment through
	// gofmt's doc-comment formatter, which turns an indented block into a code
	// block — and does it differently across Go releases, so the committed stub
	// would drift from what CI's toolchain regenerates.)
	ModelResults  string `protobuf:"bytes,11,opt,name=model_results,json=modelResults,proto3" json:"model_results,omitempty"`
	ErrorMessage  string `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     string `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformationRun) Reset() {
	*x = TransformationRun{}
	mi := &file_transformation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformationRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformationRun) ProtoMessage() {}

func (x *TransformationRun) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformationRun.ProtoReflect.Descriptor instead.
func (*TransformationRun) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{1}
}

func (x *TransformationRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransformationRun) GetTransformationId() string {
	if x != nil {
		return x.TransformationId
	}
	return ""
}

func (x *TransformationRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransformationRun) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *TransformationRun) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *TransformationRun) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *TransformationRun) GetModelsTotal() int32 {
	if x != nil {
		return x.ModelsTotal
	}
	return 0
}

func (x *TransformationRun) GetModelsFailed() int32 {
	if x != nil {
		return x.ModelsFailed
	}
	return 0
}

func (x *TransformationRun) GetTestsTotal() int32 {
	if x != nil {
		return x.TestsTotal
	}
	return 0
}

func (x *TransformationRun) GetTestsFailed() int32 {
	if x != nil {
		return x.TestsFailed
	}
	return 0
}

func (x *TransformationRun) GetModelResults() string {
	if x != nil {
		return x.ModelResults
	}
	return ""
}

func (x *TransformationRun) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TransformationRun) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateTransformationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Empty = hosted box repo.
	RepoUrl string `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	RepoRef string `protobuf:"bytes,3,opt,name=repo_ref,json=repoRef,proto3" json:"repo_ref,omitempty"`
	// JSON string: git deploy credentials for a connected repo, e.g.
	// {"username": "...", "token": "..."}. Ignored (and unnecessary) for the
	// hosted repo. Stored encrypted, only ever sent to the box worker.
	GitCredentials         string `protobuf:"bytes,4,opt,name=git_credentials,json=gitCredentials,proto3" json:"git_credentials,omitempty"`
	Schedule               string `protobuf:"bytes,5,opt,name=schedule,proto3" json:"schedule,omitempty"`
	TriggerAfterPipelineId string `protobuf:"bytes,6,opt,name=trigger_after_pipeline_id,json=triggerAfterPipelineId,proto3" json:"trigger_after_pipeline_id,omitempty"`
	DbtSelector            string `protobuf:"bytes,7,opt,name=dbt_selector,json=dbtSelector,proto3" json:"dbt_selector,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateTransformationRequest) Reset() {
	*x = CreateTransformationRequest{}
	mi := &file_transformation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransformationRequest) ProtoMessage() {}

func (x *CreateTransformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransformationRequest.ProtoReflect.Descriptor instead.
func (*CreateTransformationRequest) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTransformationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTransformationRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *CreateTransformationRequest) GetRepoRef() string {
	if x != nil {
		return x.RepoRef
	}
	return ""
}

func (x *CreateTransformationRequest) GetGitCredentials() string {
	if x != nil {
		return x.GitCredentials
	}
	return ""
}

func (x *CreateTransformationRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CreateTransformationRequest) GetTriggerAfterPipelineId() string {
	if x != nil {
		return x.TriggerAfterPipelineId
	}
	return ""
}

func (x *CreateTransformationRequest) GetDbtSelector() string {
	if x != nil {
		return x.DbtSelector
	}
	return ""
}

type CreateTransformationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Transformation *Transformation        `protobuf:"bytes,1,opt,name=transformation,proto3" json:"transformation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTransformationResponse) Reset() {
	*x = CreateTransformationResponse{}
	mi := &file_transformation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransformationResponse) ProtoMessage() {}

func (x *CreateTransformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransformationResponse.ProtoReflect.Descriptor instead.
func (*CreateTransformationResponse) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTransformationResponse) GetTransformation() *Transformation {
	if x != nil {
		return x.Transformation
	}
	return nil
}

type ListTransformationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransformationsRequest) Reset() {
	*x = ListTransformationsRequest{}
	mi := &file_transformation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransformationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransformationsRequest) ProtoMessage() {}

func (x *ListTransformationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransformationsRequest.ProtoReflect.Descriptor instead.
func (*ListTransformationsRequest) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{4}
}

type ListTransformationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Transformations []*Transformation      `protobuf:"bytes,1,rep,name=transformations,proto3" json:"transformations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListTransformationsResponse) Reset() {
	*x = ListTransformationsResponse{}
	mi := &file_transformation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransformationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransformationsResponse) ProtoMessage() {}

func (x *ListTransformationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransformationsResponse.ProtoReflect.Descriptor instead.
func (*ListTransformationsResponse) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{5}
}

func (x *ListTransformationsResponse) GetTransformations() []*Transformation {
	if x != nil {
		return x.Transformations
	}
	return nil
}

type GetTransformationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransformationRequest) Reset() {
	*x = GetTransformationRequest{}
	mi := &file_transformation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransformationRequest) ProtoMessage() {}

func (x *GetTransformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransformationRequest.ProtoReflect.Descriptor instead.
func (*GetTransformationRequest) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransformationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTransformationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Transformation *Transformation        `protobuf:"bytes,1,opt,name=transformation,proto3" json:"transformation,omitempty"`
	RecentRuns     []*TransformationRun   `protobuf:"bytes,2,rep,name=recent_runs,json=recentRuns,proto3" json:"recent_runs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTransformationResponse) Reset() {
	*x = GetTransformationResponse{}
	mi := &file_transformation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransformationResponse) ProtoMessage() {}

func (x *GetTransformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransformationResponse.ProtoReflect.Descriptor instead.
func (*GetTransformationResponse) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransformationResponse) GetTransformation() *Transformation {
	if x != nil {
		return x.Transformation
	}
	return nil
}

func (x *GetTransformationResponse) GetRecentRuns() []*TransformationRun {
	if x != nil {
		return x.RecentRuns
	}
	return nil
}

type UpdateTransformationRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RepoUrl string                 `protobuf:"bytes,3,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	RepoRef string                 `protobuf:"bytes,4,opt,name=repo_ref,json=repoRef,proto3" json:"repo_ref,omitempty"`
	// JSON string: git deploy credentials. Empty string = keep existing.
	GitCredentials         string `protobuf:"bytes,5,opt,name=git_credentials,json=gitCredentials,proto3" json:"git_credentials,omitempty"`
	Schedule               string `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	TriggerAfterPipelineId string `protobuf:"bytes,7,opt,name=trigger_after_pipeline_id,json=triggerAfterPipelineId,proto3" json:"trigger_after_pipeline_id,omitempty"`
	DbtSelector            string `protobuf:"bytes,8,opt,name=dbt_selector,json=dbtSelector,proto3" json:"dbt_selector,omitempty"`
	Enabled                bool   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateTransformationRequest) Reset() {
	*x = UpdateTransformationRequest{}
	mi := &file_transformation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransformationRequest) ProtoMessage() {}

func (x *UpdateTransformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransformationRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransformationRequest) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTransformationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTransformationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTransformationRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *UpdateTransformationRequest) GetRepoRef() string {
	if x != nil {
		return x.RepoRef
	}
	return ""
}

func (x *UpdateTransformationRequest) GetGitCredentials() string {
	if x != nil {
		return x.GitCredentials
	}
	return ""
}

func (x *UpdateTransformationRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *UpdateTransformationRequest) GetTriggerAfterPipelineId() string {
	if x != nil {
		return x.TriggerAfterPipelineId
	}
	return ""
}

func (x *UpdateTransformationRequest) GetDbtSelector() string {
	if x != nil {
		return x.DbtSelector
	}
	return ""
}

func (x *UpdateTransformationRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateTransformationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Transformation *Transformation        `protobuf:"bytes,1,opt,name=transformation,proto3" json:"transformation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTransformationResponse) Reset() {
	*x = UpdateTransformationResponse{}
	mi := &file_transformation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransformationResponse) ProtoMessage() {}

func (x *UpdateTransformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransformationResponse.ProtoReflect.Descriptor instead.
func (*UpdateTransformationResponse) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTransformationResponse) GetTransformation() *Transformation {
	if x != nil {
		return x.Transformation
	}
	return nil
}

type DeleteTransformationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransformationRequest) Reset() {
	*x = DeleteTransformationRequest{}
	mi := &file_transformation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransformationRequest) ProtoMessage() {}

func (x *DeleteTransformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransformationRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransformationRequest) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTransformationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTransformationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransformationResponse) Reset() {
	*x = DeleteTransformationResponse{}
	mi := &file_transformation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransformationResponse) ProtoMessage() {}

func (x *DeleteTransformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransformationResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransformationResponse) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{11}
}

type TriggerTransformationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerTransformationRequest) Reset() {
	*x = TriggerTransformationRequest{}
	mi := &file_transformation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerTransformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerTransformationRequest) ProtoMessage() {}

func (x *TriggerTransformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerTransformationRequest.ProtoReflect.Descriptor instead.
func (*TriggerTransformationRequest) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{12}
}

func (x *TriggerTransformationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TriggerTransformationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *TransformationRun     `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerTransformationResponse) Reset() {
	*x = TriggerTransformationResponse{}
	mi := &file_transformation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerTransformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerTransformationResponse) ProtoMessage() {}

func (x *TriggerTransformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerTransformationResponse.ProtoReflect.Descriptor instead.
func (*TriggerTransformationResponse) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{13}
}

func (x *TriggerTransformationResponse) GetRun() *TransformationRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type GetTransformationConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerSlug  string                 `protobuf:"bytes,1,opt,name=customer_slug,json=customerSlug,proto3" json:"customer_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransformationConfigsRequest) Reset() {
	*x = GetTransformationConfigsRequest{}
	mi := &file_transformation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransformationConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransformationConfigsRequest) ProtoMessage() {}

func (x *GetTransformationConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransformationConfigsRequest.ProtoReflect.Descriptor instead.
func (*GetTransformationConfigsRequest) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{14}
}

func (x *GetTransformationConfigsRequest) GetCustomerSlug() string {
	if x != nil {
		return x.CustomerSlug
	}
	return ""
}

type GetTransformationConfigsResponse struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Transformations []*TransformationConfigItem `protobuf:"bytes,1,rep,name=transformations,proto3" json:"transformations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTransformationConfigsResponse) Reset() {
	*x = GetTransformationConfigsResponse{}
	mi := &file_transformation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransformationConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransformationConfigsResponse) ProtoMessage() {}

func (x *GetTransformationConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransformationConfigsResponse.ProtoReflect.Descriptor instead.
func (*GetTransformationConfigsResponse) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{15}
}

func (x *GetTransformationConfigsResponse) GetTransformations() []*TransformationConfigItem {
	if x != nil {
		return x.Transformations
	}
	return nil
}

// TransformationConfigItem includes git_credentials (only sent to workers).
type TransformationConfigItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Empty = hosted box repo: the worker falls back to its TRANSFORM_REPO_URL
	// env (the box-local Gitea URL + token minted by the dlt seed Job).
	RepoUrl string `protobuf:"bytes,3,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	RepoRef string `protobuf:"bytes,4,opt,name=repo_ref,json=repoRef,proto3" json:"repo_ref,omitempty"`
	// JSON string: git deploy credentials for a connected repo.
	GitCredentials         string `protobuf:"bytes,5,opt,name=git_credentials,json=gitCredentials,proto3" json:"git_credentials,omitempty"`
	Schedule               string `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	TriggerAfterPipelineId string `protobuf:"bytes,7,opt,name=trigger_after_pipeline_id,json=triggerAfterPipelineId,proto3" json:"trigger_after_pipeline_id,omitempty"`
	DbtSelector            string `protobuf:"bytes,8,opt,name=dbt_selector,json=dbtSelector,proto3" json:"dbt_selector,omitempty"`
	Enabled                bool   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// True when a pending run exists (manual trigger).
	TriggerNow bool `protobuf:"varint,10,opt,name=trigger_now,json=triggerNow,proto3" json:"trigger_now,omitempty"`
	// UUID of the pending run to update (instead of creating a new one).
	PendingRunId string `protobuf:"bytes,11,opt,name=pending_run_id,json=pendingRunId,proto3" json:"pending_run_id,omitempty"`
	// RFC 3339 timestamp of last successful run, empty if never run.
	LastRunAt     string `protobuf:"bytes,12,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformationConfigItem) Reset() {
	*x = TransformationConfigItem{}
	mi := &file_transformation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformationConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformationConfigItem) ProtoMessage() {}

func (x *TransformationConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformationConfigItem.ProtoReflect.Descriptor instead.
func (*TransformationConfigItem) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{16}
}

func (x *TransformationConfigItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransformationConfigItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransformationConfigItem) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *TransformationConfigItem) GetRepoRef() string {
	if x != nil {
		return x.RepoRef
	}
	return ""
}

func (x *TransformationConfigItem) GetGitCredentials() string {
	if x != nil {
		return x.GitCredentials
	}
	return ""
}

func (x *TransformationConfigItem) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *TransformationConfigItem) GetTriggerAfterPipelineId() string {
	if x != nil {
		return x.TriggerAfterPipelineId
	}
	return ""
}

func (x *TransformationConfigItem) GetDbtSelector() string {
	if x != nil {
		return x.DbtSelector
	}
	return ""
}

func (x *TransformationConfigItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TransformationConfigItem) GetTriggerNow() bool {
	if x != nil {
		return x.TriggerNow
	}
	return false
}

func (x *TransformationConfigItem) GetPendingRunId() string {
	if x != nil {
		return x.PendingRunId
	}
	return ""
}

func (x *TransformationConfigItem) GetLastRunAt() string {
	if x != nil {
		return x.LastRunAt
	}
	return ""
}

type ReportTransformationRunRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransformationId string                 `protobuf:"bytes,1,opt,name=transformation_id,json=transformationId,proto3" json:"transformation_id,omitempty"`
	// "success" or "failed".
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// RFC 3339 timestamps.
	StartedAt    string `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt  string `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CommitSha    string `protobuf:"bytes,5,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	ModelsTotal  int32  `protobuf:"varint,6,opt,name=models_total,json=modelsTotal,proto3" json:"models_total,omitempty"`
	ModelsFailed int32  `protobuf:"varint,7,opt,name=models_failed,json=modelsFailed,proto3" json:"models_failed,omitempty"`
	TestsTotal   int32  `protobuf:"varint,8,opt,name=tests_total,json=testsTotal,proto3" json:"tests_total,omitempty"`
	TestsFailed  int32  `protobuf:"varint,9,opt,name=tests_failed,json=testsFailed,proto3" json:"tests_failed,omitempty"`
	// JSON array of per-node results.
	ModelResults  string `protobuf:"bytes,10,opt,name=model_results,json=modelResults,proto3" json:"model_results,omitempty"`
	ErrorMessage  string `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RunId         string `protobuf:"bytes,12,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // Update existing run if set.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTransformationRunRequest) Reset() {
	*x = ReportTransformationRunRequest{}
	mi := &file_transformation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTransformationRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTransformationRunRequest) ProtoMessage() {}

func (x *ReportTransformationRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTransformationRunRequest.ProtoReflect.Descriptor instead.
func (*ReportTransformationRunRequest) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{17}
}

func (x *ReportTransformationRunRequest) GetTransformationId() string {
	if x != nil {
		return x.TransformationId
	}
	return ""
}

func (x *ReportTransformationRunRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportTransformationRunRequest) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ReportTransformationRunRequest) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *ReportTransformationRunRequest) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *ReportTransformationRunRequest) GetModelsTotal() int32 {
	if x != nil {
		return x.ModelsTotal
	}
	return 0
}

func (x *ReportTransformationRunRequest) GetModelsFailed() int32 {
	if x != nil {
		return x.ModelsFailed
	}
	return 0
}

func (x *ReportTransformationRunRequest) GetTestsTotal() int32 {
	if x != nil {
		return x.TestsTotal
	}
	return 0
}

func (x *ReportTransformationRunRequest) GetTestsFailed() int32 {
	if x != nil {
		return x.TestsFailed
	}
	return 0
}

func (x *ReportTransformationRunRequest) GetModelResults() string {
	if x != nil {
		return x.ModelResults
	}
	return ""
}

func (x *ReportTransformationRunRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReportTransformationRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ReportTransformationRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTransformationRunResponse) Reset() {
	*x = ReportTransformationRunResponse{}
	mi := &file_transformation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTransformationRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTransformationRunResponse) ProtoMessage() {}

func (x *ReportTransformationRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transformation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTransformationRunResponse.ProtoReflect.Descriptor instead.
func (*ReportTransformationRunResponse) Descriptor() ([]byte, []int) {
	return file_transformation_proto_rawDescGZIP(), []int{18}
}

var File_transformation_proto protoreflect.FileDescriptor

const file_transformation_proto_rawDesc = "" +
	"\n" +
	"\x14transformation.proto\x12\x11transformation.v1\"\xa9\x03\n" +
	"\x0eTransformation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcustomer_slug\x18\x02 \x01(\tR\fcustomerSlug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\brepo_url\x18\x04 \x01(\tR\arepoUrl\x12\x19\n" +
	"\brepo_ref\x18\x05 \x01(\tR\arepoRef\x12\x1a\n" +
	"\bschedule\x18\x06 \x01(\tR\bschedule\x129\n" +
	"\x19trigger_after_pipeline_id\x18\a \x01(\tR\x16triggerAfterPipelineId\x12!\n" +
	"\fdbt_selector\x18\b \x01(\tR\vdbtSelector\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x1e\n" +
	"\vlast_run_at\x18\f \x01(\tR\tlastRunAt\x12&\n" +
	"\x0flast_run_status\x18\r \x01(\tR\rlastRunStatus\"\xbe\x03\n" +
	"\x11TransformationRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11transformation_id\x18\x02 \x01(\tR\x10transformationId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x05 \x01(\tR\vcompletedAt\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x06 \x01(\tR\tcommitSha\x12!\n" +
	"\fmodels_total\x18\a \x01(\x05R\vmodelsTotal\x12#\n" +
	"\rmodels_failed\x18\b \x01(\x05R\fmodelsFailed\x12\x1f\n" +
	"\vtests_total\x18\t \x01(\x05R\n" +
	"testsTotal\x12!\n" +
	"\ftests_failed\x18\n" +
	" \x01(\x05R\vtestsFailed\x12#\n" +
	"\rmodel_results\x18\v \x01(\tR\fmodelResults\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\"\x8a\x02\n" +
	"\x1bCreateTransformationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\brepo_url\x18\x02 \x01(\tR\arepoUrl\x12\x19\n" +
	"\brepo_ref\x18\x03 \x01(\tR\arepoRef\x12'\n" +
	"\x0fgit_credentials\x18\x04 \x01(\tR\x0egitCredentials\x12\x1a\n" +
	"\bschedule\x18\x05 \x01(\tR\bschedule\x129\n" +
	"\x19trigger_after_pipeline_id\x18\x06 \x01(\tR\x16triggerAfterPipelineId\x12!\n" +
	"\fdbt_selector\x18\a \x01(\tR\vdbtSelector\"i\n" +
	"\x1cCreateTransformationResponse\x12I\n" +
	"\x0etransformation\x18\x01 \x01(\v2!.transformation.v1.TransformationR\x0etransformation\"\x1c\n" +
	"\x1aListTransformationsRequest\"j\n" +
	"\x1bListTransformationsResponse\x12K\n" +
	"\x0ftransformations\x18\x01 \x03(\v2!.transformation.v1.TransformationR\x0ftransformations\"*\n" +
	"\x18GetTransformationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xad\x01\n" +
	"\x19GetTransformationResponse\x12I\n" +
	"\x0etransformation\x18\x01 \x01(\v2!.transformation.v1.TransformationR\x0etransformation\x12E\n" +
	"\vrecent_runs\x18\x02 \x03(\v2$.transformation.v1.TransformationRunR\n" +
	"recentRuns\"\xb4\x02\n" +
	"\x1bUpdateTransformationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\brepo_url\x18\x03 \x01(\tR\arepoUrl\x12\x19\n" +
	"\brepo_ref\x18\x04 \x01(\tR\arepoRef\x12'\n" +
	"\x0fgit_credentials\x18\x05 \x01(\tR\x0egitCredentials\x12\x1a\n" +
	"\bschedule\x18\x06 \x01(\tR\bschedule\x129\n" +
	"\x19trigger_after_pipeline_id\x18\a \x01(\tR\x16triggerAfterPipelineId\x12!\n" +
	"\fdbt_selector\x18\b \x01(\tR\vdbtSelector\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\"i\n" +
	"\x1cUpdateTransformationResponse\x12I\n" +
	"\x0etransformation\x18\x01 \x01(\v2!.transformation.v1.TransformationR\x0etransformation\"-\n" +
	"\x1bDeleteTransformationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\x1cDeleteTransformationResponse\".\n" +
	"\x1cTriggerTransformationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x1dTriggerTransformationResponse\x126\n" +
	"\x03run\x18\x01 \x01(\v2$.transformation.v1.TransformationRunR\x03run\"F\n" +
	"\x1fGetTransformationConfigsRequest\x12#\n" +
	"\rcustomer_slug\x18\x01 \x01(\tR\fcustomerSlug\"y\n" +
	" GetTransformationConfigsResponse\x12U\n" +
	"\x0ftransformations\x18\x01 \x03(\v2+.transformation.v1.TransformationConfigItemR\x0ftransformations\"\x98\x03\n" +
	"\x18TransformationConfigItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\brepo_url\x18\x03 \x01(\tR\arepoUrl\x12\x19\n" +
	"\brepo_ref\x18\x04 \x01(\tR\arepoRef\x12'\n" +
	"\x0fgit_credentials\x18\x05 \x01(\tR\x0egitCredentials\x12\x1a\n" +
	"\bschedule\x18\x06 \x01(\tR\bschedule\x129\n" +
	"\x19trigger_after_pipeline_id\x18\a \x01(\tR\x16triggerAfterPipelineId\x12!\n" +
	"\fdbt_selector\x18\b \x01(\tR\vdbtSelector\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x12\x1f\n" +
	"\vtrigger_now\x18\n" +
	" \x01(\bR\n" +
	"triggerNow\x12$\n" +
	"\x0epending_run_id\x18\v \x01(\tR\fpendingRunId\x12\x1e\n" +
	"\vlast_run_at\x18\f \x01(\tR\tlastRunAt\"\xb3\x03\n" +
	"\x1eReportTransformationRunRequest\x12+\n" +
	"\x11transformation_id\x18\x01 \x01(\tR\x10transformationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x04 \x01(\tR\vcompletedAt\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x05 \x01(\tR\tcommitSha\x12!\n" +
	"\fmodels_total\x18\x06 \x01(\x05R\vmodelsTotal\x12#\n" +
	"\rmodels_failed\x18\a \x01(\x05R\fmodelsFailed\x12\x1f\n" +
	"\vtests_total\x18\b \x01(\x05R\n" +
	"testsTotal\x12!\n" +
	"\ftests_failed\x18\t \x01(\x05R\vtestsFailed\x12#\n" +
	"\rmodel_results\x18\n" +
	" \x01(\tR\fmodelResults\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12\x15\n" +
	"\x06run_id\x18\f \x01(\tR\x05runId\"!\n" +
	"\x1fReportTransformationRunResponse2\xfd\a\n" +
	"\x15TransformationService\x12y\n" +
	"\x14CreateTransformation\x12..transformation.v1.CreateTransformationRequest\x1a/.transformation.v1.CreateTransformationResponse\"\x00\x12v\n" +
	"\x13ListTransformations\x12-.transformation.v1.ListTransformationsRequest\x1a..transformation.v1.ListTransformationsResponse\"\x00\x12p\n" +
	"\x11GetTransformation\x12+.transformation.v1.GetTransformationRequest\x1a,.transformation.v1.GetTransformationResponse\"\x00\x12y\n" +
	"\x14UpdateTransformation\x12..transformation.v1.UpdateTransformationRequest\x1a/.transformation.v1.UpdateTransformationResponse\"\x00\x12y\n" +
	"\x14DeleteTransformation\x12..transformation.v1.DeleteTransformationRequest\x1a/.transformation.v1.DeleteTransformationResponse\"\x00\x12|\n" +
	"\x15TriggerTransformation\x12/.transformation.v1.TriggerTransformationRequest\x1a0.transformation.v1.TriggerTransformationResponse\"\x00\x12\x85\x01\n" +
	"\x18GetTransformationConfigs\x122.transformation.v1.GetTransformationConfigsRequest\x1a3.transformation.v1.GetTransformationConfigsResponse\"\x00\x12\x82\x01\n" +
	"\x17ReportTransformationRun\x121.transformation.v1.ReportTransformationRunRequest\x1a2.transformation.v1.ReportTransformationRunResponse\"\x00BLZJgithub.com/fairtier/workspace-api/proto/transformation/v1;transformationv1b\x06proto3"

var (
	file_transformation_proto_rawDescOnce sync.Once
	file_transformation_proto_rawDescData []byte
)

func file_transformation_proto_rawDescGZIP() []byte {
	file_transformation_proto_rawDescOnce.Do(func() {
		file_transformation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transformation_proto_rawDesc), len(file_transformation_proto_rawDesc)))
	})
	return file_transformation_proto_rawDescData
}

var file_transformation_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_transformation_proto_goTypes = []any{
	(*Transformation)(nil),                   // 0: transformation.v1.Transformation
	(*TransformationRun)(nil),                // 1: transformation.v1.TransformationRun
	(*CreateTransformationRequest)(nil),      // 2: transformation.v1.CreateTransformationRequest
	(*CreateTransformationResponse)(nil),     // 3: transformation.v1.CreateTransformationResponse
	(*ListTransformationsRequest)(nil),       // 4: transformation.v1.ListTransformationsRequest
	(*ListTransformationsResponse)(nil),      // 5: transformation.v1.ListTransformationsResponse
	(*GetTransformationRequest)(nil),         // 6: transformation.v1.GetTransformationRequest
	(*GetTransformationResponse)(nil),        // 7: transformation.v1.GetTransformationResponse
	(*UpdateTransformationRequest)(nil),      // 8: transformation.v1.UpdateTransformationRequest
	(*UpdateTransformationResponse)(nil),     // 9: transformation.v1.UpdateTransformationResponse
	(*DeleteTransformationRequest)(nil),      // 10: transformation.v1.DeleteTransformationRequest
	(*DeleteTransformationResponse)(nil),     // 11: transformation.v1.DeleteTransformationResponse
	(*TriggerTransformationRequest)(nil),     // 12: transformation.v1.TriggerTransformationRequest
	(*TriggerTransformationResponse)(nil),    // 13: transformation.v1.TriggerTransformationResponse
	(*GetTransformationConfigsRequest)(nil),  // 14: transformation.v1.GetTransformationConfigsRequest
	(*GetTransformationConfigsResponse)(nil), // 15: transformation.v1.GetTransformationConfigsResponse
	(*TransformationConfigItem)(nil),         // 16: transformation.v1.TransformationConfigItem
	(*ReportTransformationRunRequest)(nil),   // 17: transformation.v1.ReportTransformationRunRequest
	(*ReportTransformationRunResponse)(nil),  // 18: transformation.v1.ReportTransformationRunResponse
}
var file_transformation_proto_depIdxs = []int32{
	0,  // 0: transformation.v1.CreateTransformationResponse.transformation:type_name -> transformation.v1.Transformation
	0,  // 1: transformation.v1.ListTransformationsResponse.transformations:type_name -> transformation.v1.Transformation
	0,  // 2: transformation.v1.GetTransformationResponse.transformation:type_name -> transformation.v1.Transformation
	1,  // 3: transformation.v1.GetTransformationResponse.recent_runs:type_name -> transformation.v1.TransformationRun
	0,  // 4: transformation.v1.UpdateTransformationResponse.transformation:type_name -> transformation.v1.Transformation
	1,  // 5: transformation.v1.TriggerTransformationResponse.run:type_name -> transformation.v1.TransformationRun
	16, // 6: transformation.v1.GetTransformationConfigsResponse.transformations:type_name -> transformation.v1.TransformationConfigItem
	2,  // 7: transformation.v1.TransformationService.CreateTransformation:input_type -> transformation.v1.CreateTransformationRequest
	4,  // 8: transformation.v1.TransformationService.ListTransformations:input_type -> transformation.v1.ListTransformationsRequest
	6,  // 9: transformation.v1.TransformationService.GetTransformation:input_type -> transformation.v1.GetTransformationRequest
	8,  // 10: transformation.v1.TransformationService.UpdateTransformation:input_type -> transformation.v1.UpdateTransformationRequest
	10, // 11: transformation.v1.TransformationService.DeleteTransformation:input_type -> transformation.v1.DeleteTransformationRequest
	12, // 12: transformation.v1.TransformationService.TriggerTransformation:input_type -> transformation.v1.TriggerTransformationRequest
	14, // 13: transformation.v1.TransformationService.GetTransformationConfigs:input_type -> transformation.v1.GetTransformationConfigsRequest
	17, // 14: transformation.v1.TransformationService.ReportTransformationRun:input_type -> transformation.v1.ReportTransformationRunRequest
	3,  // 15: transformation.v1.TransformationService.CreateTransformation:output_type -> transformation.v1.CreateTransformationResponse
	5,  // 16: transformation.v1.TransformationService.ListTransformations:output_type -> transformation.v1.ListTransformationsResponse
	7,  // 17: transformation.v1.TransformationService.GetTransformation:output_type -> transformation.v1.GetTransformationResponse
	9,  // 18: transformation.v1.TransformationService.UpdateTransformation:output_type -> transformation.v1.UpdateTransformationResponse
	11, // 19: transformation.v1.TransformationService.DeleteTransformation:output_type -> transformation.v1.DeleteTransformationResponse
	13, // 20: transformation.v1.TransformationService.TriggerTransformation:output_type -> transformation.v1.TriggerTransformationResponse
	15, // 21: transformation.v1.TransformationService.GetTransformationConfigs:output_type -> transformation.v1.GetTransformationConfigsResponse
	18, // 22: transformation.v1.TransformationService.ReportTransformationRun:output_type -> transformation.v1.ReportTransformationRunResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_transformation_proto_init() }
func file_transformation_proto_init() {
	if File_transformation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transformation_proto_rawDesc), len(file_transformation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transformation_proto_goTypes,
		DependencyIndexes: file_transformation_proto_depIdxs,
		MessageInfos:      file_transformation_proto_msgTypes,
	}.Build()
	File_transformation_proto = out.File
	file_transformation_proto_goTypes = nil
	file_transformation_proto_depIdxs = nil
}
