// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: boxcredential.proto

package boxcredentialv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fairtier/workspace-api/proto/boxcredential/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BoxCredentialServiceName is the fully-qualified name of the BoxCredentialService service.
	BoxCredentialServiceName = "boxcredential.v1.BoxCredentialService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BoxCredentialServiceDepositFederationClientProcedure is the fully-qualified name of the
	// BoxCredentialService's DepositFederationClient RPC.
	BoxCredentialServiceDepositFederationClientProcedure = "/boxcredential.v1.BoxCredentialService/DepositFederationClient"
	// BoxCredentialServiceFetchBoxSecretsProcedure is the fully-qualified name of the
	// BoxCredentialService's FetchBoxSecrets RPC.
	BoxCredentialServiceFetchBoxSecretsProcedure = "/boxcredential.v1.BoxCredentialService/FetchBoxSecrets"
)

// BoxCredentialServiceClient is a client for the boxcredential.v1.BoxCredentialService service.
type BoxCredentialServiceClient interface {
	// DepositFederationClient upserts the OAuth client the box minted for
	// itself so its users can sign in through the central identity provider.
	// Central registers the deposited pair as this tenant's client rather than
	// minting one and pushing it down — the secret that ends up in the box's
	// database is then the box's own, and its owner can rotate it by
	// re-depositing. Idempotent: the box seed Job re-deposits on every ArgoCD
	// sync.
	DepositFederationClient(context.Context, *connect.Request[v1.DepositFederationClientRequest]) (*connect.Response[v1.DepositFederationClientResponse], error)
	// FetchBoxSecrets returns the centrally-minted secrets central holds for the
	// calling tenant. The one RPC on this service that runs the other way, and
	// the reason it exists: a box's other channel for a centrally-known secret
	// is cloud-init, which is create-only on the provider and therefore frozen
	// at first boot. Anything delivered that way can never be changed or
	// rotated without replacing the customer's machine. This is the day-2 path.
	//
	// Same trust rules as the deposit — the slug is bound by issuer trust, so a
	// box can only ever read its own secrets. Idempotent and safe to call on a
	// loop: the box sync Job re-reads on every ArgoCD sync, which is what makes
	// a central rotation converge without touching the box.
	FetchBoxSecrets(context.Context, *connect.Request[v1.FetchBoxSecretsRequest]) (*connect.Response[v1.FetchBoxSecretsResponse], error)
}

// NewBoxCredentialServiceClient constructs a client for the boxcredential.v1.BoxCredentialService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBoxCredentialServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BoxCredentialServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	boxCredentialServiceMethods := v1.File_boxcredential_proto.Services().ByName("BoxCredentialService").Methods()
	return &boxCredentialServiceClient{
		depositFederationClient: connect.NewClient[v1.DepositFederationClientRequest, v1.DepositFederationClientResponse](
			httpClient,
			baseURL+BoxCredentialServiceDepositFederationClientProcedure,
			connect.WithSchema(boxCredentialServiceMethods.ByName("DepositFederationClient")),
			connect.WithClientOptions(opts...),
		),
		fetchBoxSecrets: connect.NewClient[v1.FetchBoxSecretsRequest, v1.FetchBoxSecretsResponse](
			httpClient,
			baseURL+BoxCredentialServiceFetchBoxSecretsProcedure,
			connect.WithSchema(boxCredentialServiceMethods.ByName("FetchBoxSecrets")),
			connect.WithClientOptions(opts...),
		),
	}
}

// boxCredentialServiceClient implements BoxCredentialServiceClient.
type boxCredentialServiceClient struct {
	depositFederationClient *connect.Client[v1.DepositFederationClientRequest, v1.DepositFederationClientResponse]
	fetchBoxSecrets         *connect.Client[v1.FetchBoxSecretsRequest, v1.FetchBoxSecretsResponse]
}

// DepositFederationClient calls boxcredential.v1.BoxCredentialService.DepositFederationClient.
func (c *boxCredentialServiceClient) DepositFederationClient(ctx context.Context, req *connect.Request[v1.DepositFederationClientRequest]) (*connect.Response[v1.DepositFederationClientResponse], error) {
	return c.depositFederationClient.CallUnary(ctx, req)
}

// FetchBoxSecrets calls boxcredential.v1.BoxCredentialService.FetchBoxSecrets.
func (c *boxCredentialServiceClient) FetchBoxSecrets(ctx context.Context, req *connect.Request[v1.FetchBoxSecretsRequest]) (*connect.Response[v1.FetchBoxSecretsResponse], error) {
	return c.fetchBoxSecrets.CallUnary(ctx, req)
}

// BoxCredentialServiceHandler is an implementation of the boxcredential.v1.BoxCredentialService
// service.
type BoxCredentialServiceHandler interface {
	// DepositFederationClient upserts the OAuth client the box minted for
	// itself so its users can sign in through the central identity provider.
	// Central registers the deposited pair as this tenant's client rather than
	// minting one and pushing it down — the secret that ends up in the box's
	// database is then the box's own, and its owner can rotate it by
	// re-depositing. Idempotent: the box seed Job re-deposits on every ArgoCD
	// sync.
	DepositFederationClient(context.Context, *connect.Request[v1.DepositFederationClientRequest]) (*connect.Response[v1.DepositFederationClientResponse], error)
	// FetchBoxSecrets returns the centrally-minted secrets central holds for the
	// calling tenant. The one RPC on this service that runs the other way, and
	// the reason it exists: a box's other channel for a centrally-known secret
	// is cloud-init, which is create-only on the provider and therefore frozen
	// at first boot. Anything delivered that way can never be changed or
	// rotated without replacing the customer's machine. This is the day-2 path.
	//
	// Same trust rules as the deposit — the slug is bound by issuer trust, so a
	// box can only ever read its own secrets. Idempotent and safe to call on a
	// loop: the box sync Job re-reads on every ArgoCD sync, which is what makes
	// a central rotation converge without touching the box.
	FetchBoxSecrets(context.Context, *connect.Request[v1.FetchBoxSecretsRequest]) (*connect.Response[v1.FetchBoxSecretsResponse], error)
}

// NewBoxCredentialServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBoxCredentialServiceHandler(svc BoxCredentialServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	boxCredentialServiceMethods := v1.File_boxcredential_proto.Services().ByName("BoxCredentialService").Methods()
	boxCredentialServiceDepositFederationClientHandler := connect.NewUnaryHandler(
		BoxCredentialServiceDepositFederationClientProcedure,
		svc.DepositFederationClient,
		connect.WithSchema(boxCredentialServiceMethods.ByName("DepositFederationClient")),
		connect.WithHandlerOptions(opts...),
	)
	boxCredentialServiceFetchBoxSecretsHandler := connect.NewUnaryHandler(
		BoxCredentialServiceFetchBoxSecretsProcedure,
		svc.FetchBoxSecrets,
		connect.WithSchema(boxCredentialServiceMethods.ByName("FetchBoxSecrets")),
		connect.WithHandlerOptions(opts...),
	)
	return "/boxcredential.v1.BoxCredentialService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BoxCredentialServiceDepositFederationClientProcedure:
			boxCredentialServiceDepositFederationClientHandler.ServeHTTP(w, r)
		case BoxCredentialServiceFetchBoxSecretsProcedure:
			boxCredentialServiceFetchBoxSecretsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBoxCredentialServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBoxCredentialServiceHandler struct{}

func (UnimplementedBoxCredentialServiceHandler) DepositFederationClient(context.Context, *connect.Request[v1.DepositFederationClientRequest]) (*connect.Response[v1.DepositFederationClientResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxcredential.v1.BoxCredentialService.DepositFederationClient is not implemented"))
}

func (UnimplementedBoxCredentialServiceHandler) FetchBoxSecrets(context.Context, *connect.Request[v1.FetchBoxSecretsRequest]) (*connect.Response[v1.FetchBoxSecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxcredential.v1.BoxCredentialService.FetchBoxSecrets is not implemented"))
}
