// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: boxcredential.proto

package boxcredentialv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fairtier/workspace-api/proto/boxcredential/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BoxCredentialServiceName is the fully-qualified name of the BoxCredentialService service.
	BoxCredentialServiceName = "boxcredential.v1.BoxCredentialService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BoxCredentialServiceDepositGitTokenProcedure is the fully-qualified name of the
	// BoxCredentialService's DepositGitToken RPC.
	BoxCredentialServiceDepositGitTokenProcedure = "/boxcredential.v1.BoxCredentialService/DepositGitToken"
	// BoxCredentialServiceDepositSnapshotTokenProcedure is the fully-qualified name of the
	// BoxCredentialService's DepositSnapshotToken RPC.
	BoxCredentialServiceDepositSnapshotTokenProcedure = "/boxcredential.v1.BoxCredentialService/DepositSnapshotToken"
	// BoxCredentialServiceDepositAgePublicKeyProcedure is the fully-qualified name of the
	// BoxCredentialService's DepositAgePublicKey RPC.
	BoxCredentialServiceDepositAgePublicKeyProcedure = "/boxcredential.v1.BoxCredentialService/DepositAgePublicKey"
)

// BoxCredentialServiceClient is a client for the boxcredential.v1.BoxCredentialService service.
type BoxCredentialServiceClient interface {
	// DepositGitToken upserts the box's editor git credential for the calling
	// tenant. Idempotent: the box seed Job re-deposits on every ArgoCD sync.
	DepositGitToken(context.Context, *connect.Request[v1.DepositGitTokenRequest]) (*connect.Response[v1.DepositGitTokenResponse], error)
	// DepositSnapshotToken upserts the bearer token guarding the box's
	// published rill-snapshot endpoint (the sidecar's AUTH_TOKEN). Central's
	// SnapshotService presents it when proxying a Console Save to the box.
	// Idempotent: the box seed Job re-deposits on every ArgoCD sync.
	DepositSnapshotToken(context.Context, *connect.Request[v1.DepositSnapshotTokenRequest]) (*connect.Response[v1.DepositSnapshotTokenResponse], error)
	// DepositAgePublicKey upserts the box's age PUBLIC key (the dlt-age
	// keypair's recipient; the private key never leaves the box). The
	// pipeline mirror encrypts source credentials to it and commits them as
	// pipelines/<name>.credentials.age (pipelines-as-files Phase 3); a
	// successful deposit triggers a best-effort mirror sync so existing
	// pipelines get their credential files immediately. Idempotent: the dlt
	// seed Job re-deposits on every ArgoCD sync.
	DepositAgePublicKey(context.Context, *connect.Request[v1.DepositAgePublicKeyRequest]) (*connect.Response[v1.DepositAgePublicKeyResponse], error)
}

// NewBoxCredentialServiceClient constructs a client for the boxcredential.v1.BoxCredentialService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBoxCredentialServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BoxCredentialServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	boxCredentialServiceMethods := v1.File_boxcredential_proto.Services().ByName("BoxCredentialService").Methods()
	return &boxCredentialServiceClient{
		depositGitToken: connect.NewClient[v1.DepositGitTokenRequest, v1.DepositGitTokenResponse](
			httpClient,
			baseURL+BoxCredentialServiceDepositGitTokenProcedure,
			connect.WithSchema(boxCredentialServiceMethods.ByName("DepositGitToken")),
			connect.WithClientOptions(opts...),
		),
		depositSnapshotToken: connect.NewClient[v1.DepositSnapshotTokenRequest, v1.DepositSnapshotTokenResponse](
			httpClient,
			baseURL+BoxCredentialServiceDepositSnapshotTokenProcedure,
			connect.WithSchema(boxCredentialServiceMethods.ByName("DepositSnapshotToken")),
			connect.WithClientOptions(opts...),
		),
		depositAgePublicKey: connect.NewClient[v1.DepositAgePublicKeyRequest, v1.DepositAgePublicKeyResponse](
			httpClient,
			baseURL+BoxCredentialServiceDepositAgePublicKeyProcedure,
			connect.WithSchema(boxCredentialServiceMethods.ByName("DepositAgePublicKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// boxCredentialServiceClient implements BoxCredentialServiceClient.
type boxCredentialServiceClient struct {
	depositGitToken      *connect.Client[v1.DepositGitTokenRequest, v1.DepositGitTokenResponse]
	depositSnapshotToken *connect.Client[v1.DepositSnapshotTokenRequest, v1.DepositSnapshotTokenResponse]
	depositAgePublicKey  *connect.Client[v1.DepositAgePublicKeyRequest, v1.DepositAgePublicKeyResponse]
}

// DepositGitToken calls boxcredential.v1.BoxCredentialService.DepositGitToken.
func (c *boxCredentialServiceClient) DepositGitToken(ctx context.Context, req *connect.Request[v1.DepositGitTokenRequest]) (*connect.Response[v1.DepositGitTokenResponse], error) {
	return c.depositGitToken.CallUnary(ctx, req)
}

// DepositSnapshotToken calls boxcredential.v1.BoxCredentialService.DepositSnapshotToken.
func (c *boxCredentialServiceClient) DepositSnapshotToken(ctx context.Context, req *connect.Request[v1.DepositSnapshotTokenRequest]) (*connect.Response[v1.DepositSnapshotTokenResponse], error) {
	return c.depositSnapshotToken.CallUnary(ctx, req)
}

// DepositAgePublicKey calls boxcredential.v1.BoxCredentialService.DepositAgePublicKey.
func (c *boxCredentialServiceClient) DepositAgePublicKey(ctx context.Context, req *connect.Request[v1.DepositAgePublicKeyRequest]) (*connect.Response[v1.DepositAgePublicKeyResponse], error) {
	return c.depositAgePublicKey.CallUnary(ctx, req)
}

// BoxCredentialServiceHandler is an implementation of the boxcredential.v1.BoxCredentialService
// service.
type BoxCredentialServiceHandler interface {
	// DepositGitToken upserts the box's editor git credential for the calling
	// tenant. Idempotent: the box seed Job re-deposits on every ArgoCD sync.
	DepositGitToken(context.Context, *connect.Request[v1.DepositGitTokenRequest]) (*connect.Response[v1.DepositGitTokenResponse], error)
	// DepositSnapshotToken upserts the bearer token guarding the box's
	// published rill-snapshot endpoint (the sidecar's AUTH_TOKEN). Central's
	// SnapshotService presents it when proxying a Console Save to the box.
	// Idempotent: the box seed Job re-deposits on every ArgoCD sync.
	DepositSnapshotToken(context.Context, *connect.Request[v1.DepositSnapshotTokenRequest]) (*connect.Response[v1.DepositSnapshotTokenResponse], error)
	// DepositAgePublicKey upserts the box's age PUBLIC key (the dlt-age
	// keypair's recipient; the private key never leaves the box). The
	// pipeline mirror encrypts source credentials to it and commits them as
	// pipelines/<name>.credentials.age (pipelines-as-files Phase 3); a
	// successful deposit triggers a best-effort mirror sync so existing
	// pipelines get their credential files immediately. Idempotent: the dlt
	// seed Job re-deposits on every ArgoCD sync.
	DepositAgePublicKey(context.Context, *connect.Request[v1.DepositAgePublicKeyRequest]) (*connect.Response[v1.DepositAgePublicKeyResponse], error)
}

// NewBoxCredentialServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBoxCredentialServiceHandler(svc BoxCredentialServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	boxCredentialServiceMethods := v1.File_boxcredential_proto.Services().ByName("BoxCredentialService").Methods()
	boxCredentialServiceDepositGitTokenHandler := connect.NewUnaryHandler(
		BoxCredentialServiceDepositGitTokenProcedure,
		svc.DepositGitToken,
		connect.WithSchema(boxCredentialServiceMethods.ByName("DepositGitToken")),
		connect.WithHandlerOptions(opts...),
	)
	boxCredentialServiceDepositSnapshotTokenHandler := connect.NewUnaryHandler(
		BoxCredentialServiceDepositSnapshotTokenProcedure,
		svc.DepositSnapshotToken,
		connect.WithSchema(boxCredentialServiceMethods.ByName("DepositSnapshotToken")),
		connect.WithHandlerOptions(opts...),
	)
	boxCredentialServiceDepositAgePublicKeyHandler := connect.NewUnaryHandler(
		BoxCredentialServiceDepositAgePublicKeyProcedure,
		svc.DepositAgePublicKey,
		connect.WithSchema(boxCredentialServiceMethods.ByName("DepositAgePublicKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/boxcredential.v1.BoxCredentialService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BoxCredentialServiceDepositGitTokenProcedure:
			boxCredentialServiceDepositGitTokenHandler.ServeHTTP(w, r)
		case BoxCredentialServiceDepositSnapshotTokenProcedure:
			boxCredentialServiceDepositSnapshotTokenHandler.ServeHTTP(w, r)
		case BoxCredentialServiceDepositAgePublicKeyProcedure:
			boxCredentialServiceDepositAgePublicKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBoxCredentialServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBoxCredentialServiceHandler struct{}

func (UnimplementedBoxCredentialServiceHandler) DepositGitToken(context.Context, *connect.Request[v1.DepositGitTokenRequest]) (*connect.Response[v1.DepositGitTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxcredential.v1.BoxCredentialService.DepositGitToken is not implemented"))
}

func (UnimplementedBoxCredentialServiceHandler) DepositSnapshotToken(context.Context, *connect.Request[v1.DepositSnapshotTokenRequest]) (*connect.Response[v1.DepositSnapshotTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxcredential.v1.BoxCredentialService.DepositSnapshotToken is not implemented"))
}

func (UnimplementedBoxCredentialServiceHandler) DepositAgePublicKey(context.Context, *connect.Request[v1.DepositAgePublicKeyRequest]) (*connect.Response[v1.DepositAgePublicKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxcredential.v1.BoxCredentialService.DepositAgePublicKey is not implemented"))
}
