// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: warehouse.proto

package warehousev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CredentialDelegationMode mirrors provisioning.v1.CredentialDelegationMode.
type CredentialDelegationMode int32

const (
	CredentialDelegationMode_CREDENTIAL_DELEGATION_MODE_UNSPECIFIED CredentialDelegationMode = 0
	// Lakekeeper vends temporary S3 credentials via STS (AWS, MinIO) or
	// temp-access-credentials (R2). Requires STS support on the provider.
	CredentialDelegationMode_CREDENTIAL_DELEGATION_MODE_VENDED CredentialDelegationMode = 1
	// Lakekeeper signs S3 requests server-side (AWS SigV4). Works with any
	// S3-compatible provider.
	CredentialDelegationMode_CREDENTIAL_DELEGATION_MODE_REMOTE_SIGNING CredentialDelegationMode = 2
	// No delegation. Client provides own S3 credentials via AWS env vars.
	CredentialDelegationMode_CREDENTIAL_DELEGATION_MODE_NONE CredentialDelegationMode = 3
)

// Enum value maps for CredentialDelegationMode.
var (
	CredentialDelegationMode_name = map[int32]string{
		0: "CREDENTIAL_DELEGATION_MODE_UNSPECIFIED",
		1: "CREDENTIAL_DELEGATION_MODE_VENDED",
		2: "CREDENTIAL_DELEGATION_MODE_REMOTE_SIGNING",
		3: "CREDENTIAL_DELEGATION_MODE_NONE",
	}
	CredentialDelegationMode_value = map[string]int32{
		"CREDENTIAL_DELEGATION_MODE_UNSPECIFIED":    0,
		"CREDENTIAL_DELEGATION_MODE_VENDED":         1,
		"CREDENTIAL_DELEGATION_MODE_REMOTE_SIGNING": 2,
		"CREDENTIAL_DELEGATION_MODE_NONE":           3,
	}
)

func (x CredentialDelegationMode) Enum() *CredentialDelegationMode {
	p := new(CredentialDelegationMode)
	*p = x
	return p
}

func (x CredentialDelegationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialDelegationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_warehouse_proto_enumTypes[0].Descriptor()
}

func (CredentialDelegationMode) Type() protoreflect.EnumType {
	return &file_warehouse_proto_enumTypes[0]
}

func (x CredentialDelegationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialDelegationMode.Descriptor instead.
func (CredentialDelegationMode) EnumDescriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{0}
}

// StorageProvider mirrors provisioning.v1.StorageProvider.
type StorageProvider int32

const (
	StorageProvider_STORAGE_PROVIDER_UNSPECIFIED   StorageProvider = 0
	StorageProvider_STORAGE_PROVIDER_AWS           StorageProvider = 1
	StorageProvider_STORAGE_PROVIDER_CLOUDFLARE_R2 StorageProvider = 2
	StorageProvider_STORAGE_PROVIDER_S3_COMPAT     StorageProvider = 3
)

// Enum value maps for StorageProvider.
var (
	StorageProvider_name = map[int32]string{
		0: "STORAGE_PROVIDER_UNSPECIFIED",
		1: "STORAGE_PROVIDER_AWS",
		2: "STORAGE_PROVIDER_CLOUDFLARE_R2",
		3: "STORAGE_PROVIDER_S3_COMPAT",
	}
	StorageProvider_value = map[string]int32{
		"STORAGE_PROVIDER_UNSPECIFIED":   0,
		"STORAGE_PROVIDER_AWS":           1,
		"STORAGE_PROVIDER_CLOUDFLARE_R2": 2,
		"STORAGE_PROVIDER_S3_COMPAT":     3,
	}
)

func (x StorageProvider) Enum() *StorageProvider {
	p := new(StorageProvider)
	*p = x
	return p
}

func (x StorageProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_warehouse_proto_enumTypes[1].Descriptor()
}

func (StorageProvider) Type() protoreflect.EnumType {
	return &file_warehouse_proto_enumTypes[1]
}

func (x StorageProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageProvider.Descriptor instead.
func (StorageProvider) EnumDescriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{1}
}

type ListWarehousesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesRequest) Reset() {
	*x = ListWarehousesRequest{}
	mi := &file_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesRequest) ProtoMessage() {}

func (x *ListWarehousesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesRequest.ProtoReflect.Descriptor instead.
func (*ListWarehousesRequest) Descriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{0}
}

type ListWarehousesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouses    []*Warehouse           `protobuf:"bytes,1,rep,name=warehouses,proto3" json:"warehouses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesResponse) Reset() {
	*x = ListWarehousesResponse{}
	mi := &file_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesResponse) ProtoMessage() {}

func (x *ListWarehousesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesResponse.ProtoReflect.Descriptor instead.
func (*ListWarehousesResponse) Descriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *ListWarehousesResponse) GetWarehouses() []*Warehouse {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

type CreateWarehouseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Warehouse name. Must be unique within the tenant's catalog.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Key prefix to isolate this warehouse's data within the bucket.
	// Defaults to the warehouse name if omitted.
	KeyPrefix string `protobuf:"bytes,2,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	// Optional custom S3 storage config. If omitted, inherits the workspace's
	// effective S3 configuration (managed R2 or BYOS).
	S3            *S3Config `protobuf:"bytes,3,opt,name=s3,proto3" json:"s3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWarehouseRequest) Reset() {
	*x = CreateWarehouseRequest{}
	mi := &file_warehouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWarehouseRequest) ProtoMessage() {}

func (x *CreateWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWarehouseRequest.ProtoReflect.Descriptor instead.
func (*CreateWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWarehouseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWarehouseRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *CreateWarehouseRequest) GetS3() *S3Config {
	if x != nil {
		return x.S3
	}
	return nil
}

// S3Config mirrors provisioning.v1.S3Config field-for-field (same numbers and
// enum values, so it is wire-compatible). The workspace plane carries its own
// copy so its proto module stays independent of the control plane's.
type S3Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bucket name (e.g. "ft-acme").
	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// Key prefix within the bucket. Internal only.
	KeyPrefix string `protobuf:"bytes,2,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	// S3 endpoint URL (e.g. "https://<account>.r2.cloudflarestorage.com").
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// S3 region (e.g. "auto" for R2, "us-east-1" for AWS).
	Region string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	// Access key ID for direct S3 access.
	AccessKeyId string `protobuf:"bytes,5,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	// Secret access key for direct S3 access.
	SecretAccessKey string `protobuf:"bytes,6,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	// Whether to use path-style S3 access (required for some providers).
	PathStyleAccess *bool `protobuf:"varint,7,opt,name=path_style_access,json=pathStyleAccess,proto3,oneof" json:"path_style_access,omitempty"`
	// Whether STS credential vending is enabled. Internal only.
	StsEnabled *bool `protobuf:"varint,8,opt,name=sts_enabled,json=stsEnabled,proto3,oneof" json:"sts_enabled,omitempty"`
	// Whether Lakekeeper remote signing is enabled. Internal only.
	RemoteSigningEnabled *bool `protobuf:"varint,9,opt,name=remote_signing_enabled,json=remoteSigningEnabled,proto3,oneof" json:"remote_signing_enabled,omitempty"`
	// Cloudflare API token for R2 management. Internal only.
	CloudflareApiToken string `protobuf:"bytes,10,opt,name=cloudflare_api_token,json=cloudflareApiToken,proto3" json:"cloudflare_api_token,omitempty"`
	// Cloudflare account ID (used with R2 credential vending).
	CloudflareAccountId string `protobuf:"bytes,11,opt,name=cloudflare_account_id,json=cloudflareAccountId,proto3" json:"cloudflare_account_id,omitempty"`
	// Credential delegation mode.
	CredentialDelegationMode CredentialDelegationMode `protobuf:"varint,12,opt,name=credential_delegation_mode,json=credentialDelegationMode,proto3,enum=warehouse.v1.CredentialDelegationMode" json:"credential_delegation_mode,omitempty"`
	// Storage provider.
	StorageProvider StorageProvider `protobuf:"varint,13,opt,name=storage_provider,json=storageProvider,proto3,enum=warehouse.v1.StorageProvider" json:"storage_provider,omitempty"`
	// AWS STS assume-role ARN (only used for AWS + vended credentials).
	AssumeRoleArn string `protobuf:"bytes,14,opt,name=assume_role_arn,json=assumeRoleArn,proto3" json:"assume_role_arn,omitempty"`
	// Storage mode lifecycle. Terminal states: "managed", "byos". Transient
	// states (set by the backend, never by the client): "migrating-to-byos",
	// "migrating-to-managed". Customers always send a terminal value; the
	// backend auto-promotes on transition.
	StorageMode   string `protobuf:"bytes,15,opt,name=storage_mode,json=storageMode,proto3" json:"storage_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3Config) Reset() {
	*x = S3Config{}
	mi := &file_warehouse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Config) ProtoMessage() {}

func (x *S3Config) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Config.ProtoReflect.Descriptor instead.
func (*S3Config) Descriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{3}
}

func (x *S3Config) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3Config) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *S3Config) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3Config) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3Config) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *S3Config) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *S3Config) GetPathStyleAccess() bool {
	if x != nil && x.PathStyleAccess != nil {
		return *x.PathStyleAccess
	}
	return false
}

func (x *S3Config) GetStsEnabled() bool {
	if x != nil && x.StsEnabled != nil {
		return *x.StsEnabled
	}
	return false
}

func (x *S3Config) GetRemoteSigningEnabled() bool {
	if x != nil && x.RemoteSigningEnabled != nil {
		return *x.RemoteSigningEnabled
	}
	return false
}

func (x *S3Config) GetCloudflareApiToken() string {
	if x != nil {
		return x.CloudflareApiToken
	}
	return ""
}

func (x *S3Config) GetCloudflareAccountId() string {
	if x != nil {
		return x.CloudflareAccountId
	}
	return ""
}

func (x *S3Config) GetCredentialDelegationMode() CredentialDelegationMode {
	if x != nil {
		return x.CredentialDelegationMode
	}
	return CredentialDelegationMode_CREDENTIAL_DELEGATION_MODE_UNSPECIFIED
}

func (x *S3Config) GetStorageProvider() StorageProvider {
	if x != nil {
		return x.StorageProvider
	}
	return StorageProvider_STORAGE_PROVIDER_UNSPECIFIED
}

func (x *S3Config) GetAssumeRoleArn() string {
	if x != nil {
		return x.AssumeRoleArn
	}
	return ""
}

func (x *S3Config) GetStorageMode() string {
	if x != nil {
		return x.StorageMode
	}
	return ""
}

type CreateWarehouseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created warehouse.
	Warehouse     *Warehouse `protobuf:"bytes,1,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWarehouseResponse) Reset() {
	*x = CreateWarehouseResponse{}
	mi := &file_warehouse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWarehouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWarehouseResponse) ProtoMessage() {}

func (x *CreateWarehouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWarehouseResponse.ProtoReflect.Descriptor instead.
func (*CreateWarehouseResponse) Descriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWarehouseResponse) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

// Warehouse represents an Iceberg warehouse in Lakekeeper.
type Warehouse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lakekeeper-assigned warehouse UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Warehouse name.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_warehouse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_warehouse_proto_rawDescGZIP(), []int{5}
}

func (x *Warehouse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Warehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_warehouse_proto protoreflect.FileDescriptor

const file_warehouse_proto_rawDesc = "" +
	"\n" +
	"\x0fwarehouse.proto\x12\fwarehouse.v1\"\x17\n" +
	"\x15ListWarehousesRequest\"Q\n" +
	"\x16ListWarehousesResponse\x127\n" +
	"\n" +
	"warehouses\x18\x01 \x03(\v2\x17.warehouse.v1.WarehouseR\n" +
	"warehouses\"s\n" +
	"\x16CreateWarehouseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x02 \x01(\tR\tkeyPrefix\x12&\n" +
	"\x02s3\x18\x03 \x01(\v2\x16.warehouse.v1.S3ConfigR\x02s3\"\xf9\x05\n" +
	"\bS3Config\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x02 \x01(\tR\tkeyPrefix\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\"\n" +
	"\raccess_key_id\x18\x05 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x06 \x01(\tR\x0fsecretAccessKey\x12/\n" +
	"\x11path_style_access\x18\a \x01(\bH\x00R\x0fpathStyleAccess\x88\x01\x01\x12$\n" +
	"\vsts_enabled\x18\b \x01(\bH\x01R\n" +
	"stsEnabled\x88\x01\x01\x129\n" +
	"\x16remote_signing_enabled\x18\t \x01(\bH\x02R\x14remoteSigningEnabled\x88\x01\x01\x120\n" +
	"\x14cloudflare_api_token\x18\n" +
	" \x01(\tR\x12cloudflareApiToken\x122\n" +
	"\x15cloudflare_account_id\x18\v \x01(\tR\x13cloudflareAccountId\x12d\n" +
	"\x1acredential_delegation_mode\x18\f \x01(\x0e2&.warehouse.v1.CredentialDelegationModeR\x18credentialDelegationMode\x12H\n" +
	"\x10storage_provider\x18\r \x01(\x0e2\x1d.warehouse.v1.StorageProviderR\x0fstorageProvider\x12&\n" +
	"\x0fassume_role_arn\x18\x0e \x01(\tR\rassumeRoleArn\x12!\n" +
	"\fstorage_mode\x18\x0f \x01(\tR\vstorageModeB\x14\n" +
	"\x12_path_style_accessB\x0e\n" +
	"\f_sts_enabledB\x19\n" +
	"\x17_remote_signing_enabled\"P\n" +
	"\x17CreateWarehouseResponse\x125\n" +
	"\twarehouse\x18\x01 \x01(\v2\x17.warehouse.v1.WarehouseR\twarehouse\"/\n" +
	"\tWarehouse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name*\xc1\x01\n" +
	"\x18CredentialDelegationMode\x12*\n" +
	"&CREDENTIAL_DELEGATION_MODE_UNSPECIFIED\x10\x00\x12%\n" +
	"!CREDENTIAL_DELEGATION_MODE_VENDED\x10\x01\x12-\n" +
	")CREDENTIAL_DELEGATION_MODE_REMOTE_SIGNING\x10\x02\x12#\n" +
	"\x1fCREDENTIAL_DELEGATION_MODE_NONE\x10\x03*\x91\x01\n" +
	"\x0fStorageProvider\x12 \n" +
	"\x1cSTORAGE_PROVIDER_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STORAGE_PROVIDER_AWS\x10\x01\x12\"\n" +
	"\x1eSTORAGE_PROVIDER_CLOUDFLARE_R2\x10\x02\x12\x1e\n" +
	"\x1aSTORAGE_PROVIDER_S3_COMPAT\x10\x032\xd3\x01\n" +
	"\x10WarehouseService\x12]\n" +
	"\x0eListWarehouses\x12#.warehouse.v1.ListWarehousesRequest\x1a$.warehouse.v1.ListWarehousesResponse\"\x00\x12`\n" +
	"\x0fCreateWarehouse\x12$.warehouse.v1.CreateWarehouseRequest\x1a%.warehouse.v1.CreateWarehouseResponse\"\x00BBZ@github.com/fairtier/workspace-api/proto/warehouse/v1;warehousev1b\x06proto3"

var (
	file_warehouse_proto_rawDescOnce sync.Once
	file_warehouse_proto_rawDescData []byte
)

func file_warehouse_proto_rawDescGZIP() []byte {
	file_warehouse_proto_rawDescOnce.Do(func() {
		file_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warehouse_proto_rawDesc), len(file_warehouse_proto_rawDesc)))
	})
	return file_warehouse_proto_rawDescData
}

var file_warehouse_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_warehouse_proto_goTypes = []any{
	(CredentialDelegationMode)(0),   // 0: warehouse.v1.CredentialDelegationMode
	(StorageProvider)(0),            // 1: warehouse.v1.StorageProvider
	(*ListWarehousesRequest)(nil),   // 2: warehouse.v1.ListWarehousesRequest
	(*ListWarehousesResponse)(nil),  // 3: warehouse.v1.ListWarehousesResponse
	(*CreateWarehouseRequest)(nil),  // 4: warehouse.v1.CreateWarehouseRequest
	(*S3Config)(nil),                // 5: warehouse.v1.S3Config
	(*CreateWarehouseResponse)(nil), // 6: warehouse.v1.CreateWarehouseResponse
	(*Warehouse)(nil),               // 7: warehouse.v1.Warehouse
}
var file_warehouse_proto_depIdxs = []int32{
	7, // 0: warehouse.v1.ListWarehousesResponse.warehouses:type_name -> warehouse.v1.Warehouse
	5, // 1: warehouse.v1.CreateWarehouseRequest.s3:type_name -> warehouse.v1.S3Config
	0, // 2: warehouse.v1.S3Config.credential_delegation_mode:type_name -> warehouse.v1.CredentialDelegationMode
	1, // 3: warehouse.v1.S3Config.storage_provider:type_name -> warehouse.v1.StorageProvider
	7, // 4: warehouse.v1.CreateWarehouseResponse.warehouse:type_name -> warehouse.v1.Warehouse
	2, // 5: warehouse.v1.WarehouseService.ListWarehouses:input_type -> warehouse.v1.ListWarehousesRequest
	4, // 6: warehouse.v1.WarehouseService.CreateWarehouse:input_type -> warehouse.v1.CreateWarehouseRequest
	3, // 7: warehouse.v1.WarehouseService.ListWarehouses:output_type -> warehouse.v1.ListWarehousesResponse
	6, // 8: warehouse.v1.WarehouseService.CreateWarehouse:output_type -> warehouse.v1.CreateWarehouseResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_warehouse_proto_init() }
func file_warehouse_proto_init() {
	if File_warehouse_proto != nil {
		return
	}
	file_warehouse_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warehouse_proto_rawDesc), len(file_warehouse_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warehouse_proto_goTypes,
		DependencyIndexes: file_warehouse_proto_depIdxs,
		EnumInfos:         file_warehouse_proto_enumTypes,
		MessageInfos:      file_warehouse_proto_msgTypes,
	}.Build()
	File_warehouse_proto = out.File
	file_warehouse_proto_goTypes = nil
	file_warehouse_proto_depIdxs = nil
}
