// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: demo.proto

package demov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fairtier/workspace-api/proto/demo/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DemoServiceName is the fully-qualified name of the DemoService service.
	DemoServiceName = "demo.v1.DemoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DemoServiceGetDemoStatusProcedure is the fully-qualified name of the DemoService's GetDemoStatus
	// RPC.
	DemoServiceGetDemoStatusProcedure = "/demo.v1.DemoService/GetDemoStatus"
	// DemoServiceLoadDemoProjectProcedure is the fully-qualified name of the DemoService's
	// LoadDemoProject RPC.
	DemoServiceLoadDemoProjectProcedure = "/demo.v1.DemoService/LoadDemoProject"
	// DemoServiceRemoveDemoProjectProcedure is the fully-qualified name of the DemoService's
	// RemoveDemoProject RPC.
	DemoServiceRemoveDemoProjectProcedure = "/demo.v1.DemoService/RemoveDemoProject"
)

// DemoServiceClient is a client for the demo.v1.DemoService service.
type DemoServiceClient interface {
	// GetDemoStatus reports whether the demo can be loaded here and whether it
	// already has been (drives the Console "Load / Remove demo project" button).
	GetDemoStatus(context.Context, *connect.Request[v1.GetDemoStatusRequest]) (*connect.Response[v1.GetDemoStatusResponse], error)
	// LoadDemoProject seeds the demo into the caller's workspace. Idempotent by
	// rejection: a second call while a demo is already loaded returns
	// ALREADY_EXISTS. On partial failure it unwinds what it created so the load
	// can be retried from a clean slate.
	LoadDemoProject(context.Context, *connect.Request[v1.LoadDemoProjectRequest]) (*connect.Response[v1.LoadDemoProjectResponse], error)
	// RemoveDemoProject deletes the two demo pipelines (their files pruned from
	// the pipelines repo by the mirror), the demo transformation, and the seed
	// commits' files from the transformations/rill repos — keyed strictly by
	// what the load recorded, so mixed-in customer work is left intact.
	//
	// Warehouse data (the lake.nyc_taxi / staging / marts tables) is NOT dropped
	// here: dropping Iceberg namespaces needs a validated DDL path (the same
	// constraint the manual customer-erasure procedure runs into).
	// removed_warehouse stays false and the tables are left for a manual sweep.
	RemoveDemoProject(context.Context, *connect.Request[v1.RemoveDemoProjectRequest]) (*connect.Response[v1.RemoveDemoProjectResponse], error)
}

// NewDemoServiceClient constructs a client for the demo.v1.DemoService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDemoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DemoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	demoServiceMethods := v1.File_demo_proto.Services().ByName("DemoService").Methods()
	return &demoServiceClient{
		getDemoStatus: connect.NewClient[v1.GetDemoStatusRequest, v1.GetDemoStatusResponse](
			httpClient,
			baseURL+DemoServiceGetDemoStatusProcedure,
			connect.WithSchema(demoServiceMethods.ByName("GetDemoStatus")),
			connect.WithClientOptions(opts...),
		),
		loadDemoProject: connect.NewClient[v1.LoadDemoProjectRequest, v1.LoadDemoProjectResponse](
			httpClient,
			baseURL+DemoServiceLoadDemoProjectProcedure,
			connect.WithSchema(demoServiceMethods.ByName("LoadDemoProject")),
			connect.WithClientOptions(opts...),
		),
		removeDemoProject: connect.NewClient[v1.RemoveDemoProjectRequest, v1.RemoveDemoProjectResponse](
			httpClient,
			baseURL+DemoServiceRemoveDemoProjectProcedure,
			connect.WithSchema(demoServiceMethods.ByName("RemoveDemoProject")),
			connect.WithClientOptions(opts...),
		),
	}
}

// demoServiceClient implements DemoServiceClient.
type demoServiceClient struct {
	getDemoStatus     *connect.Client[v1.GetDemoStatusRequest, v1.GetDemoStatusResponse]
	loadDemoProject   *connect.Client[v1.LoadDemoProjectRequest, v1.LoadDemoProjectResponse]
	removeDemoProject *connect.Client[v1.RemoveDemoProjectRequest, v1.RemoveDemoProjectResponse]
}

// GetDemoStatus calls demo.v1.DemoService.GetDemoStatus.
func (c *demoServiceClient) GetDemoStatus(ctx context.Context, req *connect.Request[v1.GetDemoStatusRequest]) (*connect.Response[v1.GetDemoStatusResponse], error) {
	return c.getDemoStatus.CallUnary(ctx, req)
}

// LoadDemoProject calls demo.v1.DemoService.LoadDemoProject.
func (c *demoServiceClient) LoadDemoProject(ctx context.Context, req *connect.Request[v1.LoadDemoProjectRequest]) (*connect.Response[v1.LoadDemoProjectResponse], error) {
	return c.loadDemoProject.CallUnary(ctx, req)
}

// RemoveDemoProject calls demo.v1.DemoService.RemoveDemoProject.
func (c *demoServiceClient) RemoveDemoProject(ctx context.Context, req *connect.Request[v1.RemoveDemoProjectRequest]) (*connect.Response[v1.RemoveDemoProjectResponse], error) {
	return c.removeDemoProject.CallUnary(ctx, req)
}

// DemoServiceHandler is an implementation of the demo.v1.DemoService service.
type DemoServiceHandler interface {
	// GetDemoStatus reports whether the demo can be loaded here and whether it
	// already has been (drives the Console "Load / Remove demo project" button).
	GetDemoStatus(context.Context, *connect.Request[v1.GetDemoStatusRequest]) (*connect.Response[v1.GetDemoStatusResponse], error)
	// LoadDemoProject seeds the demo into the caller's workspace. Idempotent by
	// rejection: a second call while a demo is already loaded returns
	// ALREADY_EXISTS. On partial failure it unwinds what it created so the load
	// can be retried from a clean slate.
	LoadDemoProject(context.Context, *connect.Request[v1.LoadDemoProjectRequest]) (*connect.Response[v1.LoadDemoProjectResponse], error)
	// RemoveDemoProject deletes the two demo pipelines (their files pruned from
	// the pipelines repo by the mirror), the demo transformation, and the seed
	// commits' files from the transformations/rill repos — keyed strictly by
	// what the load recorded, so mixed-in customer work is left intact.
	//
	// Warehouse data (the lake.nyc_taxi / staging / marts tables) is NOT dropped
	// here: dropping Iceberg namespaces needs a validated DDL path (the same
	// constraint the manual customer-erasure procedure runs into).
	// removed_warehouse stays false and the tables are left for a manual sweep.
	RemoveDemoProject(context.Context, *connect.Request[v1.RemoveDemoProjectRequest]) (*connect.Response[v1.RemoveDemoProjectResponse], error)
}

// NewDemoServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDemoServiceHandler(svc DemoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	demoServiceMethods := v1.File_demo_proto.Services().ByName("DemoService").Methods()
	demoServiceGetDemoStatusHandler := connect.NewUnaryHandler(
		DemoServiceGetDemoStatusProcedure,
		svc.GetDemoStatus,
		connect.WithSchema(demoServiceMethods.ByName("GetDemoStatus")),
		connect.WithHandlerOptions(opts...),
	)
	demoServiceLoadDemoProjectHandler := connect.NewUnaryHandler(
		DemoServiceLoadDemoProjectProcedure,
		svc.LoadDemoProject,
		connect.WithSchema(demoServiceMethods.ByName("LoadDemoProject")),
		connect.WithHandlerOptions(opts...),
	)
	demoServiceRemoveDemoProjectHandler := connect.NewUnaryHandler(
		DemoServiceRemoveDemoProjectProcedure,
		svc.RemoveDemoProject,
		connect.WithSchema(demoServiceMethods.ByName("RemoveDemoProject")),
		connect.WithHandlerOptions(opts...),
	)
	return "/demo.v1.DemoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DemoServiceGetDemoStatusProcedure:
			demoServiceGetDemoStatusHandler.ServeHTTP(w, r)
		case DemoServiceLoadDemoProjectProcedure:
			demoServiceLoadDemoProjectHandler.ServeHTTP(w, r)
		case DemoServiceRemoveDemoProjectProcedure:
			demoServiceRemoveDemoProjectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDemoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDemoServiceHandler struct{}

func (UnimplementedDemoServiceHandler) GetDemoStatus(context.Context, *connect.Request[v1.GetDemoStatusRequest]) (*connect.Response[v1.GetDemoStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("demo.v1.DemoService.GetDemoStatus is not implemented"))
}

func (UnimplementedDemoServiceHandler) LoadDemoProject(context.Context, *connect.Request[v1.LoadDemoProjectRequest]) (*connect.Response[v1.LoadDemoProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("demo.v1.DemoService.LoadDemoProject is not implemented"))
}

func (UnimplementedDemoServiceHandler) RemoveDemoProject(context.Context, *connect.Request[v1.RemoveDemoProjectRequest]) (*connect.Response[v1.RemoveDemoProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("demo.v1.DemoService.RemoveDemoProject is not implemented"))
}
