// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pipeline_assist.proto

package pipelineassistv1

import (
	v1 "github.com/fairtier/workspace-api/proto/pipeline/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DraftPipelineRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Natural-language description of the data the user wants to ingest, e.g.
	// "Load my Stripe charges and customers daily into a stripe dataset".
	Prompt        string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftPipelineRequest) Reset() {
	*x = DraftPipelineRequest{}
	mi := &file_pipeline_assist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftPipelineRequest) ProtoMessage() {}

func (x *DraftPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_assist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftPipelineRequest.ProtoReflect.Descriptor instead.
func (*DraftPipelineRequest) Descriptor() ([]byte, []int) {
	return file_pipeline_assist_proto_rawDescGZIP(), []int{0}
}

func (x *DraftPipelineRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type DraftPipelineResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The drafted pipeline request, pre-filled and validated. Its
	// source_credentials field is always empty — the model never drafts secrets.
	Draft *v1.CreatePipelineRequest `protobuf:"bytes,1,opt,name=draft,proto3" json:"draft,omitempty"`
	// Short human-readable explanation of the draft and any assumptions made,
	// surfaced to the user above the pre-filled form.
	Notes         string `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftPipelineResponse) Reset() {
	*x = DraftPipelineResponse{}
	mi := &file_pipeline_assist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftPipelineResponse) ProtoMessage() {}

func (x *DraftPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_assist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftPipelineResponse.ProtoReflect.Descriptor instead.
func (*DraftPipelineResponse) Descriptor() ([]byte, []int) {
	return file_pipeline_assist_proto_rawDescGZIP(), []int{1}
}

func (x *DraftPipelineResponse) GetDraft() *v1.CreatePipelineRequest {
	if x != nil {
		return x.Draft
	}
	return nil
}

func (x *DraftPipelineResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

var File_pipeline_assist_proto protoreflect.FileDescriptor

const file_pipeline_assist_proto_rawDesc = "" +
	"\n" +
	"\x15pipeline_assist.proto\x12\x12pipeline_assist.v1\x1a\x0epipeline.proto\".\n" +
	"\x14DraftPipelineRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"g\n" +
	"\x15DraftPipelineResponse\x128\n" +
	"\x05draft\x18\x01 \x01(\v2\".pipeline.v1.CreatePipelineRequestR\x05draft\x12\x14\n" +
	"\x05notes\x18\x02 \x01(\tR\x05notes2\x7f\n" +
	"\x15PipelineAssistService\x12f\n" +
	"\rDraftPipeline\x12(.pipeline_assist.v1.DraftPipelineRequest\x1a).pipeline_assist.v1.DraftPipelineResponse\"\x00BMZKgithub.com/fairtier/workspace-api/proto/pipeline_assist/v1;pipelineassistv1b\x06proto3"

var (
	file_pipeline_assist_proto_rawDescOnce sync.Once
	file_pipeline_assist_proto_rawDescData []byte
)

func file_pipeline_assist_proto_rawDescGZIP() []byte {
	file_pipeline_assist_proto_rawDescOnce.Do(func() {
		file_pipeline_assist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pipeline_assist_proto_rawDesc), len(file_pipeline_assist_proto_rawDesc)))
	})
	return file_pipeline_assist_proto_rawDescData
}

var file_pipeline_assist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pipeline_assist_proto_goTypes = []any{
	(*DraftPipelineRequest)(nil),     // 0: pipeline_assist.v1.DraftPipelineRequest
	(*DraftPipelineResponse)(nil),    // 1: pipeline_assist.v1.DraftPipelineResponse
	(*v1.CreatePipelineRequest)(nil), // 2: pipeline.v1.CreatePipelineRequest
}
var file_pipeline_assist_proto_depIdxs = []int32{
	2, // 0: pipeline_assist.v1.DraftPipelineResponse.draft:type_name -> pipeline.v1.CreatePipelineRequest
	0, // 1: pipeline_assist.v1.PipelineAssistService.DraftPipeline:input_type -> pipeline_assist.v1.DraftPipelineRequest
	1, // 2: pipeline_assist.v1.PipelineAssistService.DraftPipeline:output_type -> pipeline_assist.v1.DraftPipelineResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pipeline_assist_proto_init() }
func file_pipeline_assist_proto_init() {
	if File_pipeline_assist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pipeline_assist_proto_rawDesc), len(file_pipeline_assist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pipeline_assist_proto_goTypes,
		DependencyIndexes: file_pipeline_assist_proto_depIdxs,
		MessageInfos:      file_pipeline_assist_proto_msgTypes,
	}.Build()
	File_pipeline_assist_proto = out.File
	file_pipeline_assist_proto_goTypes = nil
	file_pipeline_assist_proto_depIdxs = nil
}
