// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: boxrepo.proto

package boxrepov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fairtier/workspace-api/proto/boxrepo/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BoxRepoServiceName is the fully-qualified name of the BoxRepoService service.
	BoxRepoServiceName = "boxrepo.v1.BoxRepoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BoxRepoServiceListFilesProcedure is the fully-qualified name of the BoxRepoService's ListFiles
	// RPC.
	BoxRepoServiceListFilesProcedure = "/boxrepo.v1.BoxRepoService/ListFiles"
	// BoxRepoServiceGetFileProcedure is the fully-qualified name of the BoxRepoService's GetFile RPC.
	BoxRepoServiceGetFileProcedure = "/boxrepo.v1.BoxRepoService/GetFile"
	// BoxRepoServicePutFileProcedure is the fully-qualified name of the BoxRepoService's PutFile RPC.
	BoxRepoServicePutFileProcedure = "/boxrepo.v1.BoxRepoService/PutFile"
	// BoxRepoServiceListFileHistoryProcedure is the fully-qualified name of the BoxRepoService's
	// ListFileHistory RPC.
	BoxRepoServiceListFileHistoryProcedure = "/boxrepo.v1.BoxRepoService/ListFileHistory"
	// BoxRepoServiceGetFileAtRefProcedure is the fully-qualified name of the BoxRepoService's
	// GetFileAtRef RPC.
	BoxRepoServiceGetFileAtRefProcedure = "/boxrepo.v1.BoxRepoService/GetFileAtRef"
	// BoxRepoServiceSetPushMirrorProcedure is the fully-qualified name of the BoxRepoService's
	// SetPushMirror RPC.
	BoxRepoServiceSetPushMirrorProcedure = "/boxrepo.v1.BoxRepoService/SetPushMirror"
	// BoxRepoServiceGetPushMirrorProcedure is the fully-qualified name of the BoxRepoService's
	// GetPushMirror RPC.
	BoxRepoServiceGetPushMirrorProcedure = "/boxrepo.v1.BoxRepoService/GetPushMirror"
	// BoxRepoServiceDeletePushMirrorProcedure is the fully-qualified name of the BoxRepoService's
	// DeletePushMirror RPC.
	BoxRepoServiceDeletePushMirrorProcedure = "/boxrepo.v1.BoxRepoService/DeletePushMirror"
	// BoxRepoServiceSyncPushMirrorProcedure is the fully-qualified name of the BoxRepoService's
	// SyncPushMirror RPC.
	BoxRepoServiceSyncPushMirrorProcedure = "/boxrepo.v1.BoxRepoService/SyncPushMirror"
)

// BoxRepoServiceClient is a client for the boxrepo.v1.BoxRepoService service.
type BoxRepoServiceClient interface {
	// ListFiles returns the file tree of a box repo.
	ListFiles(context.Context, *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error)
	// GetFile returns one file's content and its blob sha (used as the
	// optimistic-concurrency token for PutFile).
	GetFile(context.Context, *connect.Request[v1.GetFileRequest]) (*connect.Response[v1.GetFileResponse], error)
	// PutFile creates or updates one file as a commit on the default branch.
	// sha must be the blob sha from GetFile when updating (empty = create);
	// a mismatch returns ABORTED ("changed outside the Console").
	PutFile(context.Context, *connect.Request[v1.PutFileRequest]) (*connect.Response[v1.PutFileResponse], error)
	// ListFileHistory returns the newest-first commit history of one file —
	// the Console's "version history" (follows the current path only; history
	// from before a rename stays with the old path).
	ListFileHistory(context.Context, *connect.Request[v1.ListFileHistoryRequest]) (*connect.Response[v1.ListFileHistoryResponse], error)
	// GetFileAtRef returns one file's content as of a commit sha, for version
	// preview/restore. Restoring = PutFile of this content guarded by the
	// CURRENT blob sha — a plain forward commit, never a git revert.
	GetFileAtRef(context.Context, *connect.Request[v1.GetFileAtRefRequest]) (*connect.Response[v1.GetFileAtRefResponse], error)
	// SetPushMirror configures (or replaces) the box repo's push mirror to the
	// customer's own git hosting (GitHub/GitLab/...). The remote token is
	// passed through to the box's Gitea, which stores and uses it — it is
	// never persisted centrally. Mirrors push on every commit plus a periodic
	// interval. Allowed repos: rill, transformations, pipelines.
	SetPushMirror(context.Context, *connect.Request[v1.SetPushMirrorRequest]) (*connect.Response[v1.SetPushMirrorResponse], error)
	// GetPushMirror returns the repo's mirror status (credential-stripped).
	GetPushMirror(context.Context, *connect.Request[v1.GetPushMirrorRequest]) (*connect.Response[v1.GetPushMirrorResponse], error)
	// DeletePushMirror removes the repo's push mirror (and the stored remote
	// credential with it).
	DeletePushMirror(context.Context, *connect.Request[v1.DeletePushMirrorRequest]) (*connect.Response[v1.DeletePushMirrorResponse], error)
	// SyncPushMirror triggers an immediate push to the mirror remote.
	SyncPushMirror(context.Context, *connect.Request[v1.SyncPushMirrorRequest]) (*connect.Response[v1.SyncPushMirrorResponse], error)
}

// NewBoxRepoServiceClient constructs a client for the boxrepo.v1.BoxRepoService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBoxRepoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BoxRepoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	boxRepoServiceMethods := v1.File_boxrepo_proto.Services().ByName("BoxRepoService").Methods()
	return &boxRepoServiceClient{
		listFiles: connect.NewClient[v1.ListFilesRequest, v1.ListFilesResponse](
			httpClient,
			baseURL+BoxRepoServiceListFilesProcedure,
			connect.WithSchema(boxRepoServiceMethods.ByName("ListFiles")),
			connect.WithClientOptions(opts...),
		),
		getFile: connect.NewClient[v1.GetFileRequest, v1.GetFileResponse](
			httpClient,
			baseURL+BoxRepoServiceGetFileProcedure,
			connect.WithSchema(boxRepoServiceMethods.ByName("GetFile")),
			connect.WithClientOptions(opts...),
		),
		putFile: connect.NewClient[v1.PutFileRequest, v1.PutFileResponse](
			httpClient,
			baseURL+BoxRepoServicePutFileProcedure,
			connect.WithSchema(boxRepoServiceMethods.ByName("PutFile")),
			connect.WithClientOptions(opts...),
		),
		listFileHistory: connect.NewClient[v1.ListFileHistoryRequest, v1.ListFileHistoryResponse](
			httpClient,
			baseURL+BoxRepoServiceListFileHistoryProcedure,
			connect.WithSchema(boxRepoServiceMethods.ByName("ListFileHistory")),
			connect.WithClientOptions(opts...),
		),
		getFileAtRef: connect.NewClient[v1.GetFileAtRefRequest, v1.GetFileAtRefResponse](
			httpClient,
			baseURL+BoxRepoServiceGetFileAtRefProcedure,
			connect.WithSchema(boxRepoServiceMethods.ByName("GetFileAtRef")),
			connect.WithClientOptions(opts...),
		),
		setPushMirror: connect.NewClient[v1.SetPushMirrorRequest, v1.SetPushMirrorResponse](
			httpClient,
			baseURL+BoxRepoServiceSetPushMirrorProcedure,
			connect.WithSchema(boxRepoServiceMethods.ByName("SetPushMirror")),
			connect.WithClientOptions(opts...),
		),
		getPushMirror: connect.NewClient[v1.GetPushMirrorRequest, v1.GetPushMirrorResponse](
			httpClient,
			baseURL+BoxRepoServiceGetPushMirrorProcedure,
			connect.WithSchema(boxRepoServiceMethods.ByName("GetPushMirror")),
			connect.WithClientOptions(opts...),
		),
		deletePushMirror: connect.NewClient[v1.DeletePushMirrorRequest, v1.DeletePushMirrorResponse](
			httpClient,
			baseURL+BoxRepoServiceDeletePushMirrorProcedure,
			connect.WithSchema(boxRepoServiceMethods.ByName("DeletePushMirror")),
			connect.WithClientOptions(opts...),
		),
		syncPushMirror: connect.NewClient[v1.SyncPushMirrorRequest, v1.SyncPushMirrorResponse](
			httpClient,
			baseURL+BoxRepoServiceSyncPushMirrorProcedure,
			connect.WithSchema(boxRepoServiceMethods.ByName("SyncPushMirror")),
			connect.WithClientOptions(opts...),
		),
	}
}

// boxRepoServiceClient implements BoxRepoServiceClient.
type boxRepoServiceClient struct {
	listFiles        *connect.Client[v1.ListFilesRequest, v1.ListFilesResponse]
	getFile          *connect.Client[v1.GetFileRequest, v1.GetFileResponse]
	putFile          *connect.Client[v1.PutFileRequest, v1.PutFileResponse]
	listFileHistory  *connect.Client[v1.ListFileHistoryRequest, v1.ListFileHistoryResponse]
	getFileAtRef     *connect.Client[v1.GetFileAtRefRequest, v1.GetFileAtRefResponse]
	setPushMirror    *connect.Client[v1.SetPushMirrorRequest, v1.SetPushMirrorResponse]
	getPushMirror    *connect.Client[v1.GetPushMirrorRequest, v1.GetPushMirrorResponse]
	deletePushMirror *connect.Client[v1.DeletePushMirrorRequest, v1.DeletePushMirrorResponse]
	syncPushMirror   *connect.Client[v1.SyncPushMirrorRequest, v1.SyncPushMirrorResponse]
}

// ListFiles calls boxrepo.v1.BoxRepoService.ListFiles.
func (c *boxRepoServiceClient) ListFiles(ctx context.Context, req *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error) {
	return c.listFiles.CallUnary(ctx, req)
}

// GetFile calls boxrepo.v1.BoxRepoService.GetFile.
func (c *boxRepoServiceClient) GetFile(ctx context.Context, req *connect.Request[v1.GetFileRequest]) (*connect.Response[v1.GetFileResponse], error) {
	return c.getFile.CallUnary(ctx, req)
}

// PutFile calls boxrepo.v1.BoxRepoService.PutFile.
func (c *boxRepoServiceClient) PutFile(ctx context.Context, req *connect.Request[v1.PutFileRequest]) (*connect.Response[v1.PutFileResponse], error) {
	return c.putFile.CallUnary(ctx, req)
}

// ListFileHistory calls boxrepo.v1.BoxRepoService.ListFileHistory.
func (c *boxRepoServiceClient) ListFileHistory(ctx context.Context, req *connect.Request[v1.ListFileHistoryRequest]) (*connect.Response[v1.ListFileHistoryResponse], error) {
	return c.listFileHistory.CallUnary(ctx, req)
}

// GetFileAtRef calls boxrepo.v1.BoxRepoService.GetFileAtRef.
func (c *boxRepoServiceClient) GetFileAtRef(ctx context.Context, req *connect.Request[v1.GetFileAtRefRequest]) (*connect.Response[v1.GetFileAtRefResponse], error) {
	return c.getFileAtRef.CallUnary(ctx, req)
}

// SetPushMirror calls boxrepo.v1.BoxRepoService.SetPushMirror.
func (c *boxRepoServiceClient) SetPushMirror(ctx context.Context, req *connect.Request[v1.SetPushMirrorRequest]) (*connect.Response[v1.SetPushMirrorResponse], error) {
	return c.setPushMirror.CallUnary(ctx, req)
}

// GetPushMirror calls boxrepo.v1.BoxRepoService.GetPushMirror.
func (c *boxRepoServiceClient) GetPushMirror(ctx context.Context, req *connect.Request[v1.GetPushMirrorRequest]) (*connect.Response[v1.GetPushMirrorResponse], error) {
	return c.getPushMirror.CallUnary(ctx, req)
}

// DeletePushMirror calls boxrepo.v1.BoxRepoService.DeletePushMirror.
func (c *boxRepoServiceClient) DeletePushMirror(ctx context.Context, req *connect.Request[v1.DeletePushMirrorRequest]) (*connect.Response[v1.DeletePushMirrorResponse], error) {
	return c.deletePushMirror.CallUnary(ctx, req)
}

// SyncPushMirror calls boxrepo.v1.BoxRepoService.SyncPushMirror.
func (c *boxRepoServiceClient) SyncPushMirror(ctx context.Context, req *connect.Request[v1.SyncPushMirrorRequest]) (*connect.Response[v1.SyncPushMirrorResponse], error) {
	return c.syncPushMirror.CallUnary(ctx, req)
}

// BoxRepoServiceHandler is an implementation of the boxrepo.v1.BoxRepoService service.
type BoxRepoServiceHandler interface {
	// ListFiles returns the file tree of a box repo.
	ListFiles(context.Context, *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error)
	// GetFile returns one file's content and its blob sha (used as the
	// optimistic-concurrency token for PutFile).
	GetFile(context.Context, *connect.Request[v1.GetFileRequest]) (*connect.Response[v1.GetFileResponse], error)
	// PutFile creates or updates one file as a commit on the default branch.
	// sha must be the blob sha from GetFile when updating (empty = create);
	// a mismatch returns ABORTED ("changed outside the Console").
	PutFile(context.Context, *connect.Request[v1.PutFileRequest]) (*connect.Response[v1.PutFileResponse], error)
	// ListFileHistory returns the newest-first commit history of one file —
	// the Console's "version history" (follows the current path only; history
	// from before a rename stays with the old path).
	ListFileHistory(context.Context, *connect.Request[v1.ListFileHistoryRequest]) (*connect.Response[v1.ListFileHistoryResponse], error)
	// GetFileAtRef returns one file's content as of a commit sha, for version
	// preview/restore. Restoring = PutFile of this content guarded by the
	// CURRENT blob sha — a plain forward commit, never a git revert.
	GetFileAtRef(context.Context, *connect.Request[v1.GetFileAtRefRequest]) (*connect.Response[v1.GetFileAtRefResponse], error)
	// SetPushMirror configures (or replaces) the box repo's push mirror to the
	// customer's own git hosting (GitHub/GitLab/...). The remote token is
	// passed through to the box's Gitea, which stores and uses it — it is
	// never persisted centrally. Mirrors push on every commit plus a periodic
	// interval. Allowed repos: rill, transformations, pipelines.
	SetPushMirror(context.Context, *connect.Request[v1.SetPushMirrorRequest]) (*connect.Response[v1.SetPushMirrorResponse], error)
	// GetPushMirror returns the repo's mirror status (credential-stripped).
	GetPushMirror(context.Context, *connect.Request[v1.GetPushMirrorRequest]) (*connect.Response[v1.GetPushMirrorResponse], error)
	// DeletePushMirror removes the repo's push mirror (and the stored remote
	// credential with it).
	DeletePushMirror(context.Context, *connect.Request[v1.DeletePushMirrorRequest]) (*connect.Response[v1.DeletePushMirrorResponse], error)
	// SyncPushMirror triggers an immediate push to the mirror remote.
	SyncPushMirror(context.Context, *connect.Request[v1.SyncPushMirrorRequest]) (*connect.Response[v1.SyncPushMirrorResponse], error)
}

// NewBoxRepoServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBoxRepoServiceHandler(svc BoxRepoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	boxRepoServiceMethods := v1.File_boxrepo_proto.Services().ByName("BoxRepoService").Methods()
	boxRepoServiceListFilesHandler := connect.NewUnaryHandler(
		BoxRepoServiceListFilesProcedure,
		svc.ListFiles,
		connect.WithSchema(boxRepoServiceMethods.ByName("ListFiles")),
		connect.WithHandlerOptions(opts...),
	)
	boxRepoServiceGetFileHandler := connect.NewUnaryHandler(
		BoxRepoServiceGetFileProcedure,
		svc.GetFile,
		connect.WithSchema(boxRepoServiceMethods.ByName("GetFile")),
		connect.WithHandlerOptions(opts...),
	)
	boxRepoServicePutFileHandler := connect.NewUnaryHandler(
		BoxRepoServicePutFileProcedure,
		svc.PutFile,
		connect.WithSchema(boxRepoServiceMethods.ByName("PutFile")),
		connect.WithHandlerOptions(opts...),
	)
	boxRepoServiceListFileHistoryHandler := connect.NewUnaryHandler(
		BoxRepoServiceListFileHistoryProcedure,
		svc.ListFileHistory,
		connect.WithSchema(boxRepoServiceMethods.ByName("ListFileHistory")),
		connect.WithHandlerOptions(opts...),
	)
	boxRepoServiceGetFileAtRefHandler := connect.NewUnaryHandler(
		BoxRepoServiceGetFileAtRefProcedure,
		svc.GetFileAtRef,
		connect.WithSchema(boxRepoServiceMethods.ByName("GetFileAtRef")),
		connect.WithHandlerOptions(opts...),
	)
	boxRepoServiceSetPushMirrorHandler := connect.NewUnaryHandler(
		BoxRepoServiceSetPushMirrorProcedure,
		svc.SetPushMirror,
		connect.WithSchema(boxRepoServiceMethods.ByName("SetPushMirror")),
		connect.WithHandlerOptions(opts...),
	)
	boxRepoServiceGetPushMirrorHandler := connect.NewUnaryHandler(
		BoxRepoServiceGetPushMirrorProcedure,
		svc.GetPushMirror,
		connect.WithSchema(boxRepoServiceMethods.ByName("GetPushMirror")),
		connect.WithHandlerOptions(opts...),
	)
	boxRepoServiceDeletePushMirrorHandler := connect.NewUnaryHandler(
		BoxRepoServiceDeletePushMirrorProcedure,
		svc.DeletePushMirror,
		connect.WithSchema(boxRepoServiceMethods.ByName("DeletePushMirror")),
		connect.WithHandlerOptions(opts...),
	)
	boxRepoServiceSyncPushMirrorHandler := connect.NewUnaryHandler(
		BoxRepoServiceSyncPushMirrorProcedure,
		svc.SyncPushMirror,
		connect.WithSchema(boxRepoServiceMethods.ByName("SyncPushMirror")),
		connect.WithHandlerOptions(opts...),
	)
	return "/boxrepo.v1.BoxRepoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BoxRepoServiceListFilesProcedure:
			boxRepoServiceListFilesHandler.ServeHTTP(w, r)
		case BoxRepoServiceGetFileProcedure:
			boxRepoServiceGetFileHandler.ServeHTTP(w, r)
		case BoxRepoServicePutFileProcedure:
			boxRepoServicePutFileHandler.ServeHTTP(w, r)
		case BoxRepoServiceListFileHistoryProcedure:
			boxRepoServiceListFileHistoryHandler.ServeHTTP(w, r)
		case BoxRepoServiceGetFileAtRefProcedure:
			boxRepoServiceGetFileAtRefHandler.ServeHTTP(w, r)
		case BoxRepoServiceSetPushMirrorProcedure:
			boxRepoServiceSetPushMirrorHandler.ServeHTTP(w, r)
		case BoxRepoServiceGetPushMirrorProcedure:
			boxRepoServiceGetPushMirrorHandler.ServeHTTP(w, r)
		case BoxRepoServiceDeletePushMirrorProcedure:
			boxRepoServiceDeletePushMirrorHandler.ServeHTTP(w, r)
		case BoxRepoServiceSyncPushMirrorProcedure:
			boxRepoServiceSyncPushMirrorHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBoxRepoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBoxRepoServiceHandler struct{}

func (UnimplementedBoxRepoServiceHandler) ListFiles(context.Context, *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxrepo.v1.BoxRepoService.ListFiles is not implemented"))
}

func (UnimplementedBoxRepoServiceHandler) GetFile(context.Context, *connect.Request[v1.GetFileRequest]) (*connect.Response[v1.GetFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxrepo.v1.BoxRepoService.GetFile is not implemented"))
}

func (UnimplementedBoxRepoServiceHandler) PutFile(context.Context, *connect.Request[v1.PutFileRequest]) (*connect.Response[v1.PutFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxrepo.v1.BoxRepoService.PutFile is not implemented"))
}

func (UnimplementedBoxRepoServiceHandler) ListFileHistory(context.Context, *connect.Request[v1.ListFileHistoryRequest]) (*connect.Response[v1.ListFileHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxrepo.v1.BoxRepoService.ListFileHistory is not implemented"))
}

func (UnimplementedBoxRepoServiceHandler) GetFileAtRef(context.Context, *connect.Request[v1.GetFileAtRefRequest]) (*connect.Response[v1.GetFileAtRefResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxrepo.v1.BoxRepoService.GetFileAtRef is not implemented"))
}

func (UnimplementedBoxRepoServiceHandler) SetPushMirror(context.Context, *connect.Request[v1.SetPushMirrorRequest]) (*connect.Response[v1.SetPushMirrorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxrepo.v1.BoxRepoService.SetPushMirror is not implemented"))
}

func (UnimplementedBoxRepoServiceHandler) GetPushMirror(context.Context, *connect.Request[v1.GetPushMirrorRequest]) (*connect.Response[v1.GetPushMirrorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxrepo.v1.BoxRepoService.GetPushMirror is not implemented"))
}

func (UnimplementedBoxRepoServiceHandler) DeletePushMirror(context.Context, *connect.Request[v1.DeletePushMirrorRequest]) (*connect.Response[v1.DeletePushMirrorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxrepo.v1.BoxRepoService.DeletePushMirror is not implemented"))
}

func (UnimplementedBoxRepoServiceHandler) SyncPushMirror(context.Context, *connect.Request[v1.SyncPushMirrorRequest]) (*connect.Response[v1.SyncPushMirrorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("boxrepo.v1.BoxRepoService.SyncPushMirror is not implemented"))
}
