// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: oauthclient.proto

package oauthclientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOAuthClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider key; empty defaults to "google" (the only one supported today).
	Provider      string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthClientRequest) Reset() {
	*x = GetOAuthClientRequest{}
	mi := &file_oauthclient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthClientRequest) ProtoMessage() {}

func (x *GetOAuthClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauthclient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthClientRequest.ProtoReflect.Descriptor instead.
func (*GetOAuthClientRequest) Descriptor() ([]byte, []int) {
	return file_oauthclient_proto_rawDescGZIP(), []int{0}
}

func (x *GetOAuthClientRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type GetOAuthClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether a client pair is stored for this workspace.
	Configured bool `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	// The stored client id. Not a secret; shown so the customer can confirm which
	// app is connected. Empty when configured is false.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The exact redirect URI to register with the provider. Served rather than
	// constructed in the browser so it always matches what the callback runs on.
	// Empty when this deployment cannot run the consent flow.
	RedirectUri string `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	// Scopes the provider app must be allowed to request.
	RequiredScopes []string `protobuf:"bytes,4,rep,name=required_scopes,json=requiredScopes,proto3" json:"required_scopes,omitempty"`
	// Whether this deployment can run the consent round-trip at all. False on a
	// box that has no redirect URI of its own: the pair can still be stored
	// (pipelines mirrored from central need it to refresh) but new connections
	// must be made from the central Console.
	FlowAvailable bool `protobuf:"varint,5,opt,name=flow_available,json=flowAvailable,proto3" json:"flow_available,omitempty"`
	// RFC 3339 timestamp of the last save, empty when never saved.
	UpdatedAt string `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Subject of the user who last saved it, empty when never saved.
	UpdatedBy     string `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthClientResponse) Reset() {
	*x = GetOAuthClientResponse{}
	mi := &file_oauthclient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthClientResponse) ProtoMessage() {}

func (x *GetOAuthClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauthclient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthClientResponse.ProtoReflect.Descriptor instead.
func (*GetOAuthClientResponse) Descriptor() ([]byte, []int) {
	return file_oauthclient_proto_rawDescGZIP(), []int{1}
}

func (x *GetOAuthClientResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *GetOAuthClientResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetOAuthClientResponse) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *GetOAuthClientResponse) GetRequiredScopes() []string {
	if x != nil {
		return x.RequiredScopes
	}
	return nil
}

func (x *GetOAuthClientResponse) GetFlowAvailable() bool {
	if x != nil {
		return x.FlowAvailable
	}
	return false
}

func (x *GetOAuthClientResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetOAuthClientResponse) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type SetOAuthClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider key; empty defaults to "google".
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// OAuth client id from the customer's provider project.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// OAuth client secret. Write-only — never returned by GetOAuthClient.
	ClientSecret  string `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOAuthClientRequest) Reset() {
	*x = SetOAuthClientRequest{}
	mi := &file_oauthclient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOAuthClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOAuthClientRequest) ProtoMessage() {}

func (x *SetOAuthClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauthclient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOAuthClientRequest.ProtoReflect.Descriptor instead.
func (*SetOAuthClientRequest) Descriptor() ([]byte, []int) {
	return file_oauthclient_proto_rawDescGZIP(), []int{2}
}

func (x *SetOAuthClientRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SetOAuthClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SetOAuthClientRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type SetOAuthClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stored state after the save, same shape as GetOAuthClient.
	Client        *GetOAuthClientResponse `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOAuthClientResponse) Reset() {
	*x = SetOAuthClientResponse{}
	mi := &file_oauthclient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOAuthClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOAuthClientResponse) ProtoMessage() {}

func (x *SetOAuthClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauthclient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOAuthClientResponse.ProtoReflect.Descriptor instead.
func (*SetOAuthClientResponse) Descriptor() ([]byte, []int) {
	return file_oauthclient_proto_rawDescGZIP(), []int{3}
}

func (x *SetOAuthClientResponse) GetClient() *GetOAuthClientResponse {
	if x != nil {
		return x.Client
	}
	return nil
}

type DeleteOAuthClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider key; empty defaults to "google".
	Provider      string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOAuthClientRequest) Reset() {
	*x = DeleteOAuthClientRequest{}
	mi := &file_oauthclient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOAuthClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOAuthClientRequest) ProtoMessage() {}

func (x *DeleteOAuthClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauthclient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOAuthClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteOAuthClientRequest) Descriptor() ([]byte, []int) {
	return file_oauthclient_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteOAuthClientRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type DeleteOAuthClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOAuthClientResponse) Reset() {
	*x = DeleteOAuthClientResponse{}
	mi := &file_oauthclient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOAuthClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOAuthClientResponse) ProtoMessage() {}

func (x *DeleteOAuthClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauthclient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOAuthClientResponse.ProtoReflect.Descriptor instead.
func (*DeleteOAuthClientResponse) Descriptor() ([]byte, []int) {
	return file_oauthclient_proto_rawDescGZIP(), []int{5}
}

var File_oauthclient_proto protoreflect.FileDescriptor

const file_oauthclient_proto_rawDesc = "" +
	"\n" +
	"\x11oauthclient.proto\x12\x0eoauthclient.v1\"3\n" +
	"\x15GetOAuthClientRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"\x86\x02\n" +
	"\x16GetOAuthClientResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\x12'\n" +
	"\x0frequired_scopes\x18\x04 \x03(\tR\x0erequiredScopes\x12%\n" +
	"\x0eflow_available\x18\x05 \x01(\bR\rflowAvailable\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\tR\tupdatedBy\"u\n" +
	"\x15SetOAuthClientRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\"X\n" +
	"\x16SetOAuthClientResponse\x12>\n" +
	"\x06client\x18\x01 \x01(\v2&.oauthclient.v1.GetOAuthClientResponseR\x06client\"6\n" +
	"\x18DeleteOAuthClientRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"\x1b\n" +
	"\x19DeleteOAuthClientResponse2\xc6\x02\n" +
	"\x12OAuthClientService\x12a\n" +
	"\x0eGetOAuthClient\x12%.oauthclient.v1.GetOAuthClientRequest\x1a&.oauthclient.v1.GetOAuthClientResponse\"\x00\x12a\n" +
	"\x0eSetOAuthClient\x12%.oauthclient.v1.SetOAuthClientRequest\x1a&.oauthclient.v1.SetOAuthClientResponse\"\x00\x12j\n" +
	"\x11DeleteOAuthClient\x12(.oauthclient.v1.DeleteOAuthClientRequest\x1a).oauthclient.v1.DeleteOAuthClientResponse\"\x00BFZDgithub.com/fairtier/workspace-api/proto/oauthclient/v1;oauthclientv1b\x06proto3"

var (
	file_oauthclient_proto_rawDescOnce sync.Once
	file_oauthclient_proto_rawDescData []byte
)

func file_oauthclient_proto_rawDescGZIP() []byte {
	file_oauthclient_proto_rawDescOnce.Do(func() {
		file_oauthclient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oauthclient_proto_rawDesc), len(file_oauthclient_proto_rawDesc)))
	})
	return file_oauthclient_proto_rawDescData
}

var file_oauthclient_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_oauthclient_proto_goTypes = []any{
	(*GetOAuthClientRequest)(nil),     // 0: oauthclient.v1.GetOAuthClientRequest
	(*GetOAuthClientResponse)(nil),    // 1: oauthclient.v1.GetOAuthClientResponse
	(*SetOAuthClientRequest)(nil),     // 2: oauthclient.v1.SetOAuthClientRequest
	(*SetOAuthClientResponse)(nil),    // 3: oauthclient.v1.SetOAuthClientResponse
	(*DeleteOAuthClientRequest)(nil),  // 4: oauthclient.v1.DeleteOAuthClientRequest
	(*DeleteOAuthClientResponse)(nil), // 5: oauthclient.v1.DeleteOAuthClientResponse
}
var file_oauthclient_proto_depIdxs = []int32{
	1, // 0: oauthclient.v1.SetOAuthClientResponse.client:type_name -> oauthclient.v1.GetOAuthClientResponse
	0, // 1: oauthclient.v1.OAuthClientService.GetOAuthClient:input_type -> oauthclient.v1.GetOAuthClientRequest
	2, // 2: oauthclient.v1.OAuthClientService.SetOAuthClient:input_type -> oauthclient.v1.SetOAuthClientRequest
	4, // 3: oauthclient.v1.OAuthClientService.DeleteOAuthClient:input_type -> oauthclient.v1.DeleteOAuthClientRequest
	1, // 4: oauthclient.v1.OAuthClientService.GetOAuthClient:output_type -> oauthclient.v1.GetOAuthClientResponse
	3, // 5: oauthclient.v1.OAuthClientService.SetOAuthClient:output_type -> oauthclient.v1.SetOAuthClientResponse
	5, // 6: oauthclient.v1.OAuthClientService.DeleteOAuthClient:output_type -> oauthclient.v1.DeleteOAuthClientResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_oauthclient_proto_init() }
func file_oauthclient_proto_init() {
	if File_oauthclient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oauthclient_proto_rawDesc), len(file_oauthclient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oauthclient_proto_goTypes,
		DependencyIndexes: file_oauthclient_proto_depIdxs,
		MessageInfos:      file_oauthclient_proto_msgTypes,
	}.Build()
	File_oauthclient_proto = out.File
	file_oauthclient_proto_goTypes = nil
	file_oauthclient_proto_depIdxs = nil
}
