// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: query.proto

package queryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fairtier/workspace-api/proto/query/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// QueryServiceName is the fully-qualified name of the QueryService service.
	QueryServiceName = "query.v1.QueryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// QueryServiceExecuteQueryProcedure is the fully-qualified name of the QueryService's ExecuteQuery
	// RPC.
	QueryServiceExecuteQueryProcedure = "/query.v1.QueryService/ExecuteQuery"
	// QueryServiceListTablesProcedure is the fully-qualified name of the QueryService's ListTables RPC.
	QueryServiceListTablesProcedure = "/query.v1.QueryService/ListTables"
	// QueryServiceDescribeTableProcedure is the fully-qualified name of the QueryService's
	// DescribeTable RPC.
	QueryServiceDescribeTableProcedure = "/query.v1.QueryService/DescribeTable"
)

// QueryServiceClient is a client for the query.v1.QueryService service.
type QueryServiceClient interface {
	// ExecuteQuery runs a single SQL statement and returns up to max_rows rows.
	// The statement runs with the engine's own privileges (catalog access is
	// read-only at the Lakekeeper level; session-local temp objects are fine).
	ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error)
	// ListTables returns every namespace/table visible to the engine, for the
	// Console catalog tree. Backed by a constant information_schema query.
	ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error)
	// DescribeTable returns the column schema of a single table.
	DescribeTable(context.Context, *connect.Request[v1.DescribeTableRequest]) (*connect.Response[v1.DescribeTableResponse], error)
}

// NewQueryServiceClient constructs a client for the query.v1.QueryService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQueryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QueryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	queryServiceMethods := v1.File_query_proto.Services().ByName("QueryService").Methods()
	return &queryServiceClient{
		executeQuery: connect.NewClient[v1.ExecuteQueryRequest, v1.ExecuteQueryResponse](
			httpClient,
			baseURL+QueryServiceExecuteQueryProcedure,
			connect.WithSchema(queryServiceMethods.ByName("ExecuteQuery")),
			connect.WithClientOptions(opts...),
		),
		listTables: connect.NewClient[v1.ListTablesRequest, v1.ListTablesResponse](
			httpClient,
			baseURL+QueryServiceListTablesProcedure,
			connect.WithSchema(queryServiceMethods.ByName("ListTables")),
			connect.WithClientOptions(opts...),
		),
		describeTable: connect.NewClient[v1.DescribeTableRequest, v1.DescribeTableResponse](
			httpClient,
			baseURL+QueryServiceDescribeTableProcedure,
			connect.WithSchema(queryServiceMethods.ByName("DescribeTable")),
			connect.WithClientOptions(opts...),
		),
	}
}

// queryServiceClient implements QueryServiceClient.
type queryServiceClient struct {
	executeQuery  *connect.Client[v1.ExecuteQueryRequest, v1.ExecuteQueryResponse]
	listTables    *connect.Client[v1.ListTablesRequest, v1.ListTablesResponse]
	describeTable *connect.Client[v1.DescribeTableRequest, v1.DescribeTableResponse]
}

// ExecuteQuery calls query.v1.QueryService.ExecuteQuery.
func (c *queryServiceClient) ExecuteQuery(ctx context.Context, req *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error) {
	return c.executeQuery.CallUnary(ctx, req)
}

// ListTables calls query.v1.QueryService.ListTables.
func (c *queryServiceClient) ListTables(ctx context.Context, req *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error) {
	return c.listTables.CallUnary(ctx, req)
}

// DescribeTable calls query.v1.QueryService.DescribeTable.
func (c *queryServiceClient) DescribeTable(ctx context.Context, req *connect.Request[v1.DescribeTableRequest]) (*connect.Response[v1.DescribeTableResponse], error) {
	return c.describeTable.CallUnary(ctx, req)
}

// QueryServiceHandler is an implementation of the query.v1.QueryService service.
type QueryServiceHandler interface {
	// ExecuteQuery runs a single SQL statement and returns up to max_rows rows.
	// The statement runs with the engine's own privileges (catalog access is
	// read-only at the Lakekeeper level; session-local temp objects are fine).
	ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error)
	// ListTables returns every namespace/table visible to the engine, for the
	// Console catalog tree. Backed by a constant information_schema query.
	ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error)
	// DescribeTable returns the column schema of a single table.
	DescribeTable(context.Context, *connect.Request[v1.DescribeTableRequest]) (*connect.Response[v1.DescribeTableResponse], error)
}

// NewQueryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQueryServiceHandler(svc QueryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	queryServiceMethods := v1.File_query_proto.Services().ByName("QueryService").Methods()
	queryServiceExecuteQueryHandler := connect.NewUnaryHandler(
		QueryServiceExecuteQueryProcedure,
		svc.ExecuteQuery,
		connect.WithSchema(queryServiceMethods.ByName("ExecuteQuery")),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceListTablesHandler := connect.NewUnaryHandler(
		QueryServiceListTablesProcedure,
		svc.ListTables,
		connect.WithSchema(queryServiceMethods.ByName("ListTables")),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceDescribeTableHandler := connect.NewUnaryHandler(
		QueryServiceDescribeTableProcedure,
		svc.DescribeTable,
		connect.WithSchema(queryServiceMethods.ByName("DescribeTable")),
		connect.WithHandlerOptions(opts...),
	)
	return "/query.v1.QueryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QueryServiceExecuteQueryProcedure:
			queryServiceExecuteQueryHandler.ServeHTTP(w, r)
		case QueryServiceListTablesProcedure:
			queryServiceListTablesHandler.ServeHTTP(w, r)
		case QueryServiceDescribeTableProcedure:
			queryServiceDescribeTableHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQueryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedQueryServiceHandler struct{}

func (UnimplementedQueryServiceHandler) ExecuteQuery(context.Context, *connect.Request[v1.ExecuteQueryRequest]) (*connect.Response[v1.ExecuteQueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("query.v1.QueryService.ExecuteQuery is not implemented"))
}

func (UnimplementedQueryServiceHandler) ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("query.v1.QueryService.ListTables is not implemented"))
}

func (UnimplementedQueryServiceHandler) DescribeTable(context.Context, *connect.Request[v1.DescribeTableRequest]) (*connect.Response[v1.DescribeTableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("query.v1.QueryService.DescribeTable is not implemented"))
}
